// Public exports of the "charts-geo" group (re-exported by src/index.ts).
export { Chart, type ChartFace, type ChartFigure, type ChartForm, type ChartLayer, type ChartNote, type ChartProps, type ChartRecord } from '../components/chart/Chart'
export {
  ReportView,
  validateReport,
  type Report,
  type ReportColumnType,
  type ReportIssue,
  type ReportKpi,
  type ReportSection,
  type ReportTable,
  type ReportTone,
  type ReportViewProps,
} from '../components/report-view/ReportView'
export {
  LiveReportView,
  initialRunView,
  isTerminal as isTerminalRunStatus,
  mergeReport,
  phaseOf as runPhaseOf,
  reduceRunEvent,
  useRunEventStream,
  type LiveReportViewProps,
  type OpenRunStream,
  type RunEvent,
  type RunPhase,
  type RunStep,
  type RunStepState,
  type RunStreamCallbacks,
  type RunStreamOptions,
  type RunStreamState,
  type RunStreamStatus,
  type RunView,
} from '../components/live-report-view/LiveReportView'
export {
  RegionMap,
  useRegionMapState,
  type RegionGroup,
  type RegionMapProps,
  type RegionMapState,
  type RegionMapStateOptions,
  type RegionMapTotals,
} from '../components/region-map/RegionMap'
export {
  checkToneUsage,
  isToneName,
  resolveTint,
  tintStyle,
  toneNames,
  type TintReferences,
  type ToneContext,
  type ToneName,
} from '../components/tone-tint/toneTint'
export {
  RegionThemeError,
  RegionThemeProvider,
  SUBDIVISION_KINDS,
  createRegionThemeRegistry,
  defaultRegionThemeRegistry,
  deriveGeometry,
  flagEmoji,
  formatProfileAddress,
  formatProfileMoney,
  getCountryProfile,
  getCountryView,
  getFlagUrl,
  getIdentityColours,
  getIdentityTone,
  getLabelPoint,
  getMacroRegions,
  getSubdivision,
  isKnownSubdivision,
  labelPointOf,
  listCountryProfiles,
  listSubdivisions,
  registerCountryProfile,
  registerRegionTheme,
  unregisterCountryProfile,
  unregisterRegionTheme,
  useRegionThemeRegistry,
  validateCountryProfile,
  validateRegionThemeEntry,
  type BoundaryCollection,
  type BoundaryFeature,
  type CountryProfile,
  type DeriveOptions,
  type IdentityColours,
  type LonLat,
  type RegionThemeEntry,
  type RegionThemeRegistry,
  type SourceCitation,
  type Subdivision,
  type SubdivisionKind,
  type SubdivisionRecord,
} from '../components/region-theme'
// Country data modules: side-effect free, tree-shaken when unused.
export { brazilRegionTheme, register as registerBrazilRegionTheme } from '../components/region-theme/data/br'
export { brazilProfile as brazilCountryProfile, register as registerBrazilCountryProfile } from '../components/region-theme/data/br-profile'
