import type { ElementDefinition } from '../definition.ts'

/** `<ty-text-area>`: the TextArea's single source (spec: wave-1/text-area.md). */
export const textAreaDefinition = {
  tag: 'ty-text-area',
  name: 'TyTextArea',
  kind: 'enhancing',
  doc: 'Multi-line text entry. A native <textarea> inside, so input, keyboard and form participation are the platform\'s; the element adds the character counter, the over-limit state and auto-grow.',
  props: {
    value: { type: 'string', attribute: 'value', doc: 'Controlled text; the element mirrors it into the textarea (while the user types, the live value is the textarea\'s own).' },
    defaultValue: { type: 'string', attribute: 'default-value', doc: 'Initial text of an uncontrolled area, applied once on connect; a form reset returns to it.' },
    rows: { type: 'number', default: 3, attribute: 'rows', doc: 'Initial visible lines.' },
    autoGrow: { type: 'boolean', attribute: 'auto-grow', doc: 'Grows with the content up to `maxRows`, then scrolls.' },
    maxRows: { type: 'number', attribute: 'max-rows', doc: 'Growth limit of `autoGrow`; past it the area scrolls (`data-scrolling`).' },
    resize: { type: 'enum', values: ['vertical', 'none'], default: 'vertical', attribute: 'resize', doc: 'The native resize handle; `autoGrow` always disables it.' },
    maxLength: { type: 'number', attribute: 'max-length', doc: 'Counted for the counter and the over-limit state; typing is not cut off.' },
    showCounter: { type: 'boolean', attribute: 'show-counter', doc: 'A character counter under the area (needs `maxLength`).' },
    counterLabel: { type: 'string', default: '{count} of {max} characters', attribute: 'counter-label', doc: 'Counter template; `{count}` and `{max}` are filled in.' },
    overLimitLabel: { type: 'string', default: '{count} of {max} characters, {over} over the limit', attribute: 'over-limit-label', doc: 'Counter template past the limit; `{over}` is the excess.' },
    monospace: { type: 'boolean', attribute: 'monospace', doc: 'Mono family for code, keys or JSON.' },
    required: { type: 'boolean', attribute: 'required', doc: 'Native required.' },
    disabled: { type: 'boolean', attribute: 'disabled', doc: 'Native disabled.' },
    readOnly: { type: 'boolean', attribute: 'read-only', doc: 'Shown but not changeable.' },
    invalid: { type: 'boolean', attribute: 'invalid', doc: 'Painted and announced as invalid without an error message (a surrounding field marks it).' },
    name: { type: 'string', attribute: 'name', doc: 'Form field name.' },
    placeholder: { type: 'string', attribute: 'placeholder', doc: 'Native placeholder.' },
    accessibleLabel: { type: 'string', attribute: 'accessible-label', doc: 'Accessible name when there is no visible label.' },
    labelledBy: { type: 'string', attribute: 'labelled-by', doc: '`aria-labelledby` from a surrounding field (used when there is no visible label and no `accessibleLabel`).' },
    describedBy: { type: 'string', attribute: 'described-by', doc: '`aria-describedby` from a surrounding field, joined before the area\'s own parts.' },
    controlId: { type: 'string', attribute: 'control-id', doc: 'Explicit id of the control (a surrounding field\'s control id); `<instance>-input` otherwise.' },
    testId: { type: 'string', attribute: 'test-id', doc: 'Test hook on the root (`data-testid`).' },
  },
  events: [{ type: 'input', kind: 'native', detail: { value: 'string' }, reactProp: 'onChange', doc: 'The native input of the textarea; `value` is the whole text.' }],
  slots: {
    label: { doc: 'The visible label, targeting the area.' },
    hint: { doc: 'Help text under the area, announced as the description.' },
    error: { doc: 'The error message; marks the area invalid and is announced.' },
  },
  anatomy: {
    tag: 'div',
    class: 'ty-text-area',
    attrs: {
      'data-resize': { prop: 'resize' },
      'data-monospace': { prop: 'monospace', kind: 'flag' },
      'data-auto-grow': { prop: 'autoGrow', kind: 'flag' },
      'data-invalid': { value: '', when: ['invalid|slot:error'] },
      'data-readonly': { prop: 'readOnly', kind: 'flag' },
      'data-disabled': { prop: 'disabled', kind: 'flag' },
      'data-testid': { prop: 'testId' },
    },
    children: [
      {
        tag: 'label',
        class: 'ty-text-area__label',
        when: ['slot:label'],
        attrs: { for: { idref: 'input', prop: 'controlId' } },
        children: [{ slot: 'label' }],
      },
      {
        tag: 'p',
        class: 'ty-text-area__hint',
        when: ['slot:hint'],
        attrs: { id: { idref: 'hint' } },
        children: [{ slot: 'hint' }],
      },
      {
        tag: 'textarea',
        class: 'ty-text-area__input',
        attrs: {
          id: { idref: 'input', prop: 'controlId' },
          rows: { prop: 'rows' },
          name: { prop: 'name' },
          placeholder: { prop: 'placeholder' },
          disabled: { prop: 'disabled', kind: 'boolean-attr' },
          readonly: { prop: 'readOnly', kind: 'boolean-attr' },
          required: { prop: 'required', kind: 'boolean-attr' },
          'aria-label': { prop: 'accessibleLabel', when: ['!slot:label'] },
          'aria-labelledby': { prop: 'labelledBy', when: ['!slot:label', '!accessibleLabel'] },
          'aria-describedby': {
            idrefs: [
              { prop: 'describedBy' },
              { id: 'hint', when: ['slot:hint'] },
              { id: 'error', when: ['slot:error'] },
              { id: 'counter', when: ['showCounter', 'maxLength'] },
            ],
          },
          'aria-invalid': { value: 'true', when: ['invalid|slot:error'] },
        },
      },
      {
        tag: 'p',
        class: 'ty-text-area__error',
        when: ['slot:error'],
        attrs: { id: { idref: 'error' } },
        children: [
          {
            tag: 'svg',
            class: 'ty-icon',
            attrs: {
              'aria-hidden': { value: 'true' },
              focusable: { value: 'false' },
              width: { value: '24' },
              height: { value: '24' },
              viewBox: { value: '0 0 24 24' },
              fill: { value: 'none' },
              stroke: { value: 'currentColor' },
              'stroke-width': { value: '2' },
              'stroke-linecap': { value: 'round' },
              'stroke-linejoin': { value: 'round' },
            },
            children: [
              { tag: 'circle', attrs: { cx: { value: '12' }, cy: { value: '12' }, r: { value: '10' } } },
              { tag: 'line', attrs: { x1: { value: '12' }, y1: { value: '8' }, x2: { value: '12' }, y2: { value: '12' } } },
              { tag: 'line', attrs: { x1: { value: '12' }, y1: { value: '16' }, x2: { value: '12.01' }, y2: { value: '16' } } },
            ],
          },
          { tag: 'span', children: [{ slot: 'error' }] },
        ],
      },
      {
        tag: 'p',
        class: 'ty-text-area__counter',
        when: ['showCounter', 'maxLength'],
        attrs: { id: { idref: 'counter' } },
      },
    ],
  },
  examples: [
    { name: 'labelled', props: {}, slots: { label: 'Notes' } },
    { name: 'hint-and-placeholder', props: { name: 'notes', placeholder: 'Write a summary' }, slots: { label: 'Notes', hint: 'Shown on the canvas' } },
    { name: 'error', props: { value: 'Draft' }, slots: { label: 'Abstract', error: 'Required' } },
    { name: 'counter', props: { value: 'Hello', maxLength: 500, showCounter: true }, slots: { label: 'Bio' } },
    { name: 'monospace-read-only', props: { monospace: true, resize: 'none', readOnly: true, value: '{ "a": 1 }' }, slots: { label: 'JSON' } },
    { name: 'auto-grow', props: { autoGrow: true, maxRows: 6, rows: 2 }, slots: { label: 'Log' } },
    { name: 'disabled-unlabelled', props: { disabled: true, accessibleLabel: 'Notes', describedBy: 'external-hint', testId: 'notes' }, slots: {} },
  ],
} as const satisfies ElementDefinition
