// Conversion between resolved themes and W3C Design Tokens Community Group
// (DTCG, 2025.10 format) trees: colour objects with `colorSpace` and
// `components`, dimension objects with `value` and `unit`.
// Every generated token carries its CSS custom property name in
// `$extensions["app.fakhir"].cssName` so any DTCG tool maps it back exactly.

import { toHex, type Rgba } from './color.ts'
import { RAMP_STEPS, type Density, DENSITIES, type ResolvedTheme, type ShadowLayer } from './theme.ts'

export interface DtcgColor {
  colorSpace: 'srgb'
  components: [number, number, number]
  alpha?: number
  hex: string
}

type Tree = { [key: string]: Tree | unknown }

const r4 = (v: number) => Math.round(v * 10000) / 10000

export function toDtcgColor(c: Rgba): DtcgColor {
  const out: DtcgColor = { colorSpace: 'srgb', components: [r4(c.r), r4(c.g), r4(c.b)], hex: toHex(c) }
  if (c.a < 1) out.alpha = r4(c.a)
  return out
}

export function fromDtcgColor(v: DtcgColor | string): Rgba {
  if (typeof v === 'string') {
    const h = v.replace('#', '')
    return { r: parseInt(h.slice(0, 2), 16) / 255, g: parseInt(h.slice(2, 4), 16) / 255, b: parseInt(h.slice(4, 6), 16) / 255, a: 1 }
  }
  const [r, g, b] = v.components
  return { r, g, b, a: v.alpha ?? 1 }
}

const px = (value: number) => ({ value, unit: 'px' as const })
const ext = (cssName: string) => ({ 'app.fakhir': { cssName } })

function shadowValue(layers: ShadowLayer[]) {
  return layers.map((l) => ({
    color: toDtcgColor(l.color),
    offsetX: px(l.x),
    offsetY: px(l.y),
    blur: px(l.blur),
    spread: px(l.spread),
    ...(l.inset ? { inset: true } : {}),
  }))
}

/** DTCG tree for one resolved theme and mode. */
export function themeToDtcg(t: ResolvedTheme): Tree {
  const color: Tree = { $type: 'color' }
  for (const [name, c] of Object.entries(t.colors)) {
    color[name] = { $value: toDtcgColor(c), $extensions: ext(`--fk-${name}`) }
  }
  const ramp: Tree = { $type: 'color' }
  for (const [seed, steps] of Object.entries(t.ramps)) {
    const group: Tree = {}
    for (const step of RAMP_STEPS) group[String(step)] = { $value: toDtcgColor(steps[step]), $extensions: ext(`--fk-${seed}-${step}`) }
    ramp[seed] = group
  }
  const shadow: Tree = { $type: 'shadow' }
  for (const [name, layers] of Object.entries(t.shadows)) {
    shadow[name] = { $value: shadowValue(layers), $extensions: ext(`--fk-shadow-${name}`) }
  }
  const dimension: Tree = { $type: 'dimension' }
  for (const [name, v] of Object.entries(t.dimensions)) dimension[name] = { $value: px(v), $extensions: ext(`--fk-${name}`) }
  const number: Tree = { $type: 'number' }
  for (const [name, v] of Object.entries(t.numbers)) number[name] = { $value: v, $extensions: ext(`--fk-${name}`) }
  return {
    $description: `Theme ${t.name}, ${t.mode} mode, ${t.contrast} contrast. Generated by @fakhir/tokens.`,
    color,
    ramp,
    gradient: {
      $type: 'gradient',
      cta: {
        $value: t.cta.stops.map((s, i, all) => ({ color: toDtcgColor(s), position: all.length === 1 ? 0 : r4(i / (all.length - 1)) })),
        $extensions: { 'app.fakhir': { cssName: '--fk-cta', angle: t.cta.angle } },
      },
    },
    shadow,
    dimension,
    number,
  }
}

/** DTCG tree for one density step. */
export function densityToDtcg(density: Density): Tree {
  const group: Tree = { $type: 'dimension' }
  for (const [k, v] of Object.entries(DENSITIES[density])) {
    group[k] =
      k === 'density'
        ? { $type: 'number', $value: v, $extensions: ext(`--fk-${k}`) }
        : { $value: px(v), $extensions: ext(`--fk-${k}`) }
  }
  return { $description: `Density ${density}.`, density: group }
}
