// Turns the flag-icons SVGs (MIT, Copyright (c) 2013 Panayiotis Lipiridis; see
// THIRD_PARTY_NOTICES.md) into one ES module per flag and aspect under
// src/flags/art/ (generated, git-ignored), plus the loader table and the code
// list. Each flag is its own dynamic-import chunk, so rendering one flag
// never loads the others. The artwork is kept as drawn; the script only
// drops whitespace between tags and the root id, and prefixes internal ids
// with the aspect so a 4x3 and a 1x1 flag can share a page.
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const pkg = join(here, '..')
const require = createRequire(join(pkg, 'package.json'))
const source = join(dirname(require.resolve('flag-icons/package.json')), 'flags')
const version = JSON.parse(readFileSync(require.resolve('flag-icons/package.json'), 'utf8')).version
const out = join(pkg, 'src', 'flags', 'art')

const ASPECTS = ['4x3', '1x1']

function clean(svg, aspect, code) {
  return svg
    .replace(/<\?xml[^>]*>/, '')
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/\s+id="flag-icons-[\w-]+"/, '')
    .replace(/(\bid="|url\(#|href="#)([\w-]+)([")])/g, (_m, a, id, b) => `${a}ty-flag-${aspect}-${id}${b}`)
    .replace(/>\s+</g, '><')
    .replace(/\s{2,}/g, ' ')
    .trim()
    .replace(/^<svg /, `<svg data-flag="${code}" `)
}

rmSync(out, { recursive: true, force: true })
const codes = readdirSync(join(source, '4x3'))
  .filter((f) => f.endsWith('.svg'))
  .map((f) => f.slice(0, -4))
  .sort()

let bytes = 0
for (const aspect of ASPECTS) {
  mkdirSync(join(out, aspect), { recursive: true })
  for (const code of codes) {
    const svg = clean(readFileSync(join(source, aspect, `${code}.svg`), 'utf8'), aspect, code)
    bytes += svg.length
    writeFileSync(join(out, aspect, `${code}.ts`), `// Generated from flag-icons ${version} (MIT). Do not edit.\nexport default ${JSON.stringify(svg)}\n`)
  }
}

const loaders = (aspect) =>
  `export const loaders${aspect.replace('x', 'by')}: Record<FlagCode, FlagLoader> = {\n${codes.map((c) => `  ${JSON.stringify(c)}: () => import('./${aspect}/${c}'),`).join('\n')}\n}\n`

writeFileSync(
  join(out, 'index.ts'),
  `// Generated by scripts/build-flags.mjs from flag-icons ${version} (MIT). Do not edit.\n` +
    `export const FLAG_ICONS_VERSION = ${JSON.stringify(version)}\n` +
    `/** Every flag code: ISO 3166-1 alpha-2, the subdivisions and the organisations flag-icons draws. */\n` +
    `export const FLAG_CODES = ${JSON.stringify(codes)} as const\n` +
    `export type FlagCode = (typeof FLAG_CODES)[number]\n` +
    `export type FlagLoader = () => Promise<{ default: string }>\n` +
    ASPECTS.map(loaders).join(''),
)

console.log(`ui: wrote src/flags/art (${codes.length} flags x ${ASPECTS.length} aspects, ${Math.round(bytes / 1024)} kB of SVG, flag-icons ${version})`)
