// Flattens src/styles.css (inlining its relative @imports) into
// dist/styles.css and into src/estilos.generated.ts (PRINT_CSS), which
// LivroPrint injects so server-rendered pages (PDF, EPUB) carry their CSS.
// --check: fail if src/estilos.generated.ts is out of date (no writes).
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const pkg = join(dirname(fileURLToPath(import.meta.url)), '..')

function flatten(file, seen = new Set()) {
  if (seen.has(file)) return ''
  seen.add(file)
  return readFileSync(file, 'utf8').replace(/@import\s+['"](\.[^'"]+)['"]\s*;/g, (_, rel) => flatten(resolve(dirname(file), rel), seen))
}

const css = flatten(join(pkg, 'src', 'styles.css'))
const semComentarios = css.replace(/\/\*[\s\S]*?\*\//g, '')
if (/@import/.test(semComentarios)) throw new Error('print: an @import was left unresolved')
const compacto = semComentarios
  .split('\n')
  .map((l) => l.trimEnd())
  .filter((l) => l.trim())
  .join('\n')
const ts = `// Generated by scripts/build-css.mjs from src/styles.css. Do not edit.\n// The component stylesheet, injected by LivroPrint so server-rendered pages carry it.\nexport const PRINT_CSS = ${JSON.stringify(compacto)}\n`
const alvoTs = join(pkg, 'src', 'estilos.generated.ts')

if (process.argv.includes('--check')) {
  if (!existsSync(alvoTs) || readFileSync(alvoTs, 'utf8') !== ts) {
    console.error('print: src/estilos.generated.ts is out of date; run npm run build -w @datatechsolutions/tympan-print')
    process.exit(1)
  }
  console.log('print: src/estilos.generated.ts is up to date')
} else {
  writeFileSync(alvoTs, ts)
  mkdirSync(join(pkg, 'dist'), { recursive: true })
  writeFileSync(join(pkg, 'dist', 'styles.css'), css)
  console.log(`print: wrote dist/styles.css and src/estilos.generated.ts (${Math.round(compacto.length / 1024)} kB)`)
}
