// Regenerates src/brand/datatech-dados.ts from the official production SVGs of
// the Datatech Solutions mark (text outlined, no filters), kept with the
// Brasil Real book: node scripts/gerar-marcas.mjs <diagramacao/logo folder>.
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const pasta = process.argv[2]
if (!pasta) throw new Error('usage: node scripts/gerar-marcas.mjs <folder with datatech-*.svg>')
const variantes = {
  cor: 'datatech-cor.svg',
  'cor-fundo-escuro': 'datatech-cor-fundo-escuro.svg',
  'mono-escuro': 'datatech-mono-escuro.svg',
  'mono-claro': 'datatech-mono-claro.svg',
  badge: 'datatech-badge.svg',
  'badge-mono-escuro': 'datatech-badge-mono-escuro.svg',
}
const out = {}
for (const [nome, arq] of Object.entries(variantes)) {
  const svg = readFileSync(join(pasta, arq), 'utf8')
  const viewBox = /viewBox="([^"]+)"/.exec(svg)[1]
  const inner = svg
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/<title>[\s\S]*?<\/title>/g, '')
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/\s*\n\s*/g, '')
    .trim()
  const ids = [...inner.matchAll(/id="([^"]+)"/g)].map((m) => m[1])
  out[nome] = { viewBox, inner, ids }
}
const ts = `// Official Datatech Solutions mark (publisher), generated by scripts/gerar-marcas.mjs from
// the print versions in brasil-real/volumes/v0-guia/diagramacao/logo/ (source:
// ~/datatech/datatechsolutions-logo; text outlined from Inter, OFL; no shadow filter).
// Do not redraw or recolour. Ids are prefixed per instance at render time.
export const DATATECH = ${JSON.stringify(out, null, 2)} as const
`
writeFileSync(new URL('../src/brand/datatech-dados.ts', import.meta.url), ts)
console.log('wrote src/brand/datatech-dados.ts')
