// Generated by tools/elements/generate.mjs from packages/ui/src/elements/*/definition.ts. Do not edit.
//
// Every example of every enhancing element, rendered by the generated
// Dioxus binding (SSR), must match the reference HTML the definition
// renders (tests/fixtures), which the React wrapper and the element
// itself are tested against on the TypeScript side.

use dioxus::prelude::*;
use tympan_dioxus::*;

use super::common;

#[test]
fn action_menu_closed() {
    fn app() -> Element {
        rsx! { TyActionMenu { label: "Item actions", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-action-menu/closed.html");
}

#[test]
fn action_menu_own_trigger() {
    fn app() -> Element {
        rsx! { TyActionMenu { label: "Run actions", instance: "i", trigger: rsx! { "More" }, } }
    }
    common::assert_matches_fixture(app, "ty-action-menu/own-trigger.html");
}

#[test]
fn action_menu_context() {
    fn app() -> Element {
        rsx! { TyActionMenu { mode: ActionMenuMode::Context, label: "File actions", instance: "i", trigger: rsx! { "report.csv" }, } }
    }
    common::assert_matches_fixture(app, "ty-action-menu/context.html");
}

#[test]
fn action_menu_translated() {
    fn app() -> Element {
        rsx! { TyActionMenu { label: "Ações do item", trigger_label: "Mais ações", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-action-menu/translated.html");
}

#[test]
fn avatar_initials() {
    fn app() -> Element {
        rsx! { TyAvatar { name: "Natália Mesquita", fallback_text: "NM", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-avatar/initials.html");
}

#[test]
fn avatar_image() {
    fn app() -> Element {
        rsx! { TyAvatar { src: "/avatars/natalia.png", name: "Natália Mesquita", fallback_text: "NM", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-avatar/image.html");
}

#[test]
fn avatar_agent() {
    fn app() -> Element {
        rsx! { TyAvatar { actor_kind: AvatarActorKind::Agent, name: "stage-counter", size: AvatarSize::Small, instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-avatar/agent.html");
}

#[test]
fn avatar_decorative_neutral() {
    fn app() -> Element {
        rsx! { TyAvatar { decorative: true, fallback_text: "NM", tint: AvatarTint::Neutral, instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-avatar/decorative-neutral.html");
}

#[test]
fn avatar_pressable() {
    fn app() -> Element {
        rsx! { TyAvatar { pressable: true, name: "Natália Mesquita", fallback_text: "NM", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-avatar/pressable.html");
}

#[test]
fn avatar_link() {
    fn app() -> Element {
        rsx! { TyAvatar { href: "/users/natalia", name: "Natália Mesquita", src: "/avatars/natalia.png", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-avatar/link.html");
}

#[test]
fn avatar_translated_action() {
    fn app() -> Element {
        rsx! { TyAvatar { pressable: true, name: "Natália Mesquita", fallback_text: "NM", action_label: "Abrir perfil de {{name}}", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-avatar/translated-action.html");
}

#[test]
fn breadcrumbs_auto_empty() {
    fn app() -> Element {
        rsx! { TyBreadcrumbs { instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-breadcrumbs/auto-empty.html");
}

#[test]
fn breadcrumbs_trail_empty() {
    fn app() -> Element {
        rsx! { TyBreadcrumbs { mode: BreadcrumbsMode::Trail, instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-breadcrumbs/trail-empty.html");
}

#[test]
fn breadcrumbs_compact_bar() {
    fn app() -> Element {
        rsx! { TyBreadcrumbs { mode: BreadcrumbsMode::Compact, instance: "i", center: rsx! { "Sources" }, actions: rsx! { "Share" }, } }
    }
    common::assert_matches_fixture(app, "ty-breadcrumbs/compact-bar.html");
}

#[test]
fn currency_field_count() {
    fn app() -> Element {
        rsx! { TyCurrencyField { decimals: 0.0f64, locale: "pt-BR", value: "3000", name: "seats", instance: "i", label: rsx! { "Vagas" }, } }
    }
    common::assert_matches_fixture(app, "ty-currency-field/count.html");
}

#[test]
fn currency_field_brl() {
    fn app() -> Element {
        rsx! { TyCurrencyField { currency: "BRL", locale: "pt-BR", value: "1500000.5", name: "price", placeholder: "0,00", instance: "i", label: rsx! { "Preço" }, hint: rsx! { "Em reais" }, } }
    }
    common::assert_matches_fixture(app, "ty-currency-field/brl.html");
}

#[test]
fn currency_field_usd() {
    fn app() -> Element {
        rsx! { TyCurrencyField { currency: "USD", locale: "en-US", value: "1500000.5", name: "amount", instance: "i", label: rsx! { "Amount" }, } }
    }
    common::assert_matches_fixture(app, "ty-currency-field/usd.html");
}

#[test]
fn currency_field_display() {
    fn app() -> Element {
        rsx! { TyCurrencyField { size: CurrencyFieldSize::Display, currency: "BRL", locale: "pt-BR", value: "99.9", instance: "i", label: rsx! { "Total" }, } }
    }
    common::assert_matches_fixture(app, "ty-currency-field/display.html");
}

#[test]
fn currency_field_error() {
    fn app() -> Element {
        rsx! { TyCurrencyField { value: "12", required: true, instance: "i", label: rsx! { "Amount" }, error: rsx! { "Required" }, } }
    }
    common::assert_matches_fixture(app, "ty-currency-field/error.html");
}

#[test]
fn currency_field_disabled_unlabelled() {
    fn app() -> Element {
        rsx! { TyCurrencyField { disabled: true, accessible_label: "Amount", test_id: "amount", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-currency-field/disabled-unlabelled.html");
}

#[test]
fn heading_page_title() {
    fn app() -> Element {
        rsx! { TyHeading { instance: "i", "Sources" } }
    }
    common::assert_matches_fixture(app, "ty-heading/page-title.html");
}

#[test]
fn heading_level_3() {
    fn app() -> Element {
        rsx! { TyHeading { level: HeadingLevel::V3, instance: "i", "Field mapping" } }
    }
    common::assert_matches_fixture(app, "ty-heading/level-3.html");
}

#[test]
fn heading_small_level_big_step() {
    fn app() -> Element {
        rsx! { TyHeading { level: HeadingLevel::V2, appearance: HeadingAppearance::H1, instance: "i", "Workspace" } }
    }
    common::assert_matches_fixture(app, "ty-heading/small-level-big-step.html");
}

#[test]
fn heading_eyebrow() {
    fn app() -> Element {
        rsx! { TyHeading { level: HeadingLevel::V2, eyebrow: "Datasets", instance: "i", "Revenue by state" } }
    }
    common::assert_matches_fixture(app, "ty-heading/eyebrow.html");
}

#[test]
fn heading_label_step() {
    fn app() -> Element {
        rsx! { TyHeading { level: HeadingLevel::V4, appearance: HeadingAppearance::Label, instance: "i", "Owner" } }
    }
    common::assert_matches_fixture(app, "ty-heading/label-step.html");
}

#[test]
fn heading_subheading() {
    fn app() -> Element {
        rsx! { TyHeading { level: HeadingLevel::V2, appearance: HeadingAppearance::H3, instance: "i", "Recent runs" } }
    }
    common::assert_matches_fixture(app, "ty-heading/subheading.html");
}

#[test]
fn notification_center_closed() {
    fn app() -> Element {
        rsx! { TyNotificationCenter { instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-notification-center/closed.html");
}

#[test]
fn notification_center_open_empty() {
    fn app() -> Element {
        rsx! { TyNotificationCenter { open: true, instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-notification-center/open-empty.html");
}

#[test]
fn notification_center_translated() {
    fn app() -> Element {
        rsx! { TyNotificationCenter { open: true, bell_label: "Notificações", title_label: "Notificações", clear_all_label: "Limpar tudo", close_label: "Fechar", empty_label: "Não há notificações nesta sessão.", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-notification-center/translated.html");
}

#[test]
fn page_header_minimal() {
    fn app() -> Element {
        rsx! { TyPageHeader { title: "Sources", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-page-header/minimal.html");
}

#[test]
fn page_header_reading_summary() {
    fn app() -> Element {
        rsx! { TyPageHeader { title: "Sources", eyebrow: "Datasets", summary: "Every dataset this workspace reads, and when each was last synced.", instance: "i", meta: rsx! { "Owner: Data team" }, } }
    }
    common::assert_matches_fixture(app, "ty-page-header/reading-summary.html");
}

#[test]
fn page_header_breadcrumbs_actions() {
    fn app() -> Element {
        rsx! { TyPageHeader { title: "Sources", instance: "i", breadcrumbs: rsx! { "Datasets" }, actions: rsx! { "Add source" }, icon: rsx! { "◈" }, } }
    }
    common::assert_matches_fixture(app, "ty-page-header/breadcrumbs-actions.html");
}

#[test]
fn page_header_section_scale() {
    fn app() -> Element {
        rsx! { TyPageHeader { title: "Connection", heading_level: PageHeaderHeadingLevel::V2, scale: PageHeaderScale::Section, instance: "i", "Status: connected" } }
    }
    common::assert_matches_fixture(app, "ty-page-header/section-scale.html");
}

#[test]
fn page_header_display() {
    fn app() -> Element {
        rsx! { TyPageHeader { title: "Welcome to Alidade", scale: PageHeaderScale::Display, summary: "Sign in to continue.", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-page-header/display.html");
}

#[test]
fn page_header_editable() {
    fn app() -> Element {
        rsx! { TyPageHeader { editable: true, value: "Untitled report", title_placeholder: "Name the report", title_label: "Report title", instance: "i", actions: rsx! { "Share" }, } }
    }
    common::assert_matches_fixture(app, "ty-page-header/editable.html");
}

#[test]
fn page_header_editable_error() {
    fn app() -> Element {
        rsx! { TyPageHeader { editable: true, title_placeholder: "Name the report", title_label: "Report title", instance: "i", error: rsx! { "A name is required." }, } }
    }
    common::assert_matches_fixture(app, "ty-page-header/editable-error.html");
}

#[test]
fn progress_bar_determinate() {
    fn app() -> Element {
        rsx! { TyProgressBar { value: 40.0f64, label: "Upload", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-progress-bar/determinate.html");
}

#[test]
fn progress_bar_custom_value_label() {
    fn app() -> Element {
        rsx! { TyProgressBar { value: 3.0f64, max_value: 8.0f64, value_label: "3 of 8 steps", label: "Setup", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-progress-bar/custom-value-label.html");
}

#[test]
fn progress_bar_indeterminate() {
    fn app() -> Element {
        rsx! { TyProgressBar { indeterminate: true, label: "Import", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-progress-bar/indeterminate.html");
}

#[test]
fn progress_bar_complete_success_thin() {
    fn app() -> Element {
        rsx! { TyProgressBar { value: 100.0f64, label: "Upload", tone: ProgressBarTone::Success, size: ProgressBarSize::Thin, instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-progress-bar/complete-success-thin.html");
}

#[test]
fn progress_bar_unlabelled_hidden_value() {
    fn app() -> Element {
        rsx! { TyProgressBar { value: 20.0f64, accessible_label: "Storage used", show_value: "false", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-progress-bar/unlabelled-hidden-value.html");
}

#[test]
fn section_heading_title() {
    fn app() -> Element {
        rsx! { TySectionHeading { title: "Members", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-section-heading/title.html");
}

#[test]
fn section_heading_level_3_subtitle() {
    fn app() -> Element {
        rsx! { TySectionHeading { title: "API keys", level: SectionHeadingLevel::V3, subtitle: "Keys of every integration", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-section-heading/level-3-subtitle.html");
}

#[test]
fn section_heading_icon_trailing() {
    fn app() -> Element {
        rsx! { TySectionHeading { title: "Webhooks", instance: "i", icon: rsx! { "⚡" }, trailing: rsx! { "Add" }, } }
    }
    common::assert_matches_fixture(app, "ty-section-heading/icon-trailing.html");
}

#[test]
fn section_heading_truncate() {
    fn app() -> Element {
        rsx! { TySectionHeading { title: "A section name that runs well past the width of its container", truncate: true, instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-section-heading/truncate.html");
}

#[test]
fn section_heading_extra() {
    fn app() -> Element {
        rsx! { TySectionHeading { title: "Filters", instance: "i", trailing: rsx! { "Clear all" }, "Status: active" } }
    }
    common::assert_matches_fixture(app, "ty-section-heading/extra.html");
}

#[test]
fn segmented_control_period_week() {
    fn app() -> Element {
        rsx! { TySegmentedControl { label: "Period", options: "[\"Day\",\"Week\",\"Month\"]", value: "Week", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-segmented-control/period-week.html");
}

#[test]
fn segmented_control_objects_compact() {
    fn app() -> Element {
        rsx! { TySegmentedControl { label: "View", size: SegmentedControlSize::Compact, default_value: "chart", options: "[{{\"value\":\"table\",\"label\":\"Table\"}},{{\"value\":\"chart\",\"label\":\"Chart\"}}]", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-segmented-control/objects-compact.html");
}

#[test]
fn segmented_control_full_width_large() {
    fn app() -> Element {
        rsx! { TySegmentedControl { label: "Mode", size: SegmentedControlSize::Large, full_width: true, options: "[\"Preview\",\"Code\"]", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-segmented-control/full-width-large.html");
}

#[test]
fn segmented_control_disabled() {
    fn app() -> Element {
        rsx! { TySegmentedControl { label: "Period", disabled: true, value: "Day", options: "[\"Day\",\"Week\"]", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-segmented-control/disabled.html");
}

#[test]
fn segmented_control_icon_only() {
    fn app() -> Element {
        rsx! { TySegmentedControl { label: "Layout", icon_only: true, value: "grid", options: "[{{\"value\":\"list\",\"label\":\"List\",\"icon\":\"M8 6h13M8 12h13M8 18h13M3 6h.01M3 12h.01M3 18h.01\"}},{{\"value\":\"grid\",\"label\":\"Grid\",\"icon\":\"M3 3h7v7H3zM14 3h7v7h-7zM14 14h7v7h-7zM3 14h7v7H3z\"}}]", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-segmented-control/icon-only.html");
}

#[test]
fn skip_link_default() {
    fn app() -> Element {
        rsx! { TySkipLink { instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-skip-link/default.html");
}

#[test]
fn skip_link_translated() {
    fn app() -> Element {
        rsx! { TySkipLink { target_id: "conteudo", label: "Ir para o conteúdo", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-skip-link/translated.html");
}

#[test]
fn tabs_horizontal() {
    fn app() -> Element {
        rsx! { TyTabs { label: "Run sections", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-tabs/horizontal.html");
}

#[test]
fn tabs_vertical() {
    fn app() -> Element {
        rsx! { TyTabs { label: "Run sections", orientation: TabsOrientation::Vertical, instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-tabs/vertical.html");
}

#[test]
fn tabs_manual() {
    fn app() -> Element {
        rsx! { TyTabs { label: "Run sections", activation: TabsActivation::Manual, instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-tabs/manual.html");
}

#[test]
fn button_secondary() {
    fn app() -> Element {
        rsx! { TyButton { instance: "i", "Cancel" } }
    }
    common::assert_matches_fixture(app, "ty-button/secondary.html");
}

#[test]
fn button_primary_large() {
    fn app() -> Element {
        rsx! { TyButton { variant: ButtonVariant::Primary, size: ButtonSize::Large, instance: "i", "Save" } }
    }
    common::assert_matches_fixture(app, "ty-button/primary-large.html");
}

#[test]
fn button_submit() {
    fn app() -> Element {
        rsx! { TyButton { variant: ButtonVariant::Primary, r#type: ButtonType::Submit, name: "intent", value: "publish", instance: "i", "Publish" } }
    }
    common::assert_matches_fixture(app, "ty-button/submit.html");
}

#[test]
fn button_busy() {
    fn app() -> Element {
        rsx! { TyButton { variant: ButtonVariant::Primary, busy: true, instance: "i", "Saving" } }
    }
    common::assert_matches_fixture(app, "ty-button/busy.html");
}

#[test]
fn button_danger_disabled() {
    fn app() -> Element {
        rsx! { TyButton { variant: ButtonVariant::Danger, disabled: true, instance: "i", "Delete" } }
    }
    common::assert_matches_fixture(app, "ty-button/danger-disabled.html");
}

#[test]
fn button_icon_only() {
    fn app() -> Element {
        rsx! { TyButton { variant: ButtonVariant::Quiet, icon_only: true, shape: ButtonShape::Circle, accessible_label: "Close", instance: "i", icon: rsx! { "×" }, } }
    }
    common::assert_matches_fixture(app, "ty-button/icon-only.html");
}

#[test]
fn button_full_width_pill() {
    fn app() -> Element {
        rsx! { TyButton { full_width: true, shape: ButtonShape::Pill, instance: "i", trailing_icon: rsx! { "→" }, "Continue" } }
    }
    common::assert_matches_fixture(app, "ty-button/full-width-pill.html");
}

#[test]
fn button_toggle() {
    fn app() -> Element {
        rsx! { TyButton { variant: ButtonVariant::Quiet, pressed: "false", expanded: "false", controls: "panel", haspopup: "dialog", test_id: "toggle", instance: "i", "Filters" } }
    }
    common::assert_matches_fixture(app, "ty-button/toggle.html");
}

#[test]
fn checkbox_off() {
    fn app() -> Element {
        rsx! { TyCheckbox { instance: "i", "Notify me" } }
    }
    common::assert_matches_fixture(app, "ty-checkbox/off.html");
}

#[test]
fn checkbox_on_with_description() {
    fn app() -> Element {
        rsx! { TyCheckbox { checked: true, name: "notify", value: "email", instance: "i", description: rsx! { "By email" }, "Notify me" } }
    }
    common::assert_matches_fixture(app, "ty-checkbox/on-with-description.html");
}

#[test]
fn checkbox_bare() {
    fn app() -> Element {
        rsx! { TyCheckbox { appearance: CheckboxAppearance::Bare, test_id: "newsletter", instance: "i", "Newsletter" } }
    }
    common::assert_matches_fixture(app, "ty-checkbox/bare.html");
}

#[test]
fn checkbox_indeterminate() {
    fn app() -> Element {
        rsx! { TyCheckbox { indeterminate: true, instance: "i", "Select all" } }
    }
    common::assert_matches_fixture(app, "ty-checkbox/indeterminate.html");
}

#[test]
fn checkbox_invalid_required() {
    fn app() -> Element {
        rsx! { TyCheckbox { required: true, instance: "i", error: rsx! { "Required" }, "I accept the terms" } }
    }
    common::assert_matches_fixture(app, "ty-checkbox/invalid-required.html");
}

#[test]
fn checkbox_disabled_unlabelled() {
    fn app() -> Element {
        rsx! { TyCheckbox { disabled: true, accessible_label: "Notifications", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-checkbox/disabled-unlabelled.html");
}

#[test]
fn drawer_closed() {
    fn app() -> Element {
        rsx! { TyDrawer { instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-drawer/closed.html");
}

#[test]
fn drawer_bottom() {
    fn app() -> Element {
        rsx! { TyDrawer { open: true, instance: "i", title: rsx! { "Language" }, "Pick a locale." } }
    }
    common::assert_matches_fixture(app, "ty-drawer/bottom.html");
}

#[test]
fn drawer_end_wide() {
    fn app() -> Element {
        rsx! { TyDrawer { open: true, placement: DrawerPlacement::End, width: DrawerWidth::Wide, instance: "i", title: rsx! { "Run details" }, "Timeline." } }
    }
    common::assert_matches_fixture(app, "ty-drawer/end-wide.html");
}

#[test]
fn drawer_no_handle() {
    fn app() -> Element {
        rsx! { TyDrawer { open: true, show_handle: "false", instance: "i", title: rsx! { "Filters" }, "Filter rows." } }
    }
    common::assert_matches_fixture(app, "ty-drawer/no-handle.html");
}

#[test]
fn drawer_not_dismissible() {
    fn app() -> Element {
        rsx! { TyDrawer { open: true, dismissible: "false", instance: "i", title: rsx! { "Required step" }, "Finish the form." } }
    }
    common::assert_matches_fixture(app, "ty-drawer/not-dismissible.html");
}

#[test]
fn drawer_max_height() {
    fn app() -> Element {
        rsx! { TyDrawer { open: true, max_height: "60dvh", instance: "i", title: rsx! { "Shortcuts" }, "Keys." } }
    }
    common::assert_matches_fixture(app, "ty-drawer/max-height.html");
}

#[test]
fn inline_notice_info() {
    fn app() -> Element {
        rsx! { TyInlineNotice { instance: "i", "Unseal the vault to run workflows that use credentials." } }
    }
    common::assert_matches_fixture(app, "ty-inline-notice/info.html");
}

#[test]
fn inline_notice_danger_title() {
    fn app() -> Element {
        rsx! { TyInlineNotice { tone: InlineNoticeTone::Danger, instance: "i", title: rsx! { "Vault sealed" }, "Unseal it to run workflows that use credentials." } }
    }
    common::assert_matches_fixture(app, "ty-inline-notice/danger-title.html");
}

#[test]
fn inline_notice_warning_heading() {
    fn app() -> Element {
        rsx! { TyInlineNotice { tone: InlineNoticeTone::Warning, title_as: InlineNoticeTitleAs::H3, instance: "i", title: rsx! { "Two sources unavailable" }, "Results may be incomplete." } }
    }
    common::assert_matches_fixture(app, "ty-inline-notice/warning-heading.html");
}

#[test]
fn inline_notice_success_dismissible() {
    fn app() -> Element {
        rsx! { TyInlineNotice { tone: InlineNoticeTone::Success, dismissible: true, instance: "i", "Version 12 is live." } }
    }
    common::assert_matches_fixture(app, "ty-inline-notice/success-dismissible.html");
}

#[test]
fn inline_notice_centred_actions() {
    fn app() -> Element {
        rsx! { TyInlineNotice { align: InlineNoticeAlign::Centre, urgency: InlineNoticeUrgency::None, instance: "i", actions: rsx! { "Help" }, "Nothing to review." } }
    }
    common::assert_matches_fixture(app, "ty-inline-notice/centred-actions.html");
}

#[test]
fn inline_notice_custom_icon() {
    fn app() -> Element {
        rsx! { TyInlineNotice { instance: "i", icon: rsx! { "★" }, "Starred runs appear first." } }
    }
    common::assert_matches_fixture(app, "ty-inline-notice/custom-icon.html");
}

#[test]
fn link_inline() {
    fn app() -> Element {
        rsx! { TyLink { href: "/runs", instance: "i", "Runs" } }
    }
    common::assert_matches_fixture(app, "ty-link/inline.html");
}

#[test]
fn link_subtle_standalone() {
    fn app() -> Element {
        rsx! { TyLink { href: "/runs/01HX", emphasis: LinkEmphasis::Subtle, standalone: true, instance: "i", "Details" } }
    }
    common::assert_matches_fixture(app, "ty-link/subtle-standalone.html");
}

#[test]
fn link_external() {
    fn app() -> Element {
        rsx! { TyLink { href: "https://example.org/report", external: true, instance: "i", "Report" } }
    }
    common::assert_matches_fixture(app, "ty-link/external.html");
}

#[test]
fn link_current() {
    fn app() -> Element {
        rsx! { TyLink { href: "/overview", current: true, instance: "i", "Overview" } }
    }
    common::assert_matches_fixture(app, "ty-link/current.html");
}

#[test]
fn link_translated_hint() {
    fn app() -> Element {
        rsx! { TyLink { href: "https://example.org/relatorio", external: true, new_tab_label: "(abre em nova aba)", described_by: "report-hint", instance: "i", "Relatório" } }
    }
    common::assert_matches_fixture(app, "ty-link/translated-hint.html");
}

#[test]
fn modal_closed() {
    fn app() -> Element {
        rsx! { TyModal { instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-modal/closed.html");
}

#[test]
fn modal_open() {
    fn app() -> Element {
        rsx! { TyModal { is_open: true, instance: "i", title: rsx! { "Delete file?" }, actions: rsx! { "Delete" }, "This cannot be undone." } }
    }
    common::assert_matches_fixture(app, "ty-modal/open.html");
}

#[test]
fn modal_open_description() {
    fn app() -> Element {
        rsx! { TyModal { is_open: true, instance: "i", title: rsx! { "Invite member" }, description: rsx! { "They get an email with a link." }, actions: rsx! { "Invite" }, "Form fields" } }
    }
    common::assert_matches_fixture(app, "ty-modal/open-description.html");
}

#[test]
fn modal_alertdialog() {
    fn app() -> Element {
        rsx! { TyModal { is_open: true, role: ModalRole::Alertdialog, instance: "i", title: rsx! { "Discard changes?" }, actions: rsx! { "Discard" }, "Your edits are not saved." } }
    }
    common::assert_matches_fixture(app, "ty-modal/alertdialog.html");
}

#[test]
fn modal_wide_busy() {
    fn app() -> Element {
        rsx! { TyModal { is_open: true, width: ModalWidth::Wide, busy: true, instance: "i", title: rsx! { "Publishing" }, "Uploading the bundle." } }
    }
    common::assert_matches_fixture(app, "ty-modal/wide-busy.html");
}

#[test]
fn modal_no_close_button() {
    fn app() -> Element {
        rsx! { TyModal { is_open: true, show_close_button: "false", instance: "i", title: rsx! { "Terms of service" }, actions: rsx! { "Accept" }, "Scroll to the end." } }
    }
    common::assert_matches_fixture(app, "ty-modal/no-close-button.html");
}

#[test]
fn native_select_labelled_placeholder() {
    fn app() -> Element {
        rsx! { TyNativeSelect { name: "region", placeholder: "Choose a region…", instance: "i", label: rsx! { "Region" }, "us-east-1" } }
    }
    common::assert_matches_fixture(app, "ty-native-select/labelled-placeholder.html");
}

#[test]
fn native_select_hint_required_value() {
    fn app() -> Element {
        rsx! { TyNativeSelect { name: "region", required: true, value: "us-east-1", instance: "i", label: rsx! { "Region" }, hint: rsx! { "Where the workflow runs" }, "us-east-1" } }
    }
    common::assert_matches_fixture(app, "ty-native-select/hint-required-value.html");
}

#[test]
fn native_select_invalid_error() {
    fn app() -> Element {
        rsx! { TyNativeSelect { name: "region", instance: "i", label: rsx! { "Region" }, error: rsx! { "Pick a region" }, "us-east-1" } }
    }
    common::assert_matches_fixture(app, "ty-native-select/invalid-error.html");
}

#[test]
fn native_select_field_wired() {
    fn app() -> Element {
        rsx! { TyNativeSelect { control_id: "field-3-control", described_by: "field-3-description field-3-error", invalid: true, required: true, name: "region", test_id: "region", accessible_label: "Region", instance: "i", error: rsx! { "Required" }, "us-east-1" } }
    }
    common::assert_matches_fixture(app, "ty-native-select/field-wired.html");
}

#[test]
fn native_select_disabled_unlabelled() {
    fn app() -> Element {
        rsx! { TyNativeSelect { disabled: true, accessible_label: "Region", instance: "i", "us-east-1" } }
    }
    common::assert_matches_fixture(app, "ty-native-select/disabled-unlabelled.html");
}

#[test]
fn popover_closed() {
    fn app() -> Element {
        rsx! { TyPopover { trigger_label: "Details", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-popover/closed.html");
}

#[test]
fn popover_info_open() {
    fn app() -> Element {
        rsx! { TyPopover { open: true, trigger_label: "About this", title: "What this means", instance: "i", "A short explanation." } }
    }
    common::assert_matches_fixture(app, "ty-popover/info-open.html");
}

#[test]
fn popover_own_trigger() {
    fn app() -> Element {
        rsx! { TyPopover { open: true, placement: PopoverPlacement::Top, align: PopoverAlign::Start, instance: "i", trigger: rsx! { "Open" }, "Anchored above, aligned to the start." } }
    }
    common::assert_matches_fixture(app, "ty-popover/own-trigger.html");
}

#[test]
fn popover_no_arrow() {
    fn app() -> Element {
        rsx! { TyPopover { open: true, trigger_label: "Where", title: "Somewhere", show_arrow: "false", instance: "i", "Without a pointer." } }
    }
    common::assert_matches_fixture(app, "ty-popover/no-arrow.html");
}

#[test]
fn popover_offset_4() {
    fn app() -> Element {
        rsx! { TyPopover { open: true, trigger_label: "Gap", title: "Further away", offset: "4", instance: "i", "A wider gap." } }
    }
    common::assert_matches_fixture(app, "ty-popover/offset-4.html");
}

#[test]
fn separator_decorative() {
    fn app() -> Element {
        rsx! { TySeparator { instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-separator/decorative.html");
}

#[test]
fn separator_semantic() {
    fn app() -> Element {
        rsx! { TySeparator { semantic: true, instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-separator/semantic.html");
}

#[test]
fn separator_semantic_vertical() {
    fn app() -> Element {
        rsx! { TySeparator { semantic: true, orientation: SeparatorOrientation::Vertical, instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-separator/semantic-vertical.html");
}

#[test]
fn separator_soft_roomy() {
    fn app() -> Element {
        rsx! { TySeparator { emphasis: SeparatorEmphasis::Soft, spacing: SeparatorSpacing::Roomy, instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-separator/soft-roomy.html");
}

#[test]
fn separator_caption() {
    fn app() -> Element {
        rsx! { TySeparator { instance: "i", caption: rsx! { "or" }, } }
    }
    common::assert_matches_fixture(app, "ty-separator/caption.html");
}

#[test]
fn skeleton_line() {
    fn app() -> Element {
        rsx! { TySkeleton { instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-skeleton/line.html");
}

#[test]
fn skeleton_heading_short() {
    fn app() -> Element {
        rsx! { TySkeleton { shape: SkeletonShape::Heading, width: "short", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-skeleton/heading-short.html");
}

#[test]
fn skeleton_circle() {
    fn app() -> Element {
        rsx! { TySkeleton { shape: SkeletonShape::Circle, instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-skeleton/circle.html");
}

#[test]
fn skeleton_rect_medium() {
    fn app() -> Element {
        rsx! { TySkeleton { shape: SkeletonShape::Rect, width: "medium", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-skeleton/rect-medium.html");
}

#[test]
fn skeleton_announced() {
    fn app() -> Element {
        rsx! { TySkeleton { label: "Loading the catalogue", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-skeleton/announced.html");
}

#[test]
fn spinner_ring() {
    fn app() -> Element {
        rsx! { TySpinner { instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-spinner/ring.html");
}

#[test]
fn spinner_dots_labelled() {
    fn app() -> Element {
        rsx! { TySpinner { shape: SpinnerShape::Dots, label: "Saving", instance: "i", "Saving" } }
    }
    common::assert_matches_fixture(app, "ty-spinner/dots-labelled.html");
}

#[test]
fn spinner_large_accent() {
    fn app() -> Element {
        rsx! { TySpinner { size: SpinnerSize::Large, tone: SpinnerTone::Accent, label: "Indexing", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-spinner/large-accent.html");
}

#[test]
fn spinner_small_on_accent() {
    fn app() -> Element {
        rsx! { TySpinner { size: SpinnerSize::Small, tone: SpinnerTone::OnAccent, label: "Uploading", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-spinner/small-on-accent.html");
}

#[test]
fn spinner_dots_neutral() {
    fn app() -> Element {
        rsx! { TySpinner { shape: SpinnerShape::Dots, tone: SpinnerTone::Neutral, instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-spinner/dots-neutral.html");
}

#[test]
fn status_pill_success() {
    fn app() -> Element {
        rsx! { TyStatusPill { status: "active", tone: StatusPillTone::Success, instance: "i", icon: rsx! { "✓" }, "Active" } }
    }
    common::assert_matches_fixture(app, "ty-status-pill/success.html");
}

#[test]
fn status_pill_busy_info() {
    fn app() -> Element {
        rsx! { TyStatusPill { status: "processing", tone: StatusPillTone::Info, busy: true, instance: "i", icon: rsx! { "↻" }, "Processing" } }
    }
    common::assert_matches_fixture(app, "ty-status-pill/busy-info.html");
}

#[test]
fn status_pill_small_warning() {
    fn app() -> Element {
        rsx! { TyStatusPill { status: "pending", tone: StatusPillTone::Warning, size: StatusPillSize::Small, instance: "i", "Pending" } }
    }
    common::assert_matches_fixture(app, "ty-status-pill/small-warning.html");
}

#[test]
fn status_pill_announced_danger() {
    fn app() -> Element {
        rsx! { TyStatusPill { status: "error", tone: StatusPillTone::Danger, announce: true, accessible_label: "Status: Error", test_id: "status-badge-error", instance: "i", "Error" } }
    }
    common::assert_matches_fixture(app, "ty-status-pill/announced-danger.html");
}

#[test]
fn status_pill_unknown_neutral() {
    fn app() -> Element {
        rsx! { TyStatusPill { status: "archived", instance: "i", "archived" } }
    }
    common::assert_matches_fixture(app, "ty-status-pill/unknown-neutral.html");
}

#[test]
fn surface_sheet() {
    fn app() -> Element {
        rsx! { TySurface { instance: "i", title: rsx! { "Runs" }, description: rsx! { "Last 24 hours" }, "Body" } }
    }
    common::assert_matches_fixture(app, "ty-surface/sheet.html");
}

#[test]
fn surface_raised_roomy() {
    fn app() -> Element {
        rsx! { TySurface { elevation: SurfaceElevation::Raised, padding: SurfacePadding::Roomy, instance: "i", "Body" } }
    }
    common::assert_matches_fixture(app, "ty-surface/raised-roomy.html");
}

#[test]
fn surface_flat_none_footer() {
    fn app() -> Element {
        rsx! { TySurface { elevation: SurfaceElevation::Flat, padding: SurfacePadding::None, instance: "i", footer: rsx! { "Actions" }, "Body" } }
    }
    common::assert_matches_fixture(app, "ty-surface/flat-none-footer.html");
}

#[test]
fn surface_pressable() {
    fn app() -> Element {
        rsx! { TySurface { pressable: true, instance: "i", title: rsx! { "Open workflow" }, "Body" } }
    }
    common::assert_matches_fixture(app, "ty-surface/pressable.html");
}

#[test]
fn surface_link_selected() {
    fn app() -> Element {
        rsx! { TySurface { href: "/runs/1", selected: true, instance: "i", title: rsx! { "Nightly sync" }, "Body" } }
    }
    common::assert_matches_fixture(app, "ty-surface/link-selected.html");
}

#[test]
fn surface_pressable_disabled() {
    fn app() -> Element {
        rsx! { TySurface { pressable: true, disabled: true, instance: "i", title: rsx! { "Archived" }, "Body" } }
    }
    common::assert_matches_fixture(app, "ty-surface/pressable-disabled.html");
}

#[test]
fn surface_title_level() {
    fn app() -> Element {
        rsx! { TySurface { title_level: SurfaceTitleLevel::H2, instance: "i", title: rsx! { "Settings" }, } }
    }
    common::assert_matches_fixture(app, "ty-surface/title-level.html");
}

#[test]
fn switch_off() {
    fn app() -> Element {
        rsx! { TySwitch { instance: "i", "Autosave" } }
    }
    common::assert_matches_fixture(app, "ty-switch/off.html");
}

#[test]
fn switch_on_with_description() {
    fn app() -> Element {
        rsx! { TySwitch { checked: true, name: "autosave", instance: "i", description: rsx! { "Save every change" }, "Autosave" } }
    }
    common::assert_matches_fixture(app, "ty-switch/on-with-description.html");
}

#[test]
fn switch_tile_large() {
    fn app() -> Element {
        rsx! { TySwitch { layout: SwitchLayout::Tile, size: SwitchSize::Large, value: "yes", test_id: "notifications", instance: "i", "Notifications" } }
    }
    common::assert_matches_fixture(app, "ty-switch/tile-large.html");
}

#[test]
fn switch_read_only() {
    fn app() -> Element {
        rsx! { TySwitch { checked: true, read_only: true, instance: "i", "Managed by your organization" } }
    }
    common::assert_matches_fixture(app, "ty-switch/read-only.html");
}

#[test]
fn switch_disabled_unlabelled() {
    fn app() -> Element {
        rsx! { TySwitch { disabled: true, accessible_label: "Dark mode", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-switch/disabled-unlabelled.html");
}

#[test]
fn tag_neutral() {
    fn app() -> Element {
        rsx! { TyTag { instance: "i", "postgres" } }
    }
    common::assert_matches_fixture(app, "ty-tag/neutral.html");
}

#[test]
fn tag_accent_small_icon() {
    fn app() -> Element {
        rsx! { TyTag { tone: TagTone::Accent, size: TagSize::Small, test_id: "env", instance: "i", icon: rsx! { "◆" }, "production" } }
    }
    common::assert_matches_fixture(app, "ty-tag/accent-small-icon.html");
}

#[test]
fn tag_category() {
    fn app() -> Element {
        rsx! { TyTag { category_index: 3.0f64, instance: "i", "Stage 3" } }
    }
    common::assert_matches_fixture(app, "ty-tag/category.html");
}

#[test]
fn tag_removable() {
    fn app() -> Element {
        rsx! { TyTag { removable: true, remove_label: "Remove São Paulo", instance: "i", "São Paulo" } }
    }
    common::assert_matches_fixture(app, "ty-tag/removable.html");
}

#[test]
fn tag_live_large() {
    fn app() -> Element {
        rsx! { TyTag { live: true, size: TagSize::Large, instance: "i", "Running" } }
    }
    common::assert_matches_fixture(app, "ty-tag/live-large.html");
}

#[test]
fn text_area_labelled() {
    fn app() -> Element {
        rsx! { TyTextArea { instance: "i", label: rsx! { "Notes" }, } }
    }
    common::assert_matches_fixture(app, "ty-text-area/labelled.html");
}

#[test]
fn text_area_hint_and_placeholder() {
    fn app() -> Element {
        rsx! { TyTextArea { name: "notes", placeholder: "Write a summary", instance: "i", label: rsx! { "Notes" }, hint: rsx! { "Shown on the canvas" }, } }
    }
    common::assert_matches_fixture(app, "ty-text-area/hint-and-placeholder.html");
}

#[test]
fn text_area_error() {
    fn app() -> Element {
        rsx! { TyTextArea { value: "Draft", instance: "i", label: rsx! { "Abstract" }, error: rsx! { "Required" }, } }
    }
    common::assert_matches_fixture(app, "ty-text-area/error.html");
}

#[test]
fn text_area_counter() {
    fn app() -> Element {
        rsx! { TyTextArea { value: "Hello", max_length: 500.0f64, show_counter: true, instance: "i", label: rsx! { "Bio" }, } }
    }
    common::assert_matches_fixture(app, "ty-text-area/counter.html");
}

#[test]
fn text_area_monospace_read_only() {
    fn app() -> Element {
        rsx! { TyTextArea { monospace: true, resize: TextAreaResize::None, read_only: true, value: "{{ \"a\": 1 }}", instance: "i", label: rsx! { "JSON" }, } }
    }
    common::assert_matches_fixture(app, "ty-text-area/monospace-read-only.html");
}

#[test]
fn text_area_auto_grow() {
    fn app() -> Element {
        rsx! { TyTextArea { auto_grow: true, max_rows: 6.0f64, rows: 2.0f64, instance: "i", label: rsx! { "Log" }, } }
    }
    common::assert_matches_fixture(app, "ty-text-area/auto-grow.html");
}

#[test]
fn text_area_disabled_unlabelled() {
    fn app() -> Element {
        rsx! { TyTextArea { disabled: true, accessible_label: "Notes", described_by: "external-hint", test_id: "notes", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-text-area/disabled-unlabelled.html");
}

#[test]
fn text_field_labelled() {
    fn app() -> Element {
        rsx! { TyTextField { instance: "i", label: rsx! { "Name" }, } }
    }
    common::assert_matches_fixture(app, "ty-text-field/labelled.html");
}

#[test]
fn text_field_hint_and_placeholder() {
    fn app() -> Element {
        rsx! { TyTextField { name: "name", placeholder: "Ada Lovelace", auto_complete: "name", instance: "i", label: rsx! { "Name" }, hint: rsx! { "As on your badge" }, } }
    }
    common::assert_matches_fixture(app, "ty-text-field/hint-and-placeholder.html");
}

#[test]
fn text_field_email_filled_leading() {
    fn app() -> Element {
        rsx! { TyTextField { input_type: TextFieldInputType::Email, appearance: TextFieldAppearance::Filled, name: "email", auto_complete: "email", instance: "i", label: rsx! { "Email" }, leading: rsx! { "✉" }, } }
    }
    common::assert_matches_fixture(app, "ty-text-field/email-filled-leading.html");
}

#[test]
fn text_field_search() {
    fn app() -> Element {
        rsx! { TyTextField { mode: TextFieldMode::Search, name: "q", value: "brazil", placeholder: "Search states", instance: "i", label: rsx! { "Search" }, } }
    }
    common::assert_matches_fixture(app, "ty-text-field/search.html");
}

#[test]
fn text_field_password() {
    fn app() -> Element {
        rsx! { TyTextField { mode: TextFieldMode::Password, name: "password", auto_complete: "current-password", required: true, instance: "i", label: rsx! { "Password" }, hint: rsx! { "At least 12 characters" }, } }
    }
    common::assert_matches_fixture(app, "ty-text-field/password.html");
}

#[test]
fn text_field_error() {
    fn app() -> Element {
        rsx! { TyTextField { value: "ab", required: true, instance: "i", label: rsx! { "Code" }, error: rsx! { "Too short" }, } }
    }
    common::assert_matches_fixture(app, "ty-text-field/error.html");
}

#[test]
fn text_field_counter() {
    fn app() -> Element {
        rsx! { TyTextField { value: "Hello", max_length: 20.0f64, show_counter: true, instance: "i", label: rsx! { "Title" }, } }
    }
    common::assert_matches_fixture(app, "ty-text-field/counter.html");
}

#[test]
fn text_field_success() {
    fn app() -> Element {
        rsx! { TyTextField { input_type: TextFieldInputType::Email, value: "ada@example.org", instance: "i", label: rsx! { "Email" }, success: rsx! { "Looks right" }, } }
    }
    common::assert_matches_fixture(app, "ty-text-field/success.html");
}

#[test]
fn text_field_disabled_unlabelled() {
    fn app() -> Element {
        rsx! { TyTextField { disabled: true, accessible_label: "Name", described_by: "external-hint", test_id: "name", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-text-field/disabled-unlabelled.html");
}
