// Generated by tools/elements/generate.mjs from packages/ui/src/elements/*/definition.ts. Do not edit.
//
// Every example of every enhancing element, rendered by the generated
// Dioxus binding (SSR), must match the reference HTML the definition
// renders (tests/fixtures), which the React wrapper and the element
// itself are tested against on the TypeScript side.

use dioxus::prelude::*;
use tympan_dioxus::*;

use super::common;

#[test]
fn button_secondary() {
    fn app() -> Element {
        rsx! { TyButton { instance: "i", "Cancel" } }
    }
    common::assert_matches_fixture(app, "ty-button/secondary.html");
}

#[test]
fn button_primary_large() {
    fn app() -> Element {
        rsx! { TyButton { variant: ButtonVariant::Primary, size: ButtonSize::Large, instance: "i", "Save" } }
    }
    common::assert_matches_fixture(app, "ty-button/primary-large.html");
}

#[test]
fn button_submit() {
    fn app() -> Element {
        rsx! { TyButton { variant: ButtonVariant::Primary, r#type: ButtonType::Submit, name: "intent", value: "publish", instance: "i", "Publish" } }
    }
    common::assert_matches_fixture(app, "ty-button/submit.html");
}

#[test]
fn button_busy() {
    fn app() -> Element {
        rsx! { TyButton { variant: ButtonVariant::Primary, busy: true, instance: "i", "Saving" } }
    }
    common::assert_matches_fixture(app, "ty-button/busy.html");
}

#[test]
fn button_danger_disabled() {
    fn app() -> Element {
        rsx! { TyButton { variant: ButtonVariant::Danger, disabled: true, instance: "i", "Delete" } }
    }
    common::assert_matches_fixture(app, "ty-button/danger-disabled.html");
}

#[test]
fn button_icon_only() {
    fn app() -> Element {
        rsx! { TyButton { variant: ButtonVariant::Quiet, icon_only: true, shape: ButtonShape::Circle, accessible_label: "Close", instance: "i", icon: rsx! { "×" }, } }
    }
    common::assert_matches_fixture(app, "ty-button/icon-only.html");
}

#[test]
fn button_full_width_pill() {
    fn app() -> Element {
        rsx! { TyButton { full_width: true, shape: ButtonShape::Pill, instance: "i", trailing_icon: rsx! { "→" }, "Continue" } }
    }
    common::assert_matches_fixture(app, "ty-button/full-width-pill.html");
}

#[test]
fn button_toggle() {
    fn app() -> Element {
        rsx! { TyButton { variant: ButtonVariant::Quiet, pressed: "false", expanded: "false", controls: "panel", haspopup: "dialog", test_id: "toggle", instance: "i", "Filters" } }
    }
    common::assert_matches_fixture(app, "ty-button/toggle.html");
}

#[test]
fn switch_off() {
    fn app() -> Element {
        rsx! { TySwitch { instance: "i", "Autosave" } }
    }
    common::assert_matches_fixture(app, "ty-switch/off.html");
}

#[test]
fn switch_on_with_description() {
    fn app() -> Element {
        rsx! { TySwitch { checked: true, name: "autosave", instance: "i", description: rsx! { "Save every change" }, "Autosave" } }
    }
    common::assert_matches_fixture(app, "ty-switch/on-with-description.html");
}

#[test]
fn switch_tile_large() {
    fn app() -> Element {
        rsx! { TySwitch { layout: SwitchLayout::Tile, size: SwitchSize::Large, value: "yes", test_id: "notifications", instance: "i", "Notifications" } }
    }
    common::assert_matches_fixture(app, "ty-switch/tile-large.html");
}

#[test]
fn switch_read_only() {
    fn app() -> Element {
        rsx! { TySwitch { checked: true, read_only: true, instance: "i", "Managed by your organization" } }
    }
    common::assert_matches_fixture(app, "ty-switch/read-only.html");
}

#[test]
fn switch_disabled_unlabelled() {
    fn app() -> Element {
        rsx! { TySwitch { disabled: true, accessible_label: "Dark mode", instance: "i", } }
    }
    common::assert_matches_fixture(app, "ty-switch/disabled-unlabelled.html");
}
