// @fakhir/ui (FSL-1.1-ALv2). Import the stylesheet once: import '@fakhir/ui/styles.css'

// Foundations
export { FakhirProvider, useMessages, type FakhirProviderProps, type RouterNavigateOptions } from './internal/provider'
export { catalogueForLocale, defaultMessages, messagesEs, messagesPtBR, mergeMessages, shippedCatalogues, type Messages, type MessageOverrides, type ProofStateKey } from './internal/messages'
export { compileIcuMessages, pseudoLocalize, pseudoString, type IcuCatalogue } from './internal/icuCatalogue'
export { ThemeProvider, useTheme, themeInitScript, type ThemeProviderProps, type ThemeState, type ThemeMode, type ThemeDensity } from './internal/theme'
export { ThemeScope, type ThemeScopeProps } from './internal/ThemeScope'
export { VisuallyHidden } from './internal/VisuallyHidden'
export { variants, type VariantConfig } from './internal/variants'
export { breakpoints, useMediaQuery, useReducedMotion } from './internal/media'
export { requestHaptic, type HapticStrength } from './internal/haptics'
export type { IconComponent } from './internal/types'

// Components (wave 1 + design direction §2.11)
export * from './components/action-menu/ActionMenu'
export * from './components/actor-chip/ActorChip'
export * from './components/app-frame/AppFrame'
export * from './components/avatar/Avatar'
export * from './components/breadcrumbs/Breadcrumbs'
export * from './components/button/Button'
export * from './components/checkbox/Checkbox'
export * from './components/data-table/DataTable'
export * from './components/drawer/Drawer'
export * from './components/empty-state/EmptyState'
export * from './components/error-state/ErrorState'
export * from './components/field/Field'
export * from './components/heading/Heading'
export * from './components/inline-notice/InlineNotice'
export * from './components/link/Link'
export * from './components/listbox-select/ListboxSelect'
export * from './components/modal-dialog/ModalDialog'
export * from './components/native-select/NativeSelect'
export * from './components/page-header/PageHeader'
export * from './components/pagination/Pagination'
export * from './components/popover/Popover'
export * from './components/progress-bar/ProgressBar'
export * from './components/proof-badge/ProofBadge'
export * from './components/section-heading/SectionHeading'
export * from './components/segmented-control/SegmentedControl'
export * from './components/separator/Separator'
export * from './components/skeleton/Skeleton'
export * from './components/skip-link/SkipLink'
export * from './components/spinner/Spinner'
export * from './components/status-pill/StatusPill'
export * from './components/surface/Surface'
export * from './components/switch/Switch'
export * from './components/tabs/Tabs'
export * from './components/tag/Tag'
export * from './components/text-area/TextArea'
export * from './components/text-field/TextField'
export * from './components/text/Text'
export * from './components/toast/Toast'

// Wave 2 and wave 4 (one barrel per group)
export * from './groups/forms-a'
export * from './groups/forms-b'
export * from './groups/overlays-nav'
export * from './groups/data-a'
export * from './groups/data-b'
export * from './groups/charts-geo'
export * from './groups/auth-brand'
export * from './groups/platform'
export * from './groups/showcase'
export * from './groups/shell'
