// Generated by tools/elements/generate.mjs from packages/ui/src/elements/action-menu/definition.ts. Do not edit.
import { createElement, forwardRef, useEffect, useId, useImperativeHandle, useRef, type ReactNode } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)
const filled = (v: ReactNode) => v !== undefined && v !== null && v !== false && v !== ''

/** A list of commands opened from a trigger button (mode `trigger`, the APG Menu Button pattern) or at a pointer position over a target (mode `context`: secondary click, Shift+F10, the ContextMenu key, or a long press on touch). Opening moves focus to the first enabled item (ArrowUp from the trigger: the last); ArrowDown/ArrowUp move with wrapping, Home/End jump, typing a character moves to the next enabled item starting with it, Enter/Space activate, Escape closes and returns focus to the origin, Tab and an outside press close. Disabled items are skipped and announced as disabled. In context mode the surface is clamped so it never overflows the viewport. Visibility is controlled: the element asks with `ty-open-change`, the host flips `open`. */
export interface TyActionMenuProps {
  /** Shown (controlled). The anatomy stays mounted but `hidden` while closed, so nothing reaches the accessibility tree. */
  open?: boolean
  /** `trigger`: opens from the trigger button; `context`: opens at a viewport point over the trigger slot's target. Default: `trigger`. */
  mode?: "trigger" | "context"
  /** Accessible name of the menu (required by the spec). */
  label?: string
  /** Accessible name of the built-in icon-only trigger (the React messages.moreActions default), used in trigger mode when the trigger slot is empty. Default: `More actions`. */
  triggerLabel?: string
  /** JSON array of entries in order: an item `{ id, label, icon?, tone?, disabled?, shortcut? }` (`icon` a decorative text glyph, `tone` "danger" marks a destructive command, `shortcut` a displayed hint only), `{ "type": "separator" }`, or `{ "type": "section", "id", "title", "items": [...] }`. The element composes the rows on upgrade. */
  items?: string
  /** Context mode: the viewport point the menu opens at, "x,y" in CSS pixels (controlled); the last context-request point when unset. Clamped so the menu stays inside the viewport. */
  position?: string
  /** Trigger mode: the host's own toggle — any single focusable element, wired with aria-haspopup="menu" and aria-expanded. Context mode: the target that receives the context request (secondary click, Shift+F10, long press). Empty in trigger mode: the built-in ellipsis button named by `triggerLabel`. */
  trigger?: ReactNode
  /** An item was activated (pointer, Enter or Space); the element then asks to close. A disabled item never fires. */
  onAction?: (detail: { id: string }) => void
  /** The element asks the host to change visibility — `open: true` on a trigger activation or a context request (secondary click, Shift+F10, the ContextMenu key, a long press), `open: false` on Escape, Tab, an outside press or after an action. Controlled: the element does not toggle itself; the host flips `open`. */
  onOpenChange?: (detail: { open: boolean }) => void
  id?: string
  className?: string
}

const DEFAULTS = { mode: "trigger", triggerLabel: "More actions" } as const

export const TyActionMenu = forwardRef<HTMLElement, TyActionMenuProps>(function TyActionMenu(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  useEffect(() => {
    const element = host.current
    if (!element) return
    const listeners: Array<[string, EventListener]> = [
      ["ty-action", (event) => handlers.current.onAction?.((event as CustomEvent).detail)],
      ["ty-open-change", (event) => handlers.current.onOpenChange?.((event as CustomEvent).detail)],
    ]
    for (const [type, listener] of listeners) element.addEventListener(type, listener)
    return () => { for (const [type, listener] of listeners) element.removeEventListener(type, listener) }
  }, [])
  const p = {
    open: props.open,
    mode: props.mode ?? DEFAULTS.mode,
    label: props.label,
    triggerLabel: props.triggerLabel ?? DEFAULTS.triggerLabel,
    items: props.items,
    position: props.position,
  }
  const slots: Record<string, boolean> = { "trigger": filled(props.trigger) }
  return createElement("ty-action-menu", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "open": truthy(p.open) ? true : undefined, "mode": text(p.mode), "label": text(p.label), "trigger-label": text(p.triggerLabel), "items": text(p.items), "position": text(p.position) },
    createElement("span", { className: "ty-action-menu__target", "data-mode": p.mode },
      (!(slots["trigger"])) && (p.mode === "trigger") ? createElement("button", { className: "ty-button ty-action-menu__trigger", type: "button", "aria-label": p.triggerLabel, "aria-haspopup": "menu", "data-variant": "quiet", "data-icon-only": "" },
        createElement("span", { className: "ty-button__icon", "aria-hidden": "true" },
          createElement("svg", { className: "ty-icon", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": "true", focusable: "false" },
            createElement("circle", { className: "ty-action-menu__glyph", cx: "12", cy: "12", r: "1" }),
            createElement("circle", { className: "ty-action-menu__glyph", cx: "19", cy: "12", r: "1" }),
            createElement("circle", { className: "ty-action-menu__glyph", cx: "5", cy: "12", r: "1" }),
          ),
        ),
      ) : null,
      ((slots["trigger"])) ? props.trigger : null,
      createElement("div", { className: "ty-action-menu", hidden: (!(truthy(p.open))) ? (true) : undefined, "data-mode": p.mode },
        createElement("div", { className: "ty-action-menu__menu", id: `${instance}-menu`, role: "menu", "aria-label": p.label, "aria-orientation": "vertical", tabIndex: "-1" }),
      ),
    ))
})
