// Generated by tools/elements/generate.mjs from packages/ui/src/elements/avatar/definition.ts. Do not edit.
import { createElement, forwardRef, useId, useImperativeHandle, useRef, type ChangeEvent, type SyntheticEvent } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)

/** Represents a person or an agent with a picture or fallback initials, optionally as a pressable control. Static, the frame is an image role named by `name` (hidden when `decorative`); pressable, it is a link (`href`) or a button (`pressable`) named by `actionLabel`, with a 44 px hit area at every size. The fallback (initials for a person, a bot mark for an agent, a user mark otherwise) shows while there is no picture and when the picture fails to load. */
export interface TyAvatarProps {
  /** Image URL; on load error the fallback shows. */
  src?: string
  /** One or two characters shown when there is no image (derived by the host from a name); the element keeps the first two grapheme clusters. */
  fallbackText?: string
  /** Accessible name; required unless `decorative`. Initials are never read as letters while it is set. */
  name?: string
  /** Hides the avatar from assistive tech when the name is already shown next to it. */
  decorative?: boolean
  /** `person`: circle with initials. `agent`: rounded square with a bot icon and a dashed border, never initials (§2.11). Default: `person`. */
  actorKind?: "person" | "agent"
  /** Size step. Default: `regular`. */
  size?: "xsmall" | "small" | "regular" | "large"
  /** Fallback background: accent-soft or neutral (§2.3). Default: `accent`. */
  tint?: "accent" | "neutral"
  /** The avatar is one press target (a button); set it when `onPress` is wired. Implied by `href`. */
  pressable?: boolean
  /** Makes the avatar a link to this destination (wins over `pressable`). */
  href?: string
  /** Accessible name of a pressable avatar; `{name}` is filled in. Translate through this attribute. Default: `Open profile of {name}`. */
  actionLabel?: string
  /** The native click of the pressable avatar (its link or button). */
  onPress?: (event: SyntheticEvent) => void
  id?: string
  className?: string
}

const DEFAULTS = { actorKind: "person", size: "regular", tint: "accent", actionLabel: "Open profile of {name}" } as const

export const TyAvatar = forwardRef<HTMLElement, TyAvatarProps>(function TyAvatar(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  const p = {
    src: props.src,
    fallbackText: props.fallbackText,
    name: props.name,
    decorative: props.decorative,
    actorKind: props.actorKind ?? DEFAULTS.actorKind,
    size: props.size ?? DEFAULTS.size,
    tint: props.tint ?? DEFAULTS.tint,
    pressable: props.pressable,
    href: props.href,
    actionLabel: props.actionLabel ?? DEFAULTS.actionLabel,
  }
  return createElement("ty-avatar", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "src": text(p.src), "fallback-text": text(p.fallbackText), "name": text(p.name), "decorative": truthy(p.decorative) ? true : undefined, "actor-kind": text(p.actorKind), "size": text(p.size), "tint": text(p.tint), "pressable": truthy(p.pressable) ? true : undefined, "href": text(p.href), "action-label": text(p.actionLabel) },
    createElement("span", { className: "ty-avatar-root" },
      (!(truthy(p.pressable))) && (!(truthy(p.href))) ? createElement("span", { className: "ty-avatar", "data-kind": p.actorKind, "data-size": p.size, "data-tint": p.tint, "data-image": (truthy(p.src)) ? ("") : undefined, "aria-hidden": (truthy(p.decorative)) ? ("true") : undefined, role: (!(truthy(p.decorative))) && (!(truthy(p.src))) ? ("img") : undefined, "aria-label": (!(truthy(p.decorative))) && (!(truthy(p.src))) ? (p.name) : undefined },
        (truthy(p.src)) && (truthy(p.decorative) || truthy(p.pressable) || truthy(p.href)) ? createElement("img", { className: "ty-avatar__image", src: p.src, alt: "" }) : null,
        (truthy(p.src)) && (!(truthy(p.decorative))) && (!(truthy(p.pressable))) && (!(truthy(p.href))) ? createElement("img", { className: "ty-avatar__image", src: p.src, alt: p.name }) : null,
        createElement("span", { className: "ty-avatar__fallback", hidden: (truthy(p.src)) ? (true) : undefined },
          (p.actorKind === "agent") ? createElement("svg", { className: "ty-avatar__icon", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": "true", focusable: "false" },
            createElement("path", { className: "ty-avatar__glyph", d: "M12 8V4H8" }),
            createElement("rect", { className: "ty-avatar__glyph", width: "16", height: "12", x: "4", y: "8", rx: "2" }),
            createElement("path", { className: "ty-avatar__glyph", d: "M2 14h2" }),
            createElement("path", { className: "ty-avatar__glyph", d: "M20 14h2" }),
            createElement("path", { className: "ty-avatar__glyph", d: "M15 13v2" }),
            createElement("path", { className: "ty-avatar__glyph", d: "M9 13v2" }),
          ) : null,
          (p.actorKind === "person") && (truthy(p.fallbackText)) ? createElement("span", { className: "ty-avatar__initials", "aria-hidden": "true" },
            text(p.fallbackText),
          ) : null,
          (p.actorKind === "person") && (!(truthy(p.fallbackText))) ? createElement("svg", { className: "ty-avatar__icon", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": "true", focusable: "false" },
            createElement("path", { className: "ty-avatar__glyph", d: "M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" }),
            createElement("circle", { className: "ty-avatar__glyph", cx: "12", cy: "7", r: "4" }),
          ) : null,
        ),
      ) : null,
      (truthy(p.href)) ? createElement("a", { className: "ty-avatar-control", href: p.href, "data-size": p.size, onPress: (event: ChangeEvent<HTMLAnchorElement>) => handlers.current.onPress?.(event) },
        createElement("span", { className: "ty-avatar", "data-kind": p.actorKind, "data-size": p.size, "data-tint": p.tint, "data-image": (truthy(p.src)) ? ("") : undefined, "aria-hidden": "true" },
          (truthy(p.src)) && (truthy(p.decorative) || truthy(p.pressable) || truthy(p.href)) ? createElement("img", { className: "ty-avatar__image", src: p.src, alt: "" }) : null,
          (truthy(p.src)) && (!(truthy(p.decorative))) && (!(truthy(p.pressable))) && (!(truthy(p.href))) ? createElement("img", { className: "ty-avatar__image", src: p.src, alt: p.name }) : null,
          createElement("span", { className: "ty-avatar__fallback", hidden: (truthy(p.src)) ? (true) : undefined },
            (p.actorKind === "agent") ? createElement("svg", { className: "ty-avatar__icon", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": "true", focusable: "false" },
              createElement("path", { className: "ty-avatar__glyph", d: "M12 8V4H8" }),
              createElement("rect", { className: "ty-avatar__glyph", width: "16", height: "12", x: "4", y: "8", rx: "2" }),
              createElement("path", { className: "ty-avatar__glyph", d: "M2 14h2" }),
              createElement("path", { className: "ty-avatar__glyph", d: "M20 14h2" }),
              createElement("path", { className: "ty-avatar__glyph", d: "M15 13v2" }),
              createElement("path", { className: "ty-avatar__glyph", d: "M9 13v2" }),
            ) : null,
            (p.actorKind === "person") && (truthy(p.fallbackText)) ? createElement("span", { className: "ty-avatar__initials", "aria-hidden": "true" },
              text(p.fallbackText),
            ) : null,
            (p.actorKind === "person") && (!(truthy(p.fallbackText))) ? createElement("svg", { className: "ty-avatar__icon", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": "true", focusable: "false" },
              createElement("path", { className: "ty-avatar__glyph", d: "M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" }),
              createElement("circle", { className: "ty-avatar__glyph", cx: "12", cy: "7", r: "4" }),
            ) : null,
          ),
        ),
      ) : null,
      (!(truthy(p.href))) && (truthy(p.pressable)) ? createElement("button", { className: "ty-avatar-control", type: "button", "data-size": p.size, onPress: (event: ChangeEvent<HTMLButtonElement>) => handlers.current.onPress?.(event) },
        createElement("span", { className: "ty-avatar", "data-kind": p.actorKind, "data-size": p.size, "data-tint": p.tint, "data-image": (truthy(p.src)) ? ("") : undefined, "aria-hidden": "true" },
          (truthy(p.src)) && (truthy(p.decorative) || truthy(p.pressable) || truthy(p.href)) ? createElement("img", { className: "ty-avatar__image", src: p.src, alt: "" }) : null,
          (truthy(p.src)) && (!(truthy(p.decorative))) && (!(truthy(p.pressable))) && (!(truthy(p.href))) ? createElement("img", { className: "ty-avatar__image", src: p.src, alt: p.name }) : null,
          createElement("span", { className: "ty-avatar__fallback", hidden: (truthy(p.src)) ? (true) : undefined },
            (p.actorKind === "agent") ? createElement("svg", { className: "ty-avatar__icon", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": "true", focusable: "false" },
              createElement("path", { className: "ty-avatar__glyph", d: "M12 8V4H8" }),
              createElement("rect", { className: "ty-avatar__glyph", width: "16", height: "12", x: "4", y: "8", rx: "2" }),
              createElement("path", { className: "ty-avatar__glyph", d: "M2 14h2" }),
              createElement("path", { className: "ty-avatar__glyph", d: "M20 14h2" }),
              createElement("path", { className: "ty-avatar__glyph", d: "M15 13v2" }),
              createElement("path", { className: "ty-avatar__glyph", d: "M9 13v2" }),
            ) : null,
            (p.actorKind === "person") && (truthy(p.fallbackText)) ? createElement("span", { className: "ty-avatar__initials", "aria-hidden": "true" },
              text(p.fallbackText),
            ) : null,
            (p.actorKind === "person") && (!(truthy(p.fallbackText))) ? createElement("svg", { className: "ty-avatar__icon", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": "true", focusable: "false" },
              createElement("path", { className: "ty-avatar__glyph", d: "M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" }),
              createElement("circle", { className: "ty-avatar__glyph", cx: "12", cy: "7", r: "4" }),
            ) : null,
          ),
        ),
      ) : null,
    ))
})
