// Generated by tools/elements/generate.mjs from packages/ui/src/elements/brand-wordmark/definition.ts. Do not edit.
import { createElement, forwardRef, useId, useImperativeHandle, useRef } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)

/** Two-tone product wordmark: the plain part (`text`) in ink and the accent part (`accent`) in the brand gradient (`background-clip: text`). Plain text for assistive tech as-is; `label` turns it into an img role with that name (a logo lockup). */
export interface TyBrandWordmarkProps {
  /** The plain part of the wordmark, in ink. */
  text?: string
  /** The accent part of the wordmark, in the brand gradient; rendered right after `text`. */
  accent?: string
  /** Type step of the wordmark. Default: `medium`. */
  size?: "small" | "medium" | "large"
  /** Accessible name as an img role (a logo lockup); left out, the wordmark is plain text read as-is. */
  label?: string
  /** Test hook on the wordmark (`data-testid`). */
  testId?: string
  id?: string
  className?: string
}

const DEFAULTS = { size: "medium" } as const

export const TyBrandWordmark = forwardRef<HTMLElement, TyBrandWordmarkProps>(function TyBrandWordmark(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  const p = {
    text: props.text,
    accent: props.accent,
    size: props.size ?? DEFAULTS.size,
    label: props.label,
    testId: props.testId,
  }
  return createElement("ty-brand-wordmark", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "text": text(p.text), "accent": text(p.accent), "size": text(p.size), "label": text(p.label), "test-id": text(p.testId) },
    createElement("span", { className: "ty-brand-wordmark", role: (truthy(p.label)) ? ("img") : undefined, "aria-label": p.label, "data-size": p.size, "data-testid": p.testId },
      (truthy(p.text)) ? createElement("span", { className: "ty-brand-wordmark__text" },
        text(p.text),
      ) : null,
      (truthy(p.accent)) ? createElement("span", { className: "ty-brand-wordmark__accent" },
        text(p.accent),
      ) : null,
    ))
})
