// Generated by tools/elements/generate.mjs from packages/ui/src/elements/breadcrumbs/definition.ts. Do not edit.
import { createElement, forwardRef, useEffect, useId, useImperativeHandle, useRef, type ReactNode } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)
const filled = (v: ReactNode) => v !== undefined && v !== null && v !== false && v !== ''

/** Shows where the current page sits in the hierarchy and goes up one or more levels. A trail at 640 px and above, a compact back link (with optional centred title and trailing actions) below. The last item is the current page — static text marked `aria-current="page"`, never a link; separators are decorative. Long labels truncate with an ellipsis, the full label kept in `title` and as the accessible name. Activating a link emits a cancelable `ty-navigate`: a host with a client-side router prevents the default and navigates through its adapter. */
export interface TyBreadcrumbsProps {
  /** JSON array of `{ "label": string, "href": string }`, ancestors first and the current page last. Composed by the element on upgrade (the theme palette's `theme-labels` precedent). */
  items?: string
  /** Accessible name of the navigation landmark (the I18n adapter's default); translate through this attribute. Default: `Breadcrumb`. */
  label?: string
  /** `auto` shows the trail at 640 px and above, the compact bar below; the element resolves it live. Default: `auto`. */
  mode?: "trail" | "compact" | "auto"
  /** Parent href of the compact back link when there is only one item. */
  rootHref?: string
  /** Parent label of the compact back link when there is only one item (with `rootHref`). */
  rootLabel?: string
  /** Collapses middle items into an overflow menu when the trail exceeds this many entries (the first and the last `maxVisible - 1` stay visible). */
  maxVisible?: number
  /** Accessible-name template of the compact back link; `{parent}` is filled with the parent's label. Default: `Back to {parent}`. */
  backLabel?: string
  /** Accessible name of the overflow menu's toggle; translate through this attribute. Default: `Show hidden levels`. */
  overflowLabel?: string
  /** Replaces the centred title of the compact bar (the current page's label when empty). */
  center?: ReactNode
  /** Trailing actions of the compact bar (narrow screens use it as a top bar). */
  actions?: ReactNode
  /** A trail, overflow or back link was activated; `href` is its destination. Cancelable: a host with a client-side router calls `preventDefault()` and navigates through its adapter; uncanceled, the native anchor navigates. */
  onNavigate?: (detail: { href: string }) => void
  id?: string
  className?: string
}

const DEFAULTS = { label: "Breadcrumb", mode: "auto", backLabel: "Back to {parent}", overflowLabel: "Show hidden levels" } as const

export const TyBreadcrumbs = forwardRef<HTMLElement, TyBreadcrumbsProps>(function TyBreadcrumbs(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  useEffect(() => {
    const element = host.current
    if (!element) return
    const listeners: Array<[string, EventListener]> = [
      ["ty-navigate", (event) => handlers.current.onNavigate?.((event as CustomEvent).detail)],
    ]
    for (const [type, listener] of listeners) element.addEventListener(type, listener)
    return () => { for (const [type, listener] of listeners) element.removeEventListener(type, listener) }
  }, [])
  const p = {
    items: props.items,
    label: props.label ?? DEFAULTS.label,
    mode: props.mode ?? DEFAULTS.mode,
    rootHref: props.rootHref,
    rootLabel: props.rootLabel,
    maxVisible: props.maxVisible,
    backLabel: props.backLabel ?? DEFAULTS.backLabel,
    overflowLabel: props.overflowLabel ?? DEFAULTS.overflowLabel,
  }
  const slots: Record<string, boolean> = { "center": filled(props.center), "actions": filled(props.actions) }
  return createElement("ty-breadcrumbs", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "items": text(p.items), "label": text(p.label), "mode": text(p.mode), "root-href": text(p.rootHref), "root-label": text(p.rootLabel), "max-visible": text(p.maxVisible), "back-label": text(p.backLabel), "overflow-label": text(p.overflowLabel) },
    createElement("nav", { className: "ty-breadcrumbs", "aria-label": p.label, "data-mode": p.mode },
      (!(p.mode === "compact")) ? createElement("ol", { className: "ty-breadcrumbs__list" }) : null,
      (p.mode === "compact" || p.mode === "auto") ? createElement("div", { className: "ty-breadcrumbs__bar" },
        createElement("div", { className: "ty-breadcrumbs__back" }),
        (slots["center"] || slots["actions"]) ? createElement("div", { className: "ty-breadcrumbs__center" },
          ((slots["center"])) ? props.center : null,
          (!(slots["center"])) ? createElement("span", { className: "ty-breadcrumbs__title", "aria-current": "page" }) : null,
        ) : null,
        (slots["actions"]) ? createElement("div", { className: "ty-breadcrumbs__actions" },
          props.actions,
        ) : null,
      ) : null,
    ))
})
