// Generated by tools/elements/generate.mjs from packages/ui/src/elements/button/definition.ts. Do not edit.
import { createElement, forwardRef, useId, useImperativeHandle, useRef, type ReactNode, type SyntheticEvent } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)
const filled = (v: ReactNode) => v !== undefined && v !== null && v !== false && v !== ''

/** Triggers one action. A native <button> inside, so focus, keyboard activation and form submission are the platform's. */
export interface TyButtonProps {
  /** Visual weight; at most one primary per view. Default: `secondary`. */
  variant?: "primary" | "secondary" | "quiet" | "danger"
  /** Height step. Default: `regular`. */
  size?: "compact" | "regular" | "large"
  /** `circle` only for icon-only buttons. Default: `rounded`. */
  shape?: "rounded" | "pill" | "circle"
  /** Hides the label; `accessibleLabel` is then required. */
  iconOnly?: boolean
  /** Stretches to the container width. */
  fullWidth?: boolean
  /** Shows the busy indicator and blocks presses (`aria-busy`, `aria-disabled`). */
  busy?: boolean
  /** Native disabled. */
  disabled?: boolean
  /** Native button type; `submit` submits the enclosing form. Default: `button`. */
  type?: "button" | "submit" | "reset"
  /** Form field name sent with a submit. */
  name?: string
  /** Form field value sent with a submit. */
  value?: string
  /** Accessible name when there is no visible label; also the tooltip of an icon-only button. */
  accessibleLabel?: string
  /** A toggle button's state, `true` or `false` (`aria-pressed`); left out for an ordinary button. */
  pressed?: string
  /** `true` or `false` while the button shows or hides a popup or region (`aria-expanded`). */
  expanded?: string
  /** Id of the element the button controls (`aria-controls`). */
  controls?: string
  /** The kind of popup the button opens (`aria-haspopup`: `menu`, `dialog`, `listbox`, …). */
  haspopup?: string
  /** Test hook on the native button (`data-testid`). */
  testId?: string
  /** The label. */
  children?: ReactNode
  /** A leading icon (decorative). */
  icon?: ReactNode
  /** A trailing icon (decorative). */
  trailingIcon?: ReactNode
  /** The native click (not fired while busy or disabled). */
  onClick?: (event: SyntheticEvent) => void
  id?: string
  className?: string
}

const DEFAULTS = { variant: "secondary", size: "regular", shape: "rounded", type: "button" } as const

export const TyButton = forwardRef<HTMLElement, TyButtonProps>(function TyButton(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  const p: Record<string, unknown> = { ...DEFAULTS }
  for (const [key, value] of Object.entries(props)) if (value !== undefined) p[key] = value
  const slots: Record<string, boolean> = { "default": filled(props.children), "icon": filled(props.icon), "trailing-icon": filled(props.trailingIcon) }
  return createElement("ty-button", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "variant": text(p.variant), "size": text(p.size), "shape": text(p.shape), "icon-only": truthy(p.iconOnly) ? true : undefined, "full-width": truthy(p.fullWidth) ? true : undefined, "busy": truthy(p.busy) ? true : undefined, "disabled": truthy(p.disabled) ? true : undefined, "type": text(p.type), "name": text(p.name), "value": text(p.value), "accessible-label": text(p.accessibleLabel), "pressed": text(p.pressed), "expanded": text(p.expanded), "controls": text(p.controls), "haspopup": text(p.haspopup), "test-id": text(p.testId) },
    createElement("button", { className: "ty-button", type: text(p.type), name: text(p.name), value: text(p.value), disabled: truthy(p.disabled) || undefined, "aria-busy": truthy(p.busy) ? 'true' : undefined, "aria-disabled": truthy(p.busy) ? 'true' : undefined, "aria-label": text(p.accessibleLabel), "aria-pressed": text(p.pressed), "aria-expanded": text(p.expanded), "aria-controls": text(p.controls), "aria-haspopup": text(p.haspopup), "data-testid": text(p.testId), title: (truthy(p.iconOnly)) ? (text(p.accessibleLabel)) : undefined, "data-variant": text(p.variant), "data-size": text(p.size), "data-shape": text(p.shape), "data-icon-only": truthy(p.iconOnly) ? '' : undefined, "data-full-width": truthy(p.fullWidth) ? '' : undefined, "data-busy": truthy(p.busy) ? '' : undefined, onClick: (event) => handlers.current.onClick?.(event) },
      (truthy(p.busy)) ? createElement("span", { className: "ty-button__busy", "aria-hidden": "true" }) : null,
      (!truthy(p.busy)) && (slots["icon"]) ? createElement("span", { className: "ty-button__icon", "aria-hidden": "true" },
        props.icon,
      ) : null,
      (!truthy(p.iconOnly)) ? createElement("span", { className: "ty-button__label" },
        props.children,
      ) : null,
      (!truthy(p.iconOnly)) && (slots["trailing-icon"]) ? createElement("span", { className: "ty-button__icon", "aria-hidden": "true" },
        props.trailingIcon,
      ) : null,
    ))
})
