// Generated by tools/elements/generate.mjs from packages/ui/src/elements/checkbox/definition.ts. Do not edit.
import { createElement, forwardRef, useId, useImperativeHandle, useRef, type ReactNode, type ChangeEvent, type SyntheticEvent } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)
const filled = (v: ReactNode) => v !== undefined && v !== null && v !== false && v !== ''

/** A labelled choice that submits with its form. A native checkbox inside a <label> row, so labelling, keyboard (Space) and form participation are the platform's. The indicator holds both marks; CSS shows the check while the input is :checked, the minus while it is :indeterminate, so every renderer (and the page before upgrade) shows the right state. */
export interface TyCheckboxProps {
  /** On. */
  checked?: boolean
  /** Mixed state for "select all" rows (the input's `indeterminate` property); cleared by the next toggle. */
  indeterminate?: boolean
  /** Native disabled. */
  disabled?: boolean
  /** Native required; the form will not submit while off. */
  required?: boolean
  /** Form field name; the value is sent while on. */
  name?: string
  /** Form value sent while on (the browser sends "on" without one). */
  value?: string
  /** `tile` draws a surface around the row; `bare` is indicator plus text. Default: `tile`. */
  appearance?: "tile" | "bare"
  /** Accessible name when there is no visible label. */
  accessibleLabel?: string
  /** Test hook on the native checkbox (`data-testid`). */
  testId?: string
  /** The visible label. */
  children?: ReactNode
  /** A secondary line, announced as the description. */
  description?: ReactNode
  /** The error message; marks the checkbox invalid (`aria-invalid`, `aria-errormessage`). */
  error?: ReactNode
  /** The native change of the checkbox; `checked` is the new state. */
  onChange?: (detail: { checked: boolean }, event: SyntheticEvent) => void
  id?: string
  className?: string
}

const DEFAULTS = { appearance: "tile" } as const

export const TyCheckbox = forwardRef<HTMLElement, TyCheckboxProps>(function TyCheckbox(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  const p = {
    checked: props.checked,
    indeterminate: props.indeterminate,
    disabled: props.disabled,
    required: props.required,
    name: props.name,
    value: props.value,
    appearance: props.appearance ?? DEFAULTS.appearance,
    accessibleLabel: props.accessibleLabel,
    testId: props.testId,
  }
  const slots: Record<string, boolean> = { "default": filled(props.children), "description": filled(props.description), "error": filled(props.error) }
  return createElement("ty-checkbox", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "checked": truthy(p.checked) ? true : undefined, "indeterminate": truthy(p.indeterminate) ? true : undefined, "disabled": truthy(p.disabled) ? true : undefined, "required": truthy(p.required) ? true : undefined, "name": text(p.name), "value": text(p.value), "appearance": text(p.appearance), "accessible-label": text(p.accessibleLabel), "test-id": text(p.testId) },
    createElement("div", { className: "ty-checkbox", "data-appearance": p.appearance },
      createElement("label", { className: "ty-checkbox__row", "data-selected": truthy(p.checked) ? '' : undefined, "data-indeterminate": truthy(p.indeterminate) ? '' : undefined, "data-disabled": truthy(p.disabled) ? '' : undefined },
        createElement("input", { className: "ty-visually-hidden", type: "checkbox", name: p.name, value: p.value, checked: Boolean(p.checked), disabled: truthy(p.disabled) || undefined, required: truthy(p.required) || undefined, "aria-label": (!(slots["default"])) ? (p.accessibleLabel) : undefined, "aria-labelledby": (slots["default"]) ? (`${instance}-label`) : undefined, "aria-describedby": (slots["description"]) ? (`${instance}-description`) : undefined, "aria-invalid": (slots["error"]) ? ("true") : undefined, "aria-errormessage": (slots["error"]) ? (`${instance}-error`) : undefined, "data-testid": p.testId, onChange: (event: ChangeEvent<HTMLInputElement>) => handlers.current.onChange?.({ checked: event.currentTarget.checked }, event) }),
        createElement("span", { className: "ty-checkbox__indicator", "aria-hidden": "true" },
          createElement("svg", { className: "ty-icon", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": "true", focusable: "false" },
            createElement("path", { className: "ty-checkbox__check", d: "M20 6 9 17l-5-5" }),
            createElement("path", { className: "ty-checkbox__minus", d: "M5 12h14" }),
          ),
        ),
        (slots["default"] || slots["description"]) ? createElement("span", { className: "ty-checkbox__text" },
          (slots["default"]) ? createElement("span", { className: "ty-checkbox__label", id: `${instance}-label` },
            props.children,
          ) : null,
          (slots["description"]) ? createElement("span", { className: "ty-checkbox__description", id: `${instance}-description` },
            props.description,
          ) : null,
        ) : null,
      ),
      (slots["error"]) ? createElement("p", { className: "ty-checkbox__error", id: `${instance}-error`, "aria-live": "polite" },
        createElement("svg", { className: "ty-icon", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": "true", focusable: "false" },
          createElement("path", { className: "ty-checkbox__error-glyph", d: "M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20ZM12 8v4M12 16h.01" }),
        ),
        createElement("span", { className: "ty-checkbox__error-text" },
          props.error,
        ),
      ) : null,
    ))
})
