// Generated by tools/elements/generate.mjs from packages/ui/src/elements/command-palette/definition.ts. Do not edit.
import { createElement, forwardRef, useEffect, useId, useImperativeHandle, useRef } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)

/** Global search-and-commands dialog in the top layer: a combobox field over grouped, fuzzy-matched results with scopes, per-item actions, fallback actions and recents. The query, the highlight and the actions sub-list reset on each open. */
export interface TyCommandPaletteProps {
  /** Shown (a modal dialog in the top layer). The element closes itself after a choice or the stepped-back Escape — removing the attribute and asking the host with `ty-close` — so a controlled host follows the attribute. */
  open?: boolean
  /** JSON array of groups: `{ id, heading, scopeId?, items: [{ id, label, description?, icon?, keywords?, hint?, shortcut?, scopeId?, actions?: [{ id, label, icon?, shortcut? }] }] }`. `keywords` are matched but not shown; `icon` is a text glyph. Unparseable or missing: no groups. */
  groups?: string
  /** JSON array of scopes: `[{ id, label, icon? }]`; empty means no scoping (no scope column, no scope keys). */
  scopes?: string
  /** The active scope id; unset: everything. The element reflects user changes back to this attribute and reports them with `ty-scope-change`. */
  activeScope?: string
  /** Shows skeleton rows and announces the loading label instead of results. */
  loading?: boolean
  /** JSON array of actions offered when the query matches nothing: `[{ id, label, icon?, shortcut? }]`; `{query}` in a label is replaced by the query. */
  fallbackActions?: string
  /** Browser-storage key of the recent store; enables it. Records the chosen item id with a count and a time, tolerant of storage being unavailable. */
  recentKey?: string
  /** Recents shown when the query is empty, most chosen first (ties: most recent). Default: `5`. */
  recentVisible?: number
  /** Most recent ids the store keeps. Default: `12`. */
  recentKeep?: number
  /** Accessible name of the dialog and the field. Default: `Search and commands`. */
  label?: string
  /** Field placeholder. Default: `Search or type a command`. */
  placeholder?: string
  /** Shown on an empty query with nothing to list. Default: `Type to search records, sources and screens.`. */
  emptyLabel?: string
  /** Shown and announced when the query matches nothing; {query} is replaced. Default: `Nothing matches “{query}”.`. */
  noResultsLabel?: string
  /** Announced in the status region while `loading`. Default: `Loading results`. */
  loadingLabel?: string
  /** Accessible name of the scope chip; {scope} is replaced by the scope label. Default: `Remove scope {scope}`. */
  removeScopeLabel?: string
  /** Heading of the actions sub-list; {label} is replaced by the item label. Default: `Actions for {label}`. */
  actionsForLabel?: string
  /** Heading of the recent group. Default: `Recent`. */
  recentLabel?: string
  /** Announced result count; {count} is replaced. Default: `{count} results`. */
  resultsLabel?: string
  /** Accessible name of the scope column. Default: `Scopes`. */
  scopesLabel?: string
  /** Heading of the fallback group. Default: `Other actions`. */
  fallbackLabel?: string
  /** Footer hint beside ↑↓. Default: `move`. */
  hintNavigate?: string
  /** Footer hint beside ↵. Default: `open`. */
  hintSelect?: string
  /** Footer hint beside →. Default: `actions`. */
  hintActions?: string
  /** Footer hint beside ←. Default: `back`. */
  hintBack?: string
  /** Footer hint beside esc. Default: `close`. */
  hintClose?: string
  /** A row was chosen: an item (`kind: "item"`, `id` the item id), a secondary action (`kind: "action"`, `id` the action id, `itemId` its item) or a fallback action (`kind: "fallback"`). `itemId` is empty except for actions. The palette then closes itself and asks the host with `ty-close`. */
  onSelect?: (detail: { id: string; kind: string; itemId: string }) => void
  /** The active scope changed (a scope button, the chip, Tab or Backspace); `scope` is the scope id, empty when cleared. The element reflects it to the `active-scope` attribute. */
  onScopeChange?: (detail: { scope: string }) => void
  /** The palette asks to close (the stepped-back Escape reaching the top level, a press outside, or after a choice). The element closes itself too. */
  onClose?: () => void
  id?: string
  className?: string
}

const DEFAULTS = { recentVisible: 5, recentKeep: 12, label: "Search and commands", placeholder: "Search or type a command", emptyLabel: "Type to search records, sources and screens.", noResultsLabel: "Nothing matches “{query}”.", loadingLabel: "Loading results", removeScopeLabel: "Remove scope {scope}", actionsForLabel: "Actions for {label}", recentLabel: "Recent", resultsLabel: "{count} results", scopesLabel: "Scopes", fallbackLabel: "Other actions", hintNavigate: "move", hintSelect: "open", hintActions: "actions", hintBack: "back", hintClose: "close" } as const

export const TyCommandPalette = forwardRef<HTMLElement, TyCommandPaletteProps>(function TyCommandPalette(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  useEffect(() => {
    const element = host.current
    if (!element) return
    const listeners: Array<[string, EventListener]> = [
      ["ty-select", (event) => handlers.current.onSelect?.((event as CustomEvent).detail)],
      ["ty-scope-change", (event) => handlers.current.onScopeChange?.((event as CustomEvent).detail)],
      ["ty-close", () => handlers.current.onClose?.()],
    ]
    for (const [type, listener] of listeners) element.addEventListener(type, listener)
    return () => { for (const [type, listener] of listeners) element.removeEventListener(type, listener) }
  }, [])
  const p = {
    open: props.open,
    groups: props.groups,
    scopes: props.scopes,
    activeScope: props.activeScope,
    loading: props.loading,
    fallbackActions: props.fallbackActions,
    recentKey: props.recentKey,
    recentVisible: props.recentVisible ?? DEFAULTS.recentVisible,
    recentKeep: props.recentKeep ?? DEFAULTS.recentKeep,
    label: props.label ?? DEFAULTS.label,
    placeholder: props.placeholder ?? DEFAULTS.placeholder,
    emptyLabel: props.emptyLabel ?? DEFAULTS.emptyLabel,
    noResultsLabel: props.noResultsLabel ?? DEFAULTS.noResultsLabel,
    loadingLabel: props.loadingLabel ?? DEFAULTS.loadingLabel,
    removeScopeLabel: props.removeScopeLabel ?? DEFAULTS.removeScopeLabel,
    actionsForLabel: props.actionsForLabel ?? DEFAULTS.actionsForLabel,
    recentLabel: props.recentLabel ?? DEFAULTS.recentLabel,
    resultsLabel: props.resultsLabel ?? DEFAULTS.resultsLabel,
    scopesLabel: props.scopesLabel ?? DEFAULTS.scopesLabel,
    fallbackLabel: props.fallbackLabel ?? DEFAULTS.fallbackLabel,
    hintNavigate: props.hintNavigate ?? DEFAULTS.hintNavigate,
    hintSelect: props.hintSelect ?? DEFAULTS.hintSelect,
    hintActions: props.hintActions ?? DEFAULTS.hintActions,
    hintBack: props.hintBack ?? DEFAULTS.hintBack,
    hintClose: props.hintClose ?? DEFAULTS.hintClose,
  }
  return createElement("ty-command-palette", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "open": truthy(p.open) ? true : undefined, "groups": text(p.groups), "scopes": text(p.scopes), "active-scope": text(p.activeScope), "loading": truthy(p.loading) ? true : undefined, "fallback-actions": text(p.fallbackActions), "recent-key": text(p.recentKey), "recent-visible": text(p.recentVisible), "recent-keep": text(p.recentKeep), "label": text(p.label), "placeholder": text(p.placeholder), "empty-label": text(p.emptyLabel), "no-results-label": text(p.noResultsLabel), "loading-label": text(p.loadingLabel), "remove-scope-label": text(p.removeScopeLabel), "actions-for-label": text(p.actionsForLabel), "recent-label": text(p.recentLabel), "results-label": text(p.resultsLabel), "scopes-label": text(p.scopesLabel), "fallback-label": text(p.fallbackLabel), "hint-navigate": text(p.hintNavigate), "hint-select": text(p.hintSelect), "hint-actions": text(p.hintActions), "hint-back": text(p.hintBack), "hint-close": text(p.hintClose) })
})
