// Generated by tools/elements/generate.mjs from packages/ui/src/elements/currency-field/definition.ts. Do not edit.
import { createElement, forwardRef, useEffect, useId, useImperativeHandle, useRef, type ReactNode } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)
const filled = (v: ReactNode) => v !== undefined && v !== null && v !== false && v !== ''

/** Money or count entry with live grouping in the locale's separators; reports a plain canonical number (digits, an optional dot and decimals, never grouped). A native <input> inside, so typing, keyboard, autofill and form participation are the platform's; the element regroups the display on every edit, keeps the caret after the same digit, shows the currency symbol and names the currency to assistive technology. */
export interface TyCurrencyFieldProps {
  /** Canonical value: digits with an optional dot and decimals, never grouped ("1500000.5"); "" when empty. The element mirrors it into the control as grouped display text (while the user types, the live value is the control's own). */
  value?: string
  /** Initial canonical value of an uncontrolled field, applied once on connect; a form reset returns to it. */
  defaultValue?: string
  /** ISO 4217 code ("BRL"); the symbol is shown (visual only) and the currency name is announced as part of the description. Omit for plain counts. */
  currency?: string
  /** Maximum fraction digits; 0 means integers only (the decimal separator is ignored and the mobile keyboard is numeric). Default: `2`. */
  decimals?: number
  /** Locale that decides the group and decimal separators ("pt-BR"); the document language, then the browser locale, when unset. Changing it changes only the display, never the canonical value. */
  locale?: string
  /** Type scale step; `display` uses the KPI numeral style. Default: `medium`. */
  size?: "small" | "medium" | "large" | "display"
  /** Template of the visually hidden currency note; `{currency}` is filled with the locale's currency name ("Currency: Brazilian real"). Default: `Currency: {currency}`. */
  currencyLabel?: string
  /** Native required. */
  required?: boolean
  /** Native disabled. */
  disabled?: boolean
  /** Shown but not changeable. */
  readOnly?: boolean
  /** Painted and announced as invalid without an error message (a surrounding field marks it). */
  invalid?: boolean
  /** Form field name. */
  name?: string
  /** Native placeholder. */
  placeholder?: string
  /** Accessible name when there is no visible label. */
  accessibleLabel?: string
  /** `aria-labelledby` from a surrounding field (used when there is no visible label and no `accessibleLabel`). */
  labelledBy?: string
  /** `aria-describedby` from a surrounding field, joined before the field's own parts. */
  describedBy?: string
  /** Explicit id of the control (a surrounding field's control id); `<instance>-input` otherwise. */
  controlId?: string
  /** Test hook on the root (`data-testid`). */
  testId?: string
  /** The visible label, targeting the input. */
  label?: ReactNode
  /** Help text above the group, announced as the description. */
  hint?: ReactNode
  /** The error message; marks the field invalid and is announced. */
  error?: ReactNode
  /** After every edit; `value` is the canonical number (digits, an optional dot and decimals, never grouped; "" when empty). The display text is never reported. */
  onValueChange?: (detail: { value: string }) => void
  id?: string
  className?: string
}

const DEFAULTS = { decimals: 2, size: "medium", currencyLabel: "Currency: {currency}" } as const

export const TyCurrencyField = forwardRef<HTMLElement, TyCurrencyFieldProps>(function TyCurrencyField(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  useEffect(() => {
    const element = host.current
    if (!element) return
    const listeners: Array<[string, EventListener]> = [
      ["ty-value-change", (event) => handlers.current.onValueChange?.((event as CustomEvent).detail)],
    ]
    for (const [type, listener] of listeners) element.addEventListener(type, listener)
    return () => { for (const [type, listener] of listeners) element.removeEventListener(type, listener) }
  }, [])
  const p = {
    value: props.value,
    defaultValue: props.defaultValue,
    currency: props.currency,
    decimals: props.decimals ?? DEFAULTS.decimals,
    locale: props.locale,
    size: props.size ?? DEFAULTS.size,
    currencyLabel: props.currencyLabel ?? DEFAULTS.currencyLabel,
    required: props.required,
    disabled: props.disabled,
    readOnly: props.readOnly,
    invalid: props.invalid,
    name: props.name,
    placeholder: props.placeholder,
    accessibleLabel: props.accessibleLabel,
    labelledBy: props.labelledBy,
    describedBy: props.describedBy,
    controlId: props.controlId,
    testId: props.testId,
  }
  const slots: Record<string, boolean> = { "label": filled(props.label), "hint": filled(props.hint), "error": filled(props.error) }
  return createElement("ty-currency-field", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "value": text(p.value), "default-value": text(p.defaultValue), "currency": text(p.currency), "decimals": text(p.decimals), "locale": text(p.locale), "size": text(p.size), "currency-label": text(p.currencyLabel), "required": truthy(p.required) ? true : undefined, "disabled": truthy(p.disabled) ? true : undefined, "read-only": truthy(p.readOnly) ? true : undefined, "invalid": truthy(p.invalid) ? true : undefined, "name": text(p.name), "placeholder": text(p.placeholder), "accessible-label": text(p.accessibleLabel), "labelled-by": text(p.labelledBy), "described-by": text(p.describedBy), "control-id": text(p.controlId), "test-id": text(p.testId) },
    createElement("div", { className: "ty-currency-field", "data-size": p.size, "data-invalid": (truthy(p.invalid) || slots["error"]) ? ("") : undefined, "data-readonly": truthy(p.readOnly) ? '' : undefined, "data-disabled": truthy(p.disabled) ? '' : undefined, "data-testid": p.testId },
      createElement("div", { className: "ty-currency-field__field" },
        (slots["label"]) ? createElement("label", { className: "ty-fb-line", "data-line": "label", htmlFor: (text(p.controlId) ?? `${instance}-input`) },
          props.label,
        ) : null,
        (slots["hint"]) ? createElement("p", { className: "ty-fb-line", "data-line": "hint", id: `${instance}-hint` },
          props.hint,
        ) : null,
        createElement("div", { className: "ty-currency-field__box" },
          (truthy(p.currency)) ? createElement("span", { className: "ty-currency-field__symbol", "aria-hidden": "true" }) : null,
          createElement("input", { className: "ty-currency-field__input", id: (text(p.controlId) ?? `${instance}-input`), type: "text", name: p.name, placeholder: p.placeholder, autoComplete: "off", disabled: truthy(p.disabled) || undefined, readOnly: truthy(p.readOnly) || undefined, required: truthy(p.required) || undefined, "aria-label": (!(slots["label"])) ? (p.accessibleLabel) : undefined, "aria-labelledby": (!(slots["label"])) && (!(truthy(p.accessibleLabel))) ? (p.labelledBy) : undefined, "aria-describedby": [text(p.describedBy) ?? '', (((slots["hint"])) ? `${instance}-hint` : ''), (((truthy(p.currency))) ? `${instance}-currency` : ''), (((slots["error"])) ? `${instance}-error` : '')].filter(Boolean).join(' ') || undefined, "aria-invalid": (truthy(p.invalid) || slots["error"]) ? ("true") : undefined }),
        ),
        (truthy(p.currency)) ? createElement("span", { className: "ty-visually-hidden ty-currency-field__currency", id: `${instance}-currency` }) : null,
        (slots["error"]) ? createElement("p", { className: "ty-fb-line", "data-line": "error", id: `${instance}-error` },
          createElement("svg", { className: "ty-icon", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": "true", focusable: "false" },
            createElement("circle", { className: "ty-currency-field__glyph", cx: "12", cy: "12", r: "10" }),
            createElement("line", { className: "ty-currency-field__glyph", x1: "12", y1: "8", x2: "12", y2: "12" }),
            createElement("line", { className: "ty-currency-field__glyph", x1: "12", y1: "16", x2: "12.01", y2: "16" }),
          ),
          createElement("span", { className: "ty-currency-field__error-text" },
            props.error,
          ),
        ) : null,
      ),
    ))
})
