// Generated by tools/elements/generate.mjs from packages/ui/src/elements/data-table/definition.ts. Do not edit.
import { createElement, forwardRef, useEffect, useId, useImperativeHandle, useRef } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)

/** Records as rows and attributes as columns, with sorting, optional row selection, row navigation, loading and empty states, in three densities. Data arrives as JSON attributes; sort, selection and row activation are controlled: the element emits `ty-sort-change`, `ty-selection-change` and `ty-row-action`, and the host writes the new `sort-column`/`sort-direction`/`selected-keys` back. */
export interface TyDataTableProps {
  /** Accessible name of the table (required); visually hidden unless `captionVisible`. */
  caption?: string
  /** Show the caption above the table; it always names the table. */
  captionVisible?: boolean
  /** JSON array of column definitions: { id, header, sortable?, align?: "start"|"end", numeric? }. `numeric` implies end alignment and tabular figures. */
  columns?: string
  /** JSON array of rows: { id, cells: { "<columnId>": "<text>" }, href?, label? }. `href` makes the whole row the target (one link per row in the tab order); `label` names the row link. */
  rows?: string
  /** Row height and cell padding: comfortable 52 px, standard 44 px, compact 36 px. Default: `standard`. */
  density?: "comfortable" | "standard" | "compact"
  /** The currently sorted column id (controlled). */
  sortColumn?: string
  /** Direction of `sortColumn` (controlled); unset: no sort. */
  sortDirection?: "ascending" | "descending"
  /** `multiple` adds a checkbox column and a select-all header checkbox. Default: `none`. */
  selectionMode?: "none" | "multiple"
  /** JSON array of the selected row ids (controlled). */
  selectedKeys?: string
  /** Show skeleton rows instead of data; the table is `aria-busy` and a polite status announces `loadingLabel`. */
  loading?: boolean
  /** Number of skeleton rows while loading. Default: `10`. */
  loadingRowCount?: number
  /** Polite status announced while loading. Default: `Loading the list`. */
  loadingLabel?: string
  /** Title of the built-in empty state, shown in a single cell spanning all columns when not loading and rows are empty. Default: `No rows to show`. */
  emptyLabel?: string
  /** Optional description under the empty title. */
  emptyDescription?: string
  /** Accessible name of the header checkbox. Default: `Select all rows`. */
  selectAllLabel?: string
  /** Accessible name template of a row checkbox; `{label}` is the row label. Default: `Select {label}`. */
  selectRowLabel?: string
  /** Rows are activatable: Enter or a press on a row without `href` emits `ty-row-action` (the presence of the spec's `onRowAction`). */
  actionable?: boolean
  /** `true` or `false`; unset: the first column stays visible while scrolling horizontally. */
  stickyFirstColumn?: string
  /** Vertical dividers between columns. */
  showColumnLines?: boolean
  /** Maximum height of the scroll container, enabling the sticky header. */
  maxBlockSize?: string
  /** A sortable header cycled (none → ascending → descending → none). `direction` is `ascending`, `descending` or null when the sort cleared (the attribute reads an empty string for the cleared state). Controlled: the host writes `sort-column`/`sort-direction`. */
  onSortChange?: (detail: { column: string; direction: string }) => void
  /** The selection changed (a row checkbox, the select-all header checkbox, or Space on a focused row); `keys` is a JSON array of the selected row ids. Controlled: the host writes `selected-keys`. */
  onSelectionChange?: (detail: { keys: string }) => void
  /** A row without `href` was activated (Enter or a press). */
  onRowAction?: (detail: { id: string }) => void
  id?: string
  className?: string
}

const DEFAULTS = { density: "standard", selectionMode: "none", loadingRowCount: 10, loadingLabel: "Loading the list", emptyLabel: "No rows to show", selectAllLabel: "Select all rows", selectRowLabel: "Select {label}" } as const

export const TyDataTable = forwardRef<HTMLElement, TyDataTableProps>(function TyDataTable(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  useEffect(() => {
    const element = host.current
    if (!element) return
    const listeners: Array<[string, EventListener]> = [
      ["ty-sort-change", (event) => handlers.current.onSortChange?.((event as CustomEvent).detail)],
      ["ty-selection-change", (event) => handlers.current.onSelectionChange?.((event as CustomEvent).detail)],
      ["ty-row-action", (event) => handlers.current.onRowAction?.((event as CustomEvent).detail)],
    ]
    for (const [type, listener] of listeners) element.addEventListener(type, listener)
    return () => { for (const [type, listener] of listeners) element.removeEventListener(type, listener) }
  }, [])
  const p = {
    caption: props.caption,
    captionVisible: props.captionVisible,
    columns: props.columns,
    rows: props.rows,
    density: props.density ?? DEFAULTS.density,
    sortColumn: props.sortColumn,
    sortDirection: props.sortDirection,
    selectionMode: props.selectionMode ?? DEFAULTS.selectionMode,
    selectedKeys: props.selectedKeys,
    loading: props.loading,
    loadingRowCount: props.loadingRowCount ?? DEFAULTS.loadingRowCount,
    loadingLabel: props.loadingLabel ?? DEFAULTS.loadingLabel,
    emptyLabel: props.emptyLabel ?? DEFAULTS.emptyLabel,
    emptyDescription: props.emptyDescription,
    selectAllLabel: props.selectAllLabel ?? DEFAULTS.selectAllLabel,
    selectRowLabel: props.selectRowLabel ?? DEFAULTS.selectRowLabel,
    actionable: props.actionable,
    stickyFirstColumn: props.stickyFirstColumn,
    showColumnLines: props.showColumnLines,
    maxBlockSize: props.maxBlockSize,
  }
  return createElement("ty-data-table", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "caption": text(p.caption), "caption-visible": truthy(p.captionVisible) ? true : undefined, "columns": text(p.columns), "rows": text(p.rows), "density": text(p.density), "sort-column": text(p.sortColumn), "sort-direction": text(p.sortDirection), "selection-mode": text(p.selectionMode), "selected-keys": text(p.selectedKeys), "loading": truthy(p.loading) ? true : undefined, "loading-row-count": text(p.loadingRowCount), "loading-label": text(p.loadingLabel), "empty-label": text(p.emptyLabel), "empty-description": text(p.emptyDescription), "select-all-label": text(p.selectAllLabel), "select-row-label": text(p.selectRowLabel), "actionable": truthy(p.actionable) ? true : undefined, "sticky-first-column": text(p.stickyFirstColumn), "show-column-lines": truthy(p.showColumnLines) ? true : undefined, "max-block-size": text(p.maxBlockSize) })
})
