// Generated by tools/elements/generate.mjs from packages/ui/src/elements/drawer/definition.ts. Do not edit.
import { createElement, forwardRef, useEffect, useId, useImperativeHandle, useRef, type ReactNode } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)
const filled = (v: ReactNode) => v !== undefined && v !== null && v !== false && v !== ''

/** Modal panel sliding in from an edge of the viewport for a secondary task: a backdrop, a panel anchored to the bottom (sheet) or end (side panel) edge, a header with the title and an always-present close button, an optional grab handle, a scrolling body and a bottom safe-area inset. Controlled through `open`; the element asks to close with `ty-open-change` (Escape, close button, an allowed backdrop press, a drag past the threshold) and the host flips `open`. Focus moves into the panel on open, is trapped while open, and returns to the invoking element on close; the page behind is inert and does not scroll. */
export interface TyDrawerProps {
  /** Shown (controlled). The anatomy stays mounted but `hidden` while closed, so nothing reaches the accessibility tree. */
  open?: boolean
  /** The edge the panel attaches to; `end` follows the reading direction. Default: `bottom`. */
  placement?: "bottom" | "end"
  /** Maximum width step of an end-placed panel. Default: `medium`. */
  width?: "medium" | "large" | "wide"
  /** Maximum height of a bottom-placed panel (a CSS length, e.g. `85dvh`); applied to the panel on upgrade. */
  maxHeight?: string
  /** `true` or `false`; unset: the grab handle shows on bottom placement. */
  showHandle?: string
  /** `true` or `false`; unset (or `true`): a backdrop press and a drag past the threshold dismiss. Escape and the close button always work. */
  dismissible?: string
  /** Accessible name of the close button. Default: `Close`. */
  closeLabel?: string
  /** Accessible name of the dialog when the title slot is empty. */
  accessibleLabel?: string
  /** Test hook on the panel (`data-testid`). */
  panelTestId?: string
  /** Test hook on the backdrop (`data-testid`). */
  backdropTestId?: string
  /** The visible heading; also the accessible name (`accessibleLabel` when empty). */
  title?: ReactNode
  /** The body; scrolls when long. */
  children?: ReactNode
  /** The element asks the host to change visibility — `open: false` on Escape, the close button, an allowed backdrop press or a drag past the threshold. Controlled: the element does not close itself; the host flips `open`. */
  onOpenChange?: (detail: { open: boolean }) => void
  id?: string
  className?: string
}

const DEFAULTS = { placement: "bottom", width: "medium", closeLabel: "Close" } as const

export const TyDrawer = forwardRef<HTMLElement, TyDrawerProps>(function TyDrawer(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  useEffect(() => {
    const element = host.current
    if (!element) return
    const listeners: Array<[string, EventListener]> = [
      ["ty-open-change", (event) => handlers.current.onOpenChange?.((event as CustomEvent).detail)],
    ]
    for (const [type, listener] of listeners) element.addEventListener(type, listener)
    return () => { for (const [type, listener] of listeners) element.removeEventListener(type, listener) }
  }, [])
  const p = {
    open: props.open,
    placement: props.placement ?? DEFAULTS.placement,
    width: props.width ?? DEFAULTS.width,
    maxHeight: props.maxHeight,
    showHandle: props.showHandle,
    dismissible: props.dismissible,
    closeLabel: props.closeLabel ?? DEFAULTS.closeLabel,
    accessibleLabel: props.accessibleLabel,
    panelTestId: props.panelTestId,
    backdropTestId: props.backdropTestId,
  }
  const slots: Record<string, boolean> = { "title": filled(props.title), "default": filled(props.children) }
  return createElement("ty-drawer", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "open": truthy(p.open) ? true : undefined, "placement": text(p.placement), "width": text(p.width), "max-height": text(p.maxHeight), "show-handle": text(p.showHandle), "dismissible": text(p.dismissible), "close-label": text(p.closeLabel), "accessible-label": text(p.accessibleLabel), "panel-test-id": text(p.panelTestId), "backdrop-test-id": text(p.backdropTestId) },
    createElement("div", { className: "ty-drawer__backdrop", hidden: (!(truthy(p.open))) ? (true) : undefined, "data-placement": p.placement, "data-testid": p.backdropTestId },
      createElement("div", { className: "ty-drawer", "data-placement": p.placement, "data-width": p.width },
        createElement("div", { className: "ty-drawer__dialog", role: "dialog", "aria-modal": "true", tabIndex: "-1", "aria-labelledby": (slots["title"]) ? (`${instance}-title`) : undefined, "aria-label": (!(slots["title"])) ? (p.accessibleLabel) : undefined, "data-testid": p.panelTestId },
          createElement("header", { className: "ty-drawer__header" },
            (p.placement === "bottom") && (!(p.showHandle === "false")) ? createElement("span", { className: "ty-drawer__handle", "aria-hidden": "true" }) : null,
            (slots["title"]) ? createElement("h2", { className: "ty-drawer__title", id: `${instance}-title` },
              props.title,
            ) : null,
            createElement("button", { className: "ty-button ty-drawer__close", type: "button", "aria-label": p.closeLabel, title: p.closeLabel, "data-variant": "quiet", "data-size": "compact", "data-shape": "circle", "data-icon-only": "" },
              createElement("span", { className: "ty-button__icon", "aria-hidden": "true" },
                createElement("svg", { className: "ty-icon", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": "true", focusable: "false" },
                  createElement("path", { className: "ty-drawer__glyph", d: "M18 6 6 18" }),
                  createElement("path", { className: "ty-drawer__glyph", d: "m6 6 12 12" }),
                ),
              ),
            ),
          ),
          (slots["default"]) ? createElement("div", { className: "ty-drawer__body" },
            props.children,
          ) : null,
          (p.placement === "bottom") ? createElement("div", { className: "ty-drawer__inset", "aria-hidden": "true" }) : null,
        ),
      ),
    ))
})
