// Generated by tools/elements/generate.mjs from packages/ui/src/elements/gradient-mark/definition.ts. Do not edit.
import { createElement, forwardRef, useId, useImperativeHandle, useRef, type ReactNode } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)
const filled = (v: ReactNode) => v !== undefined && v !== null && v !== false && v !== ''

/** App-icon style badge: a rounded square filled with the brand gradient, holding an arbitrary glyph (the default slot). Named by `label` (an img role) or decorative without one. The gradient and corner radius default to token values and can be overridden per instance with CSS values. */
export interface TyGradientMarkProps {
  /** Accessible name; set it and the badge is an img role, leave it out and the badge is decorative (`aria-hidden`). */
  label?: string
  /** Badge size step (24 / 32 / 48 px from the spacing scale). Default: `medium`. */
  size?: "small" | "medium" | "large"
  /** CSS gradient image of the badge (e.g. `linear-gradient(135deg, #e11d48, #7c3aed)`); the default is the token brand gradient (`--ty-info` → `--ty-brand` → `--ty-brand-strong`). Applied as the `--ty-gradient-mark-gradient` custom property when the element upgrades. */
  gradient?: string
  /** CSS corner-radius override (a length or `50%` for a circle); the default is a squircle scaled from the size. Applied as the `--ty-gradient-mark-radius` custom property when the element upgrades. */
  radius?: string
  /** Test hook on the badge (`data-testid`). */
  testId?: string
  /** The glyph inside the badge (an icon or an initial); decorative — the badge is named by `label`. */
  children?: ReactNode
  id?: string
  className?: string
}

const DEFAULTS = { size: "medium" } as const

export const TyGradientMark = forwardRef<HTMLElement, TyGradientMarkProps>(function TyGradientMark(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  const p = {
    label: props.label,
    size: props.size ?? DEFAULTS.size,
    gradient: props.gradient,
    radius: props.radius,
    testId: props.testId,
  }
  const slots: Record<string, boolean> = { "default": filled(props.children) }
  return createElement("ty-gradient-mark", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "label": text(p.label), "size": text(p.size), "gradient": text(p.gradient), "radius": text(p.radius), "test-id": text(p.testId) },
    createElement("span", { className: "ty-gradient-mark", role: (truthy(p.label)) ? ("img") : undefined, "aria-label": p.label, "aria-hidden": (!(truthy(p.label))) ? ("true") : undefined, "data-size": p.size, "data-testid": p.testId },
      (slots["default"]) ? createElement("span", { className: "ty-gradient-mark__glyph", "aria-hidden": "true" },
        props.children,
      ) : null,
    ))
})
