// Generated by tools/elements/generate.mjs from packages/ui/src/elements/heading/definition.ts. Do not edit.
import { createElement, forwardRef, useId, useImperativeHandle, useRef, type ReactNode } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)

/** Section title whose document level (`level`, h1 to h6) and visual step (`appearance`: display, h1, h2, h3 or label) are set independently; unset, the step derives from the level. An optional `eyebrow` labels the section above the heading, outside the heading element. The heading id (`heading-id`, generated otherwise) lets a section or dialog reference it with `aria-labelledby`. `level="2" appearance="h3"` is the Subheading. */
export interface TyHeadingProps {
  /** Document outline level (1 to 6, as its attribute spelling); one h1 per page, no skipped levels. Default: `1`. */
  level?: "1" | "2" | "3" | "4" | "5" | "6"
  /** Visual step from the type scale of §2.2, decoupled from `level`; derived from the level when unset (1 → h1, 2 → h2, 3+ → h3). */
  appearance?: "display" | "h1" | "h2" | "h3" | "label"
  /** Small uppercase label rendered before, and outside, the heading element (the §2.2 eyebrow token); the heading text alone stays the accessible name. */
  eyebrow?: string
  /** Stable id of the heading element, for `aria-labelledby` of the enclosing section or dialog; `<instance>-heading` when unset. */
  headingId?: string
  /** The heading text. */
  children?: ReactNode
  id?: string
  className?: string
}

const DEFAULTS = { level: "1" } as const

export const TyHeading = forwardRef<HTMLElement, TyHeadingProps>(function TyHeading(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  const p = {
    level: props.level ?? DEFAULTS.level,
    appearance: props.appearance,
    eyebrow: props.eyebrow,
    headingId: props.headingId,
  }
  return createElement("ty-heading", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "level": text(p.level), "appearance": text(p.appearance), "eyebrow": text(p.eyebrow), "heading-id": text(p.headingId) },
    createElement("div", { className: "ty-heading-group" },
      (truthy(p.eyebrow)) ? createElement("p", { className: "ty-heading__eyebrow" },
        text(p.eyebrow),
      ) : null,
      (p.level === "1") ? createElement("h1", { className: "ty-heading", id: (text(p.headingId) ?? `${instance}-heading`), "data-appearance": truthy(p.appearance) ? ({"display":"display","h1":"h1","h2":"h2","h3":"h3","label":"label"} as Record<string, string>)[String(p.appearance)] : ({"1":"h1","2":"h2","3":"h3","4":"h3","5":"h3","6":"h3"} as Record<string, string>)[String(p.level)] },
        props.children,
      ) : null,
      (p.level === "2") ? createElement("h2", { className: "ty-heading", id: (text(p.headingId) ?? `${instance}-heading`), "data-appearance": truthy(p.appearance) ? ({"display":"display","h1":"h1","h2":"h2","h3":"h3","label":"label"} as Record<string, string>)[String(p.appearance)] : ({"1":"h1","2":"h2","3":"h3","4":"h3","5":"h3","6":"h3"} as Record<string, string>)[String(p.level)] },
        props.children,
      ) : null,
      (p.level === "3") ? createElement("h3", { className: "ty-heading", id: (text(p.headingId) ?? `${instance}-heading`), "data-appearance": truthy(p.appearance) ? ({"display":"display","h1":"h1","h2":"h2","h3":"h3","label":"label"} as Record<string, string>)[String(p.appearance)] : ({"1":"h1","2":"h2","3":"h3","4":"h3","5":"h3","6":"h3"} as Record<string, string>)[String(p.level)] },
        props.children,
      ) : null,
      (p.level === "4") ? createElement("h4", { className: "ty-heading", id: (text(p.headingId) ?? `${instance}-heading`), "data-appearance": truthy(p.appearance) ? ({"display":"display","h1":"h1","h2":"h2","h3":"h3","label":"label"} as Record<string, string>)[String(p.appearance)] : ({"1":"h1","2":"h2","3":"h3","4":"h3","5":"h3","6":"h3"} as Record<string, string>)[String(p.level)] },
        props.children,
      ) : null,
      (p.level === "5") ? createElement("h5", { className: "ty-heading", id: (text(p.headingId) ?? `${instance}-heading`), "data-appearance": truthy(p.appearance) ? ({"display":"display","h1":"h1","h2":"h2","h3":"h3","label":"label"} as Record<string, string>)[String(p.appearance)] : ({"1":"h1","2":"h2","3":"h3","4":"h3","5":"h3","6":"h3"} as Record<string, string>)[String(p.level)] },
        props.children,
      ) : null,
      (p.level === "6") ? createElement("h6", { className: "ty-heading", id: (text(p.headingId) ?? `${instance}-heading`), "data-appearance": truthy(p.appearance) ? ({"display":"display","h1":"h1","h2":"h2","h3":"h3","label":"label"} as Record<string, string>)[String(p.appearance)] : ({"1":"h1","2":"h2","3":"h3","4":"h3","5":"h3","6":"h3"} as Record<string, string>)[String(p.level)] },
        props.children,
      ) : null,
    ))
})
