// Generated by tools/elements/generate.mjs from packages/ui/src/elements/inline-notice/definition.ts. Do not edit.
import { createElement, forwardRef, useEffect, useId, useImperativeHandle, useRef, type ReactNode } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)
const filled = (v: ReactNode) => v !== undefined && v !== null && v !== false && v !== ''

/** Short message about the state of a form, section or page. Assertive tones (danger and warning unless `urgency` says otherwise) are `role="alert"`, polite ones `role="status"`; a visually hidden tone word precedes the message. Dismissal is the host's: the element emits `ty-dismiss` and moves focus to the next logical element. */
export interface TyInlineNoticeProps {
  /** Semantic tone; colours the surface and picks the default icon and tone word. Default: `info`. */
  tone?: "danger" | "warning" | "info" | "success"
  /** `centre` only for short single-message confirmations. Default: `start`. */
  align?: "start" | "centre"
  /** How the notice is announced when it appears; unset: assertive for danger and warning, polite otherwise. `none` (no live role) for notices present on page load. */
  urgency?: "polite" | "assertive" | "none"
  /** Element for the title; a plain strong paragraph unless configured. Default: `p`. */
  titleAs?: "p" | "h2" | "h3" | "h4"
  /** Shows the dismiss button; the host removes the notice on `ty-dismiss`. */
  dismissible?: boolean
  /** Accessible name of the dismiss button. Default: `Dismiss`. */
  dismissLabel?: string
  /** Visually hidden word announced before a danger notice. Default: `Error: `. */
  toneWordDanger?: string
  /** Visually hidden word announced before a warning notice. Default: `Warning: `. */
  toneWordWarning?: string
  /** Visually hidden word announced before an info notice. Default: `Information: `. */
  toneWordInfo?: string
  /** Visually hidden word announced before a success notice. Default: `Success: `. */
  toneWordSuccess?: string
  /** The message body. */
  children?: ReactNode
  /** Short heading above the message. */
  title?: ReactNode
  /** Overrides the tone's icon (decorative). */
  icon?: ReactNode
  /** Buttons or links below the message (up to two). */
  actions?: ReactNode
  /** The dismiss button was pressed; the host removes the notice. Focus has moved to the next logical element. */
  onDismiss?: () => void
  id?: string
  className?: string
}

const DEFAULTS = { tone: "info", align: "start", titleAs: "p", dismissLabel: "Dismiss", toneWordDanger: "Error: ", toneWordWarning: "Warning: ", toneWordInfo: "Information: ", toneWordSuccess: "Success: " } as const

export const TyInlineNotice = forwardRef<HTMLElement, TyInlineNoticeProps>(function TyInlineNotice(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  useEffect(() => {
    const element = host.current
    if (!element) return
    const listeners: Array<[string, EventListener]> = [
      ["ty-dismiss", () => handlers.current.onDismiss?.()],
    ]
    for (const [type, listener] of listeners) element.addEventListener(type, listener)
    return () => { for (const [type, listener] of listeners) element.removeEventListener(type, listener) }
  }, [])
  const p = {
    tone: props.tone ?? DEFAULTS.tone,
    align: props.align ?? DEFAULTS.align,
    urgency: props.urgency,
    titleAs: props.titleAs ?? DEFAULTS.titleAs,
    dismissible: props.dismissible,
    dismissLabel: props.dismissLabel ?? DEFAULTS.dismissLabel,
    toneWordDanger: props.toneWordDanger ?? DEFAULTS.toneWordDanger,
    toneWordWarning: props.toneWordWarning ?? DEFAULTS.toneWordWarning,
    toneWordInfo: props.toneWordInfo ?? DEFAULTS.toneWordInfo,
    toneWordSuccess: props.toneWordSuccess ?? DEFAULTS.toneWordSuccess,
  }
  const slots: Record<string, boolean> = { "default": filled(props.children), "title": filled(props.title), "icon": filled(props.icon), "actions": filled(props.actions) }
  return createElement("ty-inline-notice", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "tone": text(p.tone), "align": text(p.align), "urgency": text(p.urgency), "title-as": text(p.titleAs), "dismissible": truthy(p.dismissible) ? true : undefined, "dismiss-label": text(p.dismissLabel), "tone-word-danger": text(p.toneWordDanger), "tone-word-warning": text(p.toneWordWarning), "tone-word-info": text(p.toneWordInfo), "tone-word-success": text(p.toneWordSuccess) },
    createElement("div", { className: "ty-notice", role: truthy(p.urgency) ? ({"assertive":"alert","polite":"status"} as Record<string, string>)[String(p.urgency)] : ({"danger":"alert","warning":"alert","info":"status","success":"status"} as Record<string, string>)[String(p.tone)], "data-tone": p.tone, "data-align": p.align },
      createElement("span", { className: "ty-notice__icon", "aria-hidden": "true" },
        (!(slots["icon"])) && (p.tone === "danger") ? createElement("svg", { className: "ty-icon", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": "true", focusable: "false" },
          createElement("circle", { className: "ty-notice__glyph", cx: "12", cy: "12", r: "10" }),
          createElement("line", { className: "ty-notice__glyph", x1: "12", x2: "12", y1: "8", y2: "12" }),
          createElement("line", { className: "ty-notice__glyph", x1: "12", x2: "12.01", y1: "16", y2: "16" }),
        ) : null,
        (!(slots["icon"])) && (p.tone === "warning") ? createElement("svg", { className: "ty-icon", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": "true", focusable: "false" },
          createElement("path", { className: "ty-notice__glyph", d: "m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3" }),
          createElement("path", { className: "ty-notice__glyph", d: "M12 9v4" }),
          createElement("path", { className: "ty-notice__glyph", d: "M12 17h.01" }),
        ) : null,
        (!(slots["icon"])) && (p.tone === "info") ? createElement("svg", { className: "ty-icon", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": "true", focusable: "false" },
          createElement("circle", { className: "ty-notice__glyph", cx: "12", cy: "12", r: "10" }),
          createElement("path", { className: "ty-notice__glyph", d: "M12 16v-4" }),
          createElement("path", { className: "ty-notice__glyph", d: "M12 8h.01" }),
        ) : null,
        (!(slots["icon"])) && (p.tone === "success") ? createElement("svg", { className: "ty-icon", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": "true", focusable: "false" },
          createElement("circle", { className: "ty-notice__glyph", cx: "12", cy: "12", r: "10" }),
          createElement("path", { className: "ty-notice__glyph", d: "m16 9-5.5 5.5L8 12" }),
        ) : null,
        ((slots["icon"])) ? props.icon : null,
      ),
      createElement("div", { className: "ty-notice__body" },
        (slots["title"]) && (p.titleAs === "p") ? createElement("p", { className: "ty-notice__title" },
          (p.tone === "danger") ? createElement("span", { className: "ty-visually-hidden" },
            text(p.toneWordDanger),
          ) : null,
          (p.tone === "warning") ? createElement("span", { className: "ty-visually-hidden" },
            text(p.toneWordWarning),
          ) : null,
          (p.tone === "info") ? createElement("span", { className: "ty-visually-hidden" },
            text(p.toneWordInfo),
          ) : null,
          (p.tone === "success") ? createElement("span", { className: "ty-visually-hidden" },
            text(p.toneWordSuccess),
          ) : null,
          props.title,
        ) : null,
        (slots["title"]) && (p.titleAs === "h2") ? createElement("h2", { className: "ty-notice__title" },
          (p.tone === "danger") ? createElement("span", { className: "ty-visually-hidden" },
            text(p.toneWordDanger),
          ) : null,
          (p.tone === "warning") ? createElement("span", { className: "ty-visually-hidden" },
            text(p.toneWordWarning),
          ) : null,
          (p.tone === "info") ? createElement("span", { className: "ty-visually-hidden" },
            text(p.toneWordInfo),
          ) : null,
          (p.tone === "success") ? createElement("span", { className: "ty-visually-hidden" },
            text(p.toneWordSuccess),
          ) : null,
          props.title,
        ) : null,
        (slots["title"]) && (p.titleAs === "h3") ? createElement("h3", { className: "ty-notice__title" },
          (p.tone === "danger") ? createElement("span", { className: "ty-visually-hidden" },
            text(p.toneWordDanger),
          ) : null,
          (p.tone === "warning") ? createElement("span", { className: "ty-visually-hidden" },
            text(p.toneWordWarning),
          ) : null,
          (p.tone === "info") ? createElement("span", { className: "ty-visually-hidden" },
            text(p.toneWordInfo),
          ) : null,
          (p.tone === "success") ? createElement("span", { className: "ty-visually-hidden" },
            text(p.toneWordSuccess),
          ) : null,
          props.title,
        ) : null,
        (slots["title"]) && (p.titleAs === "h4") ? createElement("h4", { className: "ty-notice__title" },
          (p.tone === "danger") ? createElement("span", { className: "ty-visually-hidden" },
            text(p.toneWordDanger),
          ) : null,
          (p.tone === "warning") ? createElement("span", { className: "ty-visually-hidden" },
            text(p.toneWordWarning),
          ) : null,
          (p.tone === "info") ? createElement("span", { className: "ty-visually-hidden" },
            text(p.toneWordInfo),
          ) : null,
          (p.tone === "success") ? createElement("span", { className: "ty-visually-hidden" },
            text(p.toneWordSuccess),
          ) : null,
          props.title,
        ) : null,
        createElement("div", { className: "ty-notice__message" },
          (!(slots["title"])) && (p.tone === "danger") ? createElement("span", { className: "ty-visually-hidden" },
            text(p.toneWordDanger),
          ) : null,
          (!(slots["title"])) && (p.tone === "warning") ? createElement("span", { className: "ty-visually-hidden" },
            text(p.toneWordWarning),
          ) : null,
          (!(slots["title"])) && (p.tone === "info") ? createElement("span", { className: "ty-visually-hidden" },
            text(p.toneWordInfo),
          ) : null,
          (!(slots["title"])) && (p.tone === "success") ? createElement("span", { className: "ty-visually-hidden" },
            text(p.toneWordSuccess),
          ) : null,
          props.children,
        ),
        (slots["actions"]) ? createElement("div", { className: "ty-notice__actions" },
          props.actions,
        ) : null,
      ),
      (truthy(p.dismissible)) ? createElement("button", { className: "ty-button ty-notice__dismiss", type: "button", "data-variant": "quiet", "data-size": "compact", "data-icon-only": "", "aria-label": p.dismissLabel },
        createElement("span", { className: "ty-button__icon", "aria-hidden": "true" },
          createElement("svg", { className: "ty-icon", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": "true", focusable: "false" },
            createElement("path", { className: "ty-notice__glyph", d: "M18 6 6 18" }),
            createElement("path", { className: "ty-notice__glyph", d: "m6 6 12 12" }),
          ),
        ),
      ) : null,
    ))
})
