// Generated by tools/elements/generate.mjs from packages/ui/src/elements/link/definition.ts. Do not edit.
import { createElement, forwardRef, useId, useImperativeHandle, useRef, type ReactNode, type ChangeEvent, type SyntheticEvent } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)

/** Moves to another location. A native <a> inside, so focus, keyboard activation and opening in a new context are the platform's; an external destination opens in a new context with a safe rel, an icon and a screen-reader hint. */
export interface TyLinkProps {
  /** Destination. The element is a navigation link; an inline action without one is a plain <button class="ty-link" data-action=""> */
  href?: string
  /** `subtle` hides the underline at rest (only where the context makes the link obvious). Default: `underlined`. */
  emphasis?: "underlined" | "subtle"
  /** Opens in a new context with `rel="noopener noreferrer"`, an icon and a screen-reader hint. Inferred on upgrade from absolute URLs to another origin; hosts render it explicitly. */
  external?: boolean
  /** Marks the link as the current page (`aria-current="page"`). */
  current?: boolean
  /** Standalone links (lists, footers) get a 44 px tall hit area; inline prose links do not. */
  standalone?: boolean
  /** Screen-reader hint appended to an external link's name on upgrade; translate through this attribute. Default: `(opens in a new tab)`. */
  newTabLabel?: string
  /** Accessible name when the visible text is not enough (`aria-label`). */
  accessibleLabel?: string
  /** Id of an element describing the link (`aria-describedby`). */
  describedBy?: string
  /** The link text. */
  children?: ReactNode
  /** The native click of the anchor. */
  onClick?: (event: SyntheticEvent) => void
  id?: string
  className?: string
}

const DEFAULTS = { emphasis: "underlined", newTabLabel: "(opens in a new tab)" } as const

export const TyLink = forwardRef<HTMLElement, TyLinkProps>(function TyLink(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  const p = {
    href: props.href,
    emphasis: props.emphasis ?? DEFAULTS.emphasis,
    external: props.external,
    current: props.current,
    standalone: props.standalone,
    newTabLabel: props.newTabLabel ?? DEFAULTS.newTabLabel,
    accessibleLabel: props.accessibleLabel,
    describedBy: props.describedBy,
  }
  return createElement("ty-link", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "href": text(p.href), "emphasis": text(p.emphasis), "external": truthy(p.external) ? true : undefined, "current": truthy(p.current) ? true : undefined, "standalone": truthy(p.standalone) ? true : undefined, "new-tab-label": text(p.newTabLabel), "accessible-label": text(p.accessibleLabel), "described-by": text(p.describedBy) },
    createElement("a", { className: "ty-link", href: p.href, target: (truthy(p.external)) ? ("_blank") : undefined, rel: (truthy(p.external)) ? ("noopener noreferrer") : undefined, "aria-current": (truthy(p.current)) ? ("page") : undefined, "aria-label": p.accessibleLabel, "aria-describedby": p.describedBy, "data-emphasis": p.emphasis, "data-standalone": truthy(p.standalone) ? '' : undefined, onClick: (event: ChangeEvent<HTMLAnchorElement>) => handlers.current.onClick?.(event) },
      props.children,
      (truthy(p.external)) ? createElement("svg", { className: "ty-icon ty-mirror-rtl ty-link__external", "aria-hidden": "true", focusable: "false", width: "24", height: "24", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round" },
        createElement("path", { d: "M15 3h6v6" }),
        createElement("path", { d: "M10 14 21 3" }),
        createElement("path", { d: "M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" }),
      ) : null,
      (truthy(p.external)) ? createElement("span", { className: "ty-visually-hidden ty-link__hint" }) : null,
    ))
})
