// Generated by tools/elements/generate.mjs from packages/ui/src/elements/markdown-view/definition.ts. Do not edit.
import { createElement, forwardRef, useId, useImperativeHandle, useRef } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)

/** Safely renders a small, product-relevant subset of Markdown written by people or produced by models, without ever interpreting raw HTML: paragraphs, lists, headings (real `h2`–`h6`, offset by `headingBase`), fenced code blocks, and inline code, strong, emphasis and http(s) links; everything else is literal text. Static — links are the only focusable content, plus a code block that overflows (a labelled scroll region). */
export interface TyMarkdownViewProps {
  /** Markdown source (the supported subset; anything else renders as literal text). Empty renders nothing. */
  text?: string
  /** Level used for a Markdown level-1 heading (2 to 6); deeper levels follow, capped at 6. Default: `3`. */
  headingBase?: number
  /** Spacing between blocks. Default: `regular`. */
  density?: "regular" | "compact"
  /** Accessible name of a code block that overflows (a scroll region) when it has no language tag; translate through this attribute. Default: `Code block`. */
  codeBlockLabel?: string
  /** Accessible name of an overflowing code block with a language tag; `{language}` is replaced by the tag. Default: `Code block, {language}`. */
  codeBlockLanguageLabel?: string
  /** Screen-reader hint appended to every link (all links open in a new tab); translate through this attribute. Default: `(opens in a new tab)`. */
  newTabLabel?: string
  id?: string
  className?: string
}

const DEFAULTS = { headingBase: 3, density: "regular", codeBlockLabel: "Code block", codeBlockLanguageLabel: "Code block, {language}", newTabLabel: "(opens in a new tab)" } as const

export const TyMarkdownView = forwardRef<HTMLElement, TyMarkdownViewProps>(function TyMarkdownView(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  const p = {
    text: props.text,
    headingBase: props.headingBase ?? DEFAULTS.headingBase,
    density: props.density ?? DEFAULTS.density,
    codeBlockLabel: props.codeBlockLabel ?? DEFAULTS.codeBlockLabel,
    codeBlockLanguageLabel: props.codeBlockLanguageLabel ?? DEFAULTS.codeBlockLanguageLabel,
    newTabLabel: props.newTabLabel ?? DEFAULTS.newTabLabel,
  }
  return createElement("ty-markdown-view", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "text": text(p.text), "heading-base": text(p.headingBase), "density": text(p.density), "code-block-label": text(p.codeBlockLabel), "code-block-language-label": text(p.codeBlockLanguageLabel), "new-tab-label": text(p.newTabLabel) })
})
