// Generated by tools/elements/generate.mjs from packages/ui/src/elements/modal/definition.ts. Do not edit.
import { createElement, forwardRef, useEffect, useId, useImperativeHandle, useRef, type ReactNode } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)
const filled = (v: ReactNode) => v !== undefined && v !== null && v !== false && v !== ''

/** Focused modal window for a decision or a short form: a backdrop and a panel (title, optional description, scrolling body, actions row, optional close button). Controlled through `open`; the element asks to close with `ty-open-change` (Escape, the close button, an allowed backdrop press) and the host flips `open`. Focus moves into the panel on open, is trapped while open, and returns to the invoking element on close; the page behind is inert and does not scroll. */
export interface TyModalProps {
  /** Shown (controlled). The anatomy stays mounted but `hidden` while closed, so nothing reaches the accessibility tree. */
  isOpen?: boolean
  /** Maximum panel width step. Default: `regular`. */
  width?: "narrow" | "regular" | "wide" | "xwide"
  /** `alertdialog` for destructive or blocking confirmations: the backdrop never dismisses it and the close button is hidden, unless the props below say otherwise. Default: `dialog`. */
  role?: "dialog" | "alertdialog"
  /** `true` or `false`; unset: the backdrop dismisses a `dialog`, never an `alertdialog`. */
  dismissOnBackdrop?: string
  /** `true` or `false`; unset: shown on a `dialog`, hidden on an `alertdialog`. */
  showCloseButton?: string
  /** Where focus lands on open; a `[data-autofocus]` control inside wins either way. Unset on an `alertdialog`: the first action (the least destructive, by convention). Default: `first`. */
  initialFocus?: "first" | "title"
  /** An action is pending: closing (Escape, the backdrop, the close button) is disabled and the panel is `aria-busy`. */
  busy?: boolean
  /** Accessible name of the close button. Default: `Close`. */
  closeLabel?: string
  /** Accessible name of the panel when the title slot is empty and no `labelledBy` is given. */
  accessibleLabel?: string
  /** `aria-labelledby` of the panel (a host that renders its own title element), joined before the title slot's heading. */
  labelledBy?: string
  /** `aria-describedby` of the panel, joined before the description slot's paragraph. */
  describedBy?: string
  /** Test hook on the panel (`data-testid`). */
  panelTestId?: string
  /** Test hook on the backdrop (`data-testid`). */
  backdropTestId?: string
  /** The accessible name, rendered as the panel's heading (required by the spec; `accessibleLabel` or `labelledBy` names the panel when it is empty). */
  title?: ReactNode
  /** Accessible description under the header. */
  description?: ReactNode
  /** The body; scrolls when long while the header and the actions stay visible. */
  children?: ReactNode
  /** The actions row (primary last on the end side). Pressing an action runs its own handler; the dialog stays open unless the host flips `isOpen`. */
  actions?: ReactNode
  /** The element asks the host to change visibility — `open: false` on Escape, the close button or an allowed backdrop press. Controlled: the element does not close itself; the host flips `isOpen`. */
  onOpenChange?: (detail: { open: boolean }) => void
  id?: string
  className?: string
}

const DEFAULTS = { width: "regular", role: "dialog", initialFocus: "first", closeLabel: "Close" } as const

export const TyModal = forwardRef<HTMLElement, TyModalProps>(function TyModal(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  useEffect(() => {
    const element = host.current
    if (!element) return
    const listeners: Array<[string, EventListener]> = [
      ["ty-open-change", (event) => handlers.current.onOpenChange?.((event as CustomEvent).detail)],
    ]
    for (const [type, listener] of listeners) element.addEventListener(type, listener)
    return () => { for (const [type, listener] of listeners) element.removeEventListener(type, listener) }
  }, [])
  const p = {
    isOpen: props.isOpen,
    width: props.width ?? DEFAULTS.width,
    role: props.role ?? DEFAULTS.role,
    dismissOnBackdrop: props.dismissOnBackdrop,
    showCloseButton: props.showCloseButton,
    initialFocus: props.initialFocus ?? DEFAULTS.initialFocus,
    busy: props.busy,
    closeLabel: props.closeLabel ?? DEFAULTS.closeLabel,
    accessibleLabel: props.accessibleLabel,
    labelledBy: props.labelledBy,
    describedBy: props.describedBy,
    panelTestId: props.panelTestId,
    backdropTestId: props.backdropTestId,
  }
  const slots: Record<string, boolean> = { "title": filled(props.title), "description": filled(props.description), "default": filled(props.children), "actions": filled(props.actions) }
  return createElement("ty-modal", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "open": truthy(p.isOpen) ? true : undefined, "width": text(p.width), "dialog-role": text(p.role), "dismiss-on-backdrop": text(p.dismissOnBackdrop), "show-close-button": text(p.showCloseButton), "initial-focus": text(p.initialFocus), "busy": truthy(p.busy) ? true : undefined, "close-label": text(p.closeLabel), "accessible-label": text(p.accessibleLabel), "labelled-by": text(p.labelledBy), "described-by": text(p.describedBy), "panel-test-id": text(p.panelTestId), "backdrop-test-id": text(p.backdropTestId) },
    createElement("div", { className: "ty-modal-dialog__backdrop", hidden: (!(truthy(p.isOpen))) ? (true) : undefined, "data-testid": p.backdropTestId },
      createElement("div", { className: "ty-modal-dialog", "data-width": p.width },
        createElement("div", { className: "ty-modal-dialog__panel", role: p.role, "aria-modal": "true", tabIndex: "-1", "aria-labelledby": [text(p.labelledBy) ?? '', (((slots["title"])) ? `${instance}-title` : '')].filter(Boolean).join(' ') || undefined, "aria-describedby": [text(p.describedBy) ?? '', (((slots["description"])) ? `${instance}-description` : '')].filter(Boolean).join(' ') || undefined, "aria-label": (!(slots["title"])) && (!(truthy(p.labelledBy))) ? (p.accessibleLabel) : undefined, "data-busy": truthy(p.busy) ? '' : undefined, "data-testid": p.panelTestId },
          createElement("div", { className: "ty-modal-dialog__inner", "aria-busy": truthy(p.busy) ? 'true' : undefined },
            (slots["title"] || p.showCloseButton === "true" || !(p.role === "alertdialog")) && (slots["title"] || !(p.showCloseButton === "false")) ? createElement("header", { className: "ty-modal-dialog__header" },
              (slots["title"]) ? createElement("h2", { className: "ty-modal-dialog__title", id: `${instance}-title`, tabIndex: "-1" },
                props.title,
              ) : null,
              (!(p.showCloseButton === "false")) && (p.showCloseButton === "true" || !(p.role === "alertdialog")) ? createElement("button", { className: "ty-button ty-modal-dialog__close", type: "button", "aria-label": p.closeLabel, title: p.closeLabel, disabled: truthy(p.busy) || undefined, "data-variant": "quiet", "data-size": "compact", "data-shape": "circle", "data-icon-only": "" },
                createElement("span", { className: "ty-button__icon", "aria-hidden": "true" },
                  createElement("svg", { className: "ty-icon", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": "true", focusable: "false" },
                    createElement("path", { className: "ty-modal-dialog__glyph", d: "M18 6 6 18" }),
                    createElement("path", { className: "ty-modal-dialog__glyph", d: "m6 6 12 12" }),
                  ),
                ),
              ) : null,
            ) : null,
            (slots["description"]) ? createElement("p", { className: "ty-modal-dialog__description", id: `${instance}-description` },
              props.description,
            ) : null,
            (slots["default"]) ? createElement("div", { className: "ty-modal-dialog__body" },
              props.children,
            ) : null,
            (slots["actions"]) ? createElement("footer", { className: "ty-modal-dialog__actions" },
              props.actions,
            ) : null,
          ),
        ),
      ),
    ))
})
