// Generated by tools/elements/generate.mjs from packages/ui/src/elements/native-select/definition.ts. Do not edit.
import { createElement, forwardRef, useId, useImperativeHandle, useRef, type ReactNode, type ChangeEvent, type SyntheticEvent } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)
const filled = (v: ReactNode) => v !== undefined && v !== null && v !== false && v !== ''

/** One value from a short list with the platform select. A native <select> inside, so the picker on touch devices, keyboard, screen-reader support and form participation are the platform's. The options are the host's children. */
export interface TyNativeSelectProps {
  /** The selected value; the element mirrors it into the control (while the user chooses, the live value is the control's own). */
  value?: string
  /** Text of the empty, disabled first option, shown while nothing is selected. */
  placeholder?: string
  /** Form field name; the selected value is sent. */
  name?: string
  /** Native required; the form will not submit while the empty option is the selection. */
  required?: boolean
  /** Native disabled. */
  disabled?: boolean
  /** Painted and announced as invalid without an error message (a surrounding field marks it). */
  invalid?: boolean
  /** Accessible name when there is no visible label. */
  accessibleLabel?: string
  /** `aria-labelledby` from a surrounding field (used when there is no visible label and no `accessibleLabel`). */
  labelledBy?: string
  /** `aria-describedby` from a surrounding field, joined before the select's own parts. */
  describedBy?: string
  /** Explicit id of the control (a surrounding field's control id); `<instance>-control` otherwise. */
  controlId?: string
  /** Test hook on the native select (`data-testid`). */
  testId?: string
  /** The `<option>` and `<optgroup>` children. */
  children?: ReactNode
  /** The visible label above the control. */
  label?: ReactNode
  /** Help text between the label and the control, announced as the description. */
  hint?: ReactNode
  /** The error message; marks the control invalid and is announced. */
  error?: ReactNode
  /** The native change of the select; `value` is the new value. */
  onChange?: (detail: { value: string }, event: SyntheticEvent) => void
  id?: string
  className?: string
}

export const TyNativeSelect = forwardRef<HTMLElement, TyNativeSelectProps>(function TyNativeSelect(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  const p = {
    value: props.value,
    placeholder: props.placeholder,
    name: props.name,
    required: props.required,
    disabled: props.disabled,
    invalid: props.invalid,
    accessibleLabel: props.accessibleLabel,
    labelledBy: props.labelledBy,
    describedBy: props.describedBy,
    controlId: props.controlId,
    testId: props.testId,
  }
  const slots: Record<string, boolean> = { "default": filled(props.children), "label": filled(props.label), "hint": filled(props.hint), "error": filled(props.error) }
  return createElement("ty-native-select", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "value": text(p.value), "placeholder": text(p.placeholder), "name": text(p.name), "required": truthy(p.required) ? true : undefined, "disabled": truthy(p.disabled) ? true : undefined, "invalid": truthy(p.invalid) ? true : undefined, "accessible-label": text(p.accessibleLabel), "labelled-by": text(p.labelledBy), "described-by": text(p.describedBy), "control-id": text(p.controlId), "test-id": text(p.testId) },
    createElement("div", { className: "ty-native-select", "data-invalid": (truthy(p.invalid) || slots["error"]) ? ("") : undefined, "data-disabled": truthy(p.disabled) ? '' : undefined },
      (slots["label"]) ? createElement("label", { className: "ty-native-select__label", htmlFor: (text(p.controlId) ?? `${instance}-control`) },
        props.label,
      ) : null,
      (slots["hint"]) ? createElement("p", { className: "ty-native-select__hint", id: `${instance}-hint` },
        props.hint,
      ) : null,
      createElement("div", { className: "ty-native-select__frame" },
        createElement("select", { className: "ty-native-select__control", id: (text(p.controlId) ?? `${instance}-control`), name: p.name, required: truthy(p.required) || undefined, disabled: truthy(p.disabled) || undefined, "aria-label": (!(slots["label"])) ? (p.accessibleLabel) : undefined, "aria-labelledby": (!(slots["label"])) && (!(truthy(p.accessibleLabel))) ? (p.labelledBy) : undefined, "aria-describedby": [text(p.describedBy) ?? '', (((slots["hint"])) ? `${instance}-hint` : ''), (((slots["error"])) ? `${instance}-error` : '')].filter(Boolean).join(' ') || undefined, "aria-invalid": (truthy(p.invalid) || slots["error"]) ? ("true") : undefined, "data-testid": p.testId, onChange: (event: ChangeEvent<HTMLSelectElement>) => handlers.current.onChange?.({ value: event.currentTarget.value }, event) },
          (truthy(p.placeholder)) ? createElement("option", { className: "ty-native-select__placeholder", label: p.placeholder, value: "", disabled: true }) : null,
          props.children,
        ),
        createElement("svg", { className: "ty-icon ty-native-select__chevron", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": "true", focusable: "false" },
          createElement("path", { className: "ty-native-select__chevron-path", d: "m6 9 6 6 6-6" }),
        ),
      ),
      (slots["error"]) ? createElement("p", { className: "ty-native-select__error", id: `${instance}-error`, role: "alert" },
        createElement("svg", { className: "ty-icon", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": "true", focusable: "false" },
          createElement("path", { className: "ty-native-select__error-glyph", d: "M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20ZM12 8v4M12 16h.01" }),
        ),
        createElement("span", { className: "ty-native-select__error-text" },
          props.error,
        ),
      ) : null,
    ))
})
