// Generated by tools/elements/generate.mjs from packages/ui/src/elements/notification-center/definition.ts. Do not edit.
import { createElement, forwardRef, useEffect, useId, useImperativeHandle, useRef } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)

/** Bell button with an unseen count and the session's notification history in a modal drawer (review, dismiss one, clear all). The host owns the history and feeds it through `notices` (JSON, newest first); the element composes the badge and the entries, asks to open or close with `ty-open-change` (controlled: the host flips `open`), and reports a dismiss (`ty-dismiss`) or a clear (`ty-clear`) so the host can update its own state. Focus moves into the drawer on open, is trapped while open, Escape asks to close, and focus returns to the bell; after a dismissal focus lands on the next entry's dismiss button (or the previous one, or the heading when the list became empty). */
export interface TyNotificationCenterProps {
  /** Drawer shown (controlled). The anatomy stays mounted but `hidden` while closed, so nothing reaches the accessibility tree. */
  open?: boolean
  /** The history as a JSON array, newest first: `[{ "id", "tone", "title", "message"?, "createdAt" }]`, `tone` one of `success`/`error`/`warning`/`info`, `createdAt` a Unix ms timestamp. Left unset (not `"[]"`) while the history is empty. The element renders at most `historyLimit` entries; it never raises toasts itself — the same call that shows a toast feeds this list. */
  notices?: string
  /** Cap of the rendered history (the newest survive). Default: `50`. */
  historyLimit?: number
  /** Accessible name of the bell; with unseen entries the `unreadLabel` phrase is appended. Default: `Notifications`. */
  bellLabel?: string
  /** Unseen phrase appended to the bell name and carried by the badge; `{count}` is replaced. Default: `{count} unread`. */
  unreadLabel?: string
  /** Heading of the drawer; also its accessible name (aria-labelledby). Default: `Notifications`. */
  titleLabel?: string
  /** Name of the clear-all button (shown only with entries). Default: `Clear all`. */
  clearAllLabel?: string
  /** Accessible name of the close button. Default: `Close`. */
  closeLabel?: string
  /** Accessible name of an entry's dismiss button; `{title}` is replaced by the entry's title. Default: `Dismiss, {title}`. */
  dismissLabel?: string
  /** The empty view's sentence. Default: `There are no notifications in this session.`. */
  emptyLabel?: string
  /** Announced politely after clear all (no confirmation: history only). Default: `Notifications cleared`. */
  clearedLabel?: string
  /** Tone word of a success entry. Default: `Success`. */
  toneSuccess?: string
  /** Tone word of an error entry. Default: `Error`. */
  toneError?: string
  /** Tone word of a warning entry. Default: `Warning`. */
  toneWarning?: string
  /** Tone word of an information entry. Default: `Information`. */
  toneInfo?: string
  /** Relative time of an entry less than a minute old. Default: `just now`. */
  timeJustNow?: string
  /** Relative time of an entry minutes old; `{count}` is replaced. Default: `{count} minutes ago`. */
  timeMinutesAgo?: string
  /** Relative time of an entry hours old; `{count}` is replaced. Default: `{count} hours ago`. */
  timeHoursAgo?: string
  /** Relative time of an entry days old; `{count}` is replaced. Default: `{count} days ago`. */
  timeDaysAgo?: string
  /** The element asks the host to change visibility — `open: true` on a bell press, `open: false` on Escape, the close button, a backdrop press or a second bell press. Controlled: the element does not toggle itself; the host flips `open`. */
  onOpenChange?: (detail: { open: boolean }) => void
  /** An entry's dismiss button was pressed. The element drops the entry from its rendered history at once; the host removes it from its own state. */
  onDismiss?: (detail: { id: string }) => void
  /** Clear all was pressed (no confirmation: history only). The element empties its rendered history and announces the `clearedLabel` politely; the host clears its own state. */
  onClear?: () => void
  id?: string
  className?: string
}

const DEFAULTS = { historyLimit: 50, bellLabel: "Notifications", unreadLabel: "{count} unread", titleLabel: "Notifications", clearAllLabel: "Clear all", closeLabel: "Close", dismissLabel: "Dismiss, {title}", emptyLabel: "There are no notifications in this session.", clearedLabel: "Notifications cleared", toneSuccess: "Success", toneError: "Error", toneWarning: "Warning", toneInfo: "Information", timeJustNow: "just now", timeMinutesAgo: "{count} minutes ago", timeHoursAgo: "{count} hours ago", timeDaysAgo: "{count} days ago" } as const

export const TyNotificationCenter = forwardRef<HTMLElement, TyNotificationCenterProps>(function TyNotificationCenter(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  useEffect(() => {
    const element = host.current
    if (!element) return
    const listeners: Array<[string, EventListener]> = [
      ["ty-open-change", (event) => handlers.current.onOpenChange?.((event as CustomEvent).detail)],
      ["ty-dismiss", (event) => handlers.current.onDismiss?.((event as CustomEvent).detail)],
      ["ty-clear", () => handlers.current.onClear?.()],
    ]
    for (const [type, listener] of listeners) element.addEventListener(type, listener)
    return () => { for (const [type, listener] of listeners) element.removeEventListener(type, listener) }
  }, [])
  const p = {
    open: props.open,
    notices: props.notices,
    historyLimit: props.historyLimit ?? DEFAULTS.historyLimit,
    bellLabel: props.bellLabel ?? DEFAULTS.bellLabel,
    unreadLabel: props.unreadLabel ?? DEFAULTS.unreadLabel,
    titleLabel: props.titleLabel ?? DEFAULTS.titleLabel,
    clearAllLabel: props.clearAllLabel ?? DEFAULTS.clearAllLabel,
    closeLabel: props.closeLabel ?? DEFAULTS.closeLabel,
    dismissLabel: props.dismissLabel ?? DEFAULTS.dismissLabel,
    emptyLabel: props.emptyLabel ?? DEFAULTS.emptyLabel,
    clearedLabel: props.clearedLabel ?? DEFAULTS.clearedLabel,
    toneSuccess: props.toneSuccess ?? DEFAULTS.toneSuccess,
    toneError: props.toneError ?? DEFAULTS.toneError,
    toneWarning: props.toneWarning ?? DEFAULTS.toneWarning,
    toneInfo: props.toneInfo ?? DEFAULTS.toneInfo,
    timeJustNow: props.timeJustNow ?? DEFAULTS.timeJustNow,
    timeMinutesAgo: props.timeMinutesAgo ?? DEFAULTS.timeMinutesAgo,
    timeHoursAgo: props.timeHoursAgo ?? DEFAULTS.timeHoursAgo,
    timeDaysAgo: props.timeDaysAgo ?? DEFAULTS.timeDaysAgo,
  }
  return createElement("ty-notification-center", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "open": truthy(p.open) ? true : undefined, "notices": text(p.notices), "history-limit": text(p.historyLimit), "bell-label": text(p.bellLabel), "unread-label": text(p.unreadLabel), "title-label": text(p.titleLabel), "clear-all-label": text(p.clearAllLabel), "close-label": text(p.closeLabel), "dismiss-label": text(p.dismissLabel), "empty-label": text(p.emptyLabel), "cleared-label": text(p.clearedLabel), "tone-success": text(p.toneSuccess), "tone-error": text(p.toneError), "tone-warning": text(p.toneWarning), "tone-info": text(p.toneInfo), "time-just-now": text(p.timeJustNow), "time-minutes-ago": text(p.timeMinutesAgo), "time-hours-ago": text(p.timeHoursAgo), "time-days-ago": text(p.timeDaysAgo) },
    createElement("span", { className: "ty-notification-center" },
      createElement("span", { className: "ty-notification-center__bell" },
        createElement("button", { className: "ty-button ty-notification-center__trigger", type: "button", "aria-label": p.bellLabel, "aria-haspopup": "dialog", "aria-expanded": truthy(p.open) ? 'true' : undefined, "aria-controls": `${instance}-dialog`, "data-variant": "quiet", "data-icon-only": "" },
          createElement("span", { className: "ty-button__icon", "aria-hidden": "true" },
            createElement("svg", { className: "ty-icon", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": "true", focusable: "false" },
              createElement("path", { className: "ty-notification-center__glyph", d: "M10.268 21a2 2 0 0 0 3.464 0" }),
              createElement("path", { className: "ty-notification-center__glyph", d: "M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326" }),
            ),
          ),
        ),
      ),
      createElement("div", { className: "ty-notification-center__backdrop", hidden: (!(truthy(p.open))) ? (true) : undefined },
        createElement("div", { className: "ty-notification-center__drawer" },
          createElement("div", { className: "ty-notification-center__dialog", role: "dialog", "aria-modal": "true", tabIndex: "-1", id: `${instance}-dialog`, "aria-labelledby": `${instance}-title` },
            createElement("header", { className: "ty-notification-center__head" },
              createElement("svg", { className: "ty-icon", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": "true", focusable: "false" },
                createElement("path", { className: "ty-notification-center__glyph", d: "M10.268 21a2 2 0 0 0 3.464 0" }),
                createElement("path", { className: "ty-notification-center__glyph", d: "M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326" }),
              ),
              createElement("h2", { className: "ty-notification-center__heading", id: `${instance}-title`, tabIndex: "-1" },
                text(p.titleLabel),
              ),
              createElement("button", { className: "ty-button ty-notification-center__clear", type: "button", hidden: (!(truthy(p.notices))) ? (true) : undefined, "data-variant": "quiet", "data-size": "compact" },
                text(p.clearAllLabel),
              ),
              createElement("button", { className: "ty-button ty-notification-center__close", type: "button", "aria-label": p.closeLabel, title: p.closeLabel, "data-variant": "quiet", "data-size": "compact", "data-shape": "circle", "data-icon-only": "" },
                createElement("span", { className: "ty-button__icon", "aria-hidden": "true" },
                  createElement("svg", { className: "ty-icon", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": "true", focusable: "false" },
                    createElement("path", { className: "ty-notification-center__glyph", d: "M18 6 6 18" }),
                    createElement("path", { className: "ty-notification-center__glyph", d: "m6 6 12 12" }),
                  ),
                ),
              ),
            ),
            createElement("div", { className: "ty-notification-center__empty", hidden: (truthy(p.notices)) ? (true) : undefined },
              createElement("svg", { className: "ty-icon", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": "true", focusable: "false" },
                createElement("path", { className: "ty-notification-center__glyph", d: "M10.268 21a2 2 0 0 0 3.464 0" }),
                createElement("path", { className: "ty-notification-center__glyph", d: "M17 17H4a1 1 0 0 1-.74-1.673C4.59 13.956 6 12.499 6 8a6 6 0 0 1 .258-1.742" }),
                createElement("path", { className: "ty-notification-center__glyph", d: "m2 2 20 20" }),
                createElement("path", { className: "ty-notification-center__glyph", d: "M8.668 3.01A6 6 0 0 1 18 8c0 2.687.77 4.653 1.707 6.05" }),
              ),
              createElement("p", { className: "ty-notification-center__empty-text" },
                text(p.emptyLabel),
              ),
            ),
            createElement("ul", { className: "ty-notification-center__list", hidden: (!(truthy(p.notices))) ? (true) : undefined }),
          ),
        ),
      ),
      createElement("span", { className: "ty-visually-hidden ty-notification-center__status", role: "status" }),
    ))
})
