// Generated by tools/elements/generate.mjs from packages/ui/src/elements/page-header/definition.ts. Do not edit.
import { createElement, forwardRef, useId, useImperativeHandle, useRef, type ReactNode, type ChangeEvent, type SyntheticEvent } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)
const filled = (v: ReactNode) => v !== undefined && v !== null && v !== false && v !== ''

/** The single top-of-page block that names the page: optional breadcrumbs, eyebrow, leading icon, title, reading summary, metadata row and page actions, plus a free slot below for tags, tabs or filters. `scale` picks the type step (`page` the h1 step, `display` for login and public pages, `section` inside a section); `heading-level` the document level. With `editable` the title is an input named by `title-label` and a visually hidden heading keeps the outline. Below 640 px the actions move under the summary and span the width (stylesheet). */
export interface TyPageHeaderProps {
  /** Page title; the heading text. Not needed with `editable` (`value` carries the text). */
  title?: string
  /** Heading level of the title (1, 2 or 3, as its attribute spelling); exactly one level-1 heading per page, which the header provides by default. Default: `1`. */
  headingLevel?: "1" | "2" | "3"
  /** `page` uses the h1 step; `display` the display step (login, public page only); `section` the h3 step. Default: `page`. */
  scale?: "page" | "display" | "section"
  /** Short uppercase context line above the title (the §2.2 eyebrow token). */
  eyebrow?: string
  /** One or two sentences (body-lg, max 60ch) saying what the screen shows. */
  summary?: string
  /** The title is an input that looks like the title (editorial screens); a visually hidden heading of the same level keeps the document outline. */
  editable?: boolean
  /** The editable title's text (controlled); the element mirrors it into the input (while the user types, the live value is the input's own). */
  value?: string
  /** Placeholder of the editable title (the empty state); also the hidden heading's text while empty. */
  titlePlaceholder?: string
  /** Accessible name of the editable title input. Default: `Page title`. */
  titleLabel?: string
  /** Id of the title heading, for `aria-labelledby` of the page region; `<instance>-title` when unset. */
  headingId?: string
  /** The breadcrumb navigation, rendered above the title. */
  breadcrumbs?: ReactNode
  /** A decorative leading icon, in an accent-soft container (`aria-hidden`). */
  icon?: ReactNode
  /** The metadata row: `li.ty-page-header__meta-item` items of icon plus short text (owner, date, count); icons decorative, text in reading order. */
  meta?: ReactNode
  /** Page actions, aligned to the end: at most one primary button plus secondary buttons (§2.10); below 640 px they move under the summary and span the width. */
  actions?: ReactNode
  /** Host-provided validation message under the editable title; marks it invalid and is announced. */
  error?: ReactNode
  /** Extra content below the header (tags, tabs, filters). */
  children?: ReactNode
  /** Typing in the editable title; `value` is the whole text. */
  onTitleChange?: (detail: { value: string }, event: SyntheticEvent) => void
  id?: string
  className?: string
}

const DEFAULTS = { headingLevel: "1", scale: "page", titleLabel: "Page title" } as const

export const TyPageHeader = forwardRef<HTMLElement, TyPageHeaderProps>(function TyPageHeader(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  const p = {
    title: props.title,
    headingLevel: props.headingLevel ?? DEFAULTS.headingLevel,
    scale: props.scale ?? DEFAULTS.scale,
    eyebrow: props.eyebrow,
    summary: props.summary,
    editable: props.editable,
    value: props.value,
    titlePlaceholder: props.titlePlaceholder,
    titleLabel: props.titleLabel ?? DEFAULTS.titleLabel,
    headingId: props.headingId,
  }
  const slots: Record<string, boolean> = { "breadcrumbs": filled(props.breadcrumbs), "icon": filled(props.icon), "meta": filled(props.meta), "actions": filled(props.actions), "error": filled(props.error), "default": filled(props.children) }
  return createElement("ty-page-header", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "title": text(p.title), "heading-level": text(p.headingLevel), "scale": text(p.scale), "eyebrow": text(p.eyebrow), "summary": text(p.summary), "editable": truthy(p.editable) ? true : undefined, "value": text(p.value), "title-placeholder": text(p.titlePlaceholder), "title-label": text(p.titleLabel), "heading-id": text(p.headingId) },
    createElement("div", { className: "ty-page-header", "data-scale": p.scale },
      (slots["breadcrumbs"]) ? createElement("div", { className: "ty-page-header__breadcrumbs" },
        props.breadcrumbs,
      ) : null,
      createElement("div", { className: "ty-page-header__row" },
        (slots["icon"]) ? createElement("span", { className: "ty-page-header__icon", "aria-hidden": "true" },
          props.icon,
        ) : null,
        createElement("div", { className: "ty-page-header__text" },
          (truthy(p.eyebrow)) ? createElement("p", { className: "ty-page-header__eyebrow" },
            text(p.eyebrow),
          ) : null,
          (!(truthy(p.editable))) && (p.headingLevel === "1") ? createElement("h1", { className: "ty-page-header__title", id: (text(p.headingId) ?? `${instance}-title`) },
            text(p.title),
          ) : null,
          (!(truthy(p.editable))) && (p.headingLevel === "2") ? createElement("h2", { className: "ty-page-header__title", id: (text(p.headingId) ?? `${instance}-title`) },
            text(p.title),
          ) : null,
          (!(truthy(p.editable))) && (p.headingLevel === "3") ? createElement("h3", { className: "ty-page-header__title", id: (text(p.headingId) ?? `${instance}-title`) },
            text(p.title),
          ) : null,
          (truthy(p.editable)) && (p.headingLevel === "1") ? createElement("h1", { className: "ty-heading ty-visually-hidden", id: (text(p.headingId) ?? `${instance}-title`) },
            ((truthy(p.value))) ? text(p.value) : null,
            ((!(truthy(p.value)))) ? text(p.titlePlaceholder) : null,
          ) : null,
          (truthy(p.editable)) && (p.headingLevel === "2") ? createElement("h2", { className: "ty-heading ty-visually-hidden", id: (text(p.headingId) ?? `${instance}-title`) },
            ((truthy(p.value))) ? text(p.value) : null,
            ((!(truthy(p.value)))) ? text(p.titlePlaceholder) : null,
          ) : null,
          (truthy(p.editable)) && (p.headingLevel === "3") ? createElement("h3", { className: "ty-heading ty-visually-hidden", id: (text(p.headingId) ?? `${instance}-title`) },
            ((truthy(p.value))) ? text(p.value) : null,
            ((!(truthy(p.value)))) ? text(p.titlePlaceholder) : null,
          ) : null,
          (truthy(p.editable)) ? createElement("input", { className: "ty-page-header__title-input ty-page-header__title", "aria-label": p.titleLabel, placeholder: p.titlePlaceholder, "aria-invalid": (slots["error"]) ? ("true") : undefined, "aria-describedby": [(((slots["error"])) ? `${instance}-error` : '')].filter(Boolean).join(' ') || undefined, "data-invalid": (slots["error"]) ? ("") : undefined, onTitleChange: (event: ChangeEvent<HTMLInputElement>) => handlers.current.onTitleChange?.({ value: event.currentTarget.value }, event) }) : null,
          (truthy(p.editable)) && (slots["error"]) ? createElement("p", { className: "ty-page-header__error", id: `${instance}-error` },
            props.error,
          ) : null,
          (truthy(p.summary)) ? createElement("p", { className: "ty-page-header__summary" },
            text(p.summary),
          ) : null,
          (slots["meta"]) ? createElement("ul", { className: "ty-page-header__meta" },
            props.meta,
          ) : null,
        ),
        (slots["actions"]) ? createElement("div", { className: "ty-page-header__actions" },
          props.actions,
        ) : null,
      ),
      (slots["default"]) ? createElement("div", { className: "ty-page-header__extra" },
        props.children,
      ) : null,
    ))
})
