// Generated by tools/elements/generate.mjs from packages/ui/src/elements/popover/definition.ts. Do not edit.
import { createElement, forwardRef, useEffect, useId, useImperativeHandle, useRef, type ReactNode } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)
const filled = (v: ReactNode) => v !== undefined && v !== null && v !== false && v !== ''

/** Non-modal floating panel anchored to a trigger, for short explanations or arbitrary small content (help text, a mini form, a brand menu). The trigger is the host's own focusable element in the trigger slot — or the built-in info button when the slot is empty and `triggerLabel` names it. The element wires aria-expanded on the trigger, places the panel with the shared placement model (side preference, collision flip, viewport clamp, arrow inset), and asks to close with `ty-open-change` on Escape, an outside press, or focus leaving the panel; the host flips `open`. Not a focus trap — content that needs one is a dialog, not a popover. */
export interface TyPopoverProps {
  /** Shown (controlled). The anatomy stays mounted but `hidden` while closed, so nothing reaches the accessibility tree. */
  open?: boolean
  /** Accessible name of the built-in info trigger (required when the trigger slot is empty). */
  triggerLabel?: string
  /** Heading at the top of the panel; also its accessible name. */
  title?: string
  /** Preferred side; `start`/`end` follow the reading direction. Flips when there is no room. Default: `bottom`. */
  placement?: "top" | "end" | "bottom" | "start"
  /** Alignment along the chosen side. Default: `center`. */
  align?: "start" | "center" | "end"
  /** Gap between trigger and panel as a step of the spacing scale (0–9); the arrow's inset is added to it. Default: `2`. */
  offset?: string
  /** `true` or `false`; unset: the arrow shows. */
  showArrow?: string
  /** Test hook on the panel (`data-testid`). */
  panelTestId?: string
  /** Accessible name of the panel when `title` is empty. */
  accessibleLabel?: string
  /** The host's own toggle — any single focusable element; wired to the panel (aria-expanded, activation). Empty: the built-in info button. */
  trigger?: ReactNode
  /** The panel body. */
  children?: ReactNode
  /** The element asks the host to change visibility — `open: false` on Escape, an outside press or focus leaving the panel, `open: true` on a trigger activation. Controlled: the element does not toggle itself; the host flips `open`. */
  onOpenChange?: (detail: { open: boolean }) => void
  id?: string
  className?: string
}

const DEFAULTS = { placement: "bottom", align: "center", offset: "2" } as const

export const TyPopover = forwardRef<HTMLElement, TyPopoverProps>(function TyPopover(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  useEffect(() => {
    const element = host.current
    if (!element) return
    const listeners: Array<[string, EventListener]> = [
      ["ty-open-change", (event) => handlers.current.onOpenChange?.((event as CustomEvent).detail)],
    ]
    for (const [type, listener] of listeners) element.addEventListener(type, listener)
    return () => { for (const [type, listener] of listeners) element.removeEventListener(type, listener) }
  }, [])
  const p = {
    open: props.open,
    triggerLabel: props.triggerLabel,
    title: props.title,
    placement: props.placement ?? DEFAULTS.placement,
    align: props.align ?? DEFAULTS.align,
    offset: props.offset ?? DEFAULTS.offset,
    showArrow: props.showArrow,
    panelTestId: props.panelTestId,
    accessibleLabel: props.accessibleLabel,
  }
  const slots: Record<string, boolean> = { "trigger": filled(props.trigger), "default": filled(props.children) }
  return createElement("ty-popover", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "open": truthy(p.open) ? true : undefined, "trigger-label": text(p.triggerLabel), "title": text(p.title), "placement": text(p.placement), "align": text(p.align), "offset": text(p.offset), "show-arrow": text(p.showArrow), "panel-test-id": text(p.panelTestId), "accessible-label": text(p.accessibleLabel) },
    createElement("div", { className: "ty-popover__anchor" },
      (!(slots["trigger"])) ? createElement("button", { className: "ty-button ty-popover__trigger", type: "button", "aria-label": p.triggerLabel, "aria-haspopup": "dialog", "data-variant": "quiet", "data-size": "compact", "data-shape": "circle", "data-icon-only": "" },
        createElement("span", { className: "ty-button__icon", "aria-hidden": "true" },
          createElement("svg", { className: "ty-icon", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": "true", focusable: "false" },
            createElement("circle", { className: "ty-popover__glyph", cx: "12", cy: "12", r: "10" }),
            createElement("path", { className: "ty-popover__glyph", d: "M12 16v-4" }),
            createElement("path", { className: "ty-popover__glyph", d: "M12 8h.01" }),
          ),
        ),
      ) : null,
      ((slots["trigger"])) ? props.trigger : null,
      createElement("div", { className: "ty-popover", hidden: (!(truthy(p.open))) ? (true) : undefined, role: "dialog", "data-placement": p.placement, "data-testid": p.panelTestId },
        (!(p.showArrow === "false")) ? createElement("div", { className: "ty-popover__arrow", "aria-hidden": "true" }) : null,
        createElement("div", { className: "ty-popover__dialog" },
          (truthy(p.title)) ? createElement("h3", { className: "ty-popover__title" },
            text(p.title),
          ) : null,
          (slots["default"]) ? createElement("div", { className: "ty-popover__content" },
            props.children,
          ) : null,
        ),
      ),
    ))
})
