// Generated by tools/elements/generate.mjs from packages/ui/src/elements/progress-bar/definition.ts. Do not edit.
import { createElement, forwardRef, useId, useImperativeHandle, useRef } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)

/** Determinate or indeterminate task progress (upload, batch run, profile completion). Not focusable; the host announces completion through a Toast or status message, not through the bar. Values outside the range are clamped on upgrade; the fill width changes with `--ty-dur-quick`, instantly under reduced motion, where the indeterminate sweep becomes a static partial fill with the label still stating "in progress". */
export interface TyProgressBarProps {
  /** Current value; clamped into the range on upgrade. Default: `0`. */
  value?: number
  /** Start of the range. Default: `0`. */
  minValue?: number
  /** End of the range; reaching it is the complete state. Default: `100`. */
  maxValue?: number
  /** Visible and accessible name (required unless `accessibleLabel` is given). */
  label?: string
  /** Accessible name when there is no visible label (`aria-label`). */
  accessibleLabel?: string
  /** Custom value text, such as "3 of 8 steps"; the computed percentage when unset. */
  valueLabel?: string
  /** `true` or `false`; unset: the value text shows. An indeterminate bar always shows its "in progress" text. */
  showValue?: string
  /** Unknown progress: no `aria-valuenow` and no percentage, the value text states "in progress". */
  indeterminate?: boolean
  /** Value text of an indeterminate bar; translate through this attribute. Default: `In progress`. */
  inProgressLabel?: string
  /** Semantic tone of the fill; never the only signal (pair with value text or a status word). Default: `accent`. */
  tone?: "accent" | "success" | "warning" | "danger"
  /** Track thickness. Default: `regular`. */
  size?: "thin" | "regular"
  id?: string
  className?: string
}

const DEFAULTS = { value: 0, minValue: 0, maxValue: 100, inProgressLabel: "In progress", tone: "accent", size: "regular" } as const

export const TyProgressBar = forwardRef<HTMLElement, TyProgressBarProps>(function TyProgressBar(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  const p = {
    value: props.value ?? DEFAULTS.value,
    minValue: props.minValue ?? DEFAULTS.minValue,
    maxValue: props.maxValue ?? DEFAULTS.maxValue,
    label: props.label,
    accessibleLabel: props.accessibleLabel,
    valueLabel: props.valueLabel,
    showValue: props.showValue,
    indeterminate: props.indeterminate,
    inProgressLabel: props.inProgressLabel ?? DEFAULTS.inProgressLabel,
    tone: props.tone ?? DEFAULTS.tone,
    size: props.size ?? DEFAULTS.size,
  }
  return createElement("ty-progress-bar", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "value": text(p.value), "min-value": text(p.minValue), "max-value": text(p.maxValue), "label": text(p.label), "accessible-label": text(p.accessibleLabel), "value-label": text(p.valueLabel), "show-value": text(p.showValue), "indeterminate": truthy(p.indeterminate) ? true : undefined, "in-progress-label": text(p.inProgressLabel), "tone": text(p.tone), "size": text(p.size) },
    createElement("div", { className: "ty-progress", role: "progressbar", "aria-labelledby": (truthy(p.label)) ? (`${instance}-label`) : undefined, "aria-label": (!(truthy(p.label))) ? (p.accessibleLabel) : undefined, "aria-valuemin": p.minValue, "aria-valuemax": p.maxValue, "aria-valuenow": (!(truthy(p.indeterminate))) ? (p.value) : undefined, "aria-valuetext": (!(truthy(p.indeterminate))) ? (p.valueLabel) : undefined, "data-tone": p.tone, "data-size": p.size, "data-indeterminate": truthy(p.indeterminate) ? '' : undefined },
      (truthy(p.label) || truthy(p.indeterminate) || !(p.showValue === "false")) ? createElement("div", { className: "ty-progress__header" },
        (truthy(p.label)) ? createElement("span", { className: "ty-progress__label", id: `${instance}-label` },
          text(p.label),
        ) : null,
        (truthy(p.indeterminate) || !(p.showValue === "false")) ? createElement("span", { className: "ty-progress__value" }) : null,
      ) : null,
      createElement("div", { className: "ty-progress__track", "aria-hidden": "true" },
        createElement("div", { className: "ty-progress__fill" }),
      ),
    ))
})
