// Generated by tools/elements/generate.mjs from packages/ui/src/elements/segmented-control/definition.ts. Do not edit.
import { createElement, forwardRef, useEffect, useId, useImperativeHandle, useRef } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)

/** Exactly one of a small set (two to five) of mutually exclusive options, changed in place — a radio group painted as segments. The segments are composed by the element from `options` (JSON); selecting the selected segment again does nothing. With `value` the control is controlled (the host answers `ty-change`); without it the element keeps the selection and mirrors it into the `value` attribute. */
export interface TySegmentedControlProps {
  /** The segments as a JSON array of `string` (both value and label) or `{ "value", "label", "icon"? }`; `icon` is the `d` of a 24×24 stroke path (lucide style). */
  options?: string
  /** The selected value (controlled). Unset, the element keeps the selection itself and mirrors it here. */
  value?: string
  /** The initially selected value when uncontrolled; the first option when unset. */
  defaultValue?: string
  /** Accessible name of the group (required). */
  label?: string
  /** Visible height; the hit area stays at least 44 px on every size. Default: `regular`. */
  size?: "compact" | "regular" | "large"
  /** The segments share the available width equally; labels truncate with the full label as the accessible name. */
  fullWidth?: boolean
  /** The whole control disabled; the group is exposed as disabled and nothing selects. */
  disabled?: boolean
  /** Hide the labels visually; each label stays the segment's accessible name. */
  iconOnly?: boolean
  /** The selection changed; `value` is the new value. Only real changes fire it — re-selecting the selected segment does nothing. */
  onChange?: (detail: { value: string }) => void
  id?: string
  className?: string
}

const DEFAULTS = { size: "regular" } as const

export const TySegmentedControl = forwardRef<HTMLElement, TySegmentedControlProps>(function TySegmentedControl(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  useEffect(() => {
    const element = host.current
    if (!element) return
    const listeners: Array<[string, EventListener]> = [
      ["ty-change", (event) => handlers.current.onChange?.((event as CustomEvent).detail)],
    ]
    for (const [type, listener] of listeners) element.addEventListener(type, listener)
    return () => { for (const [type, listener] of listeners) element.removeEventListener(type, listener) }
  }, [])
  const p = {
    options: props.options,
    value: props.value,
    defaultValue: props.defaultValue,
    label: props.label,
    size: props.size ?? DEFAULTS.size,
    fullWidth: props.fullWidth,
    disabled: props.disabled,
    iconOnly: props.iconOnly,
  }
  return createElement("ty-segmented-control", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "options": text(p.options), "value": text(p.value), "default-value": text(p.defaultValue), "label": text(p.label), "size": text(p.size), "full-width": truthy(p.fullWidth) ? true : undefined, "disabled": truthy(p.disabled) ? true : undefined, "icon-only": truthy(p.iconOnly) ? true : undefined },
    createElement("div", { className: "ty-segmented-control", role: "radiogroup", "aria-label": p.label, "aria-disabled": truthy(p.disabled) ? 'true' : undefined, "data-size": p.size, "data-full-width": truthy(p.fullWidth) ? '' : undefined, "data-icon-only": truthy(p.iconOnly) ? '' : undefined, "data-disabled": truthy(p.disabled) ? '' : undefined }))
})
