// Generated by tools/elements/generate.mjs from packages/ui/src/elements/separator/definition.ts. Do not edit.
import { createElement, forwardRef, useId, useImperativeHandle, useRef, type ReactNode } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)
const filled = (v: ReactNode) => v !== undefined && v !== null && v !== false && v !== ''

/** Thin rule between groups of content, optionally with a short caption centred on it ("or"). Decorative by default (`aria-hidden`); `semantic` exposes the non-focusable separator role. A captioned rule keeps the caption readable as plain text and the strokes decorative, so it never carries the role. */
export interface TySeparatorProps {
  /** Direction of the rule; vertical takes the height of its row. Default: `horizontal`. */
  orientation?: "horizontal" | "vertical"
  /** Line strength: `--ty-line` or the fainter `--ty-line-soft`. Default: `regular`. */
  emphasis?: "regular" | "soft"
  /** Exposes the separator role (with `aria-orientation`); decorative otherwise. */
  semantic?: boolean
  /** Margin step from the spacing scale. Default: `regular`. */
  spacing?: "none" | "regular" | "roomy"
  /** Short text centred on the rule, such as "or"; readable plain text between the two decorative strokes. */
  caption?: ReactNode
  id?: string
  className?: string
}

const DEFAULTS = { orientation: "horizontal", emphasis: "regular", spacing: "regular" } as const

export const TySeparator = forwardRef<HTMLElement, TySeparatorProps>(function TySeparator(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  const p = {
    orientation: props.orientation ?? DEFAULTS.orientation,
    emphasis: props.emphasis ?? DEFAULTS.emphasis,
    semantic: props.semantic,
    spacing: props.spacing ?? DEFAULTS.spacing,
  }
  const slots: Record<string, boolean> = { "caption": filled(props.caption) }
  return createElement("ty-separator", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "orientation": text(p.orientation), "emphasis": text(p.emphasis), "semantic": truthy(p.semantic) ? true : undefined, "spacing": text(p.spacing) },
    createElement("div", { className: "ty-separator", role: (truthy(p.semantic)) && (!(slots["caption"])) ? ("separator") : undefined, "aria-orientation": (truthy(p.semantic)) && (!(slots["caption"])) ? (p.orientation) : undefined, "aria-hidden": (!(truthy(p.semantic))) && (!(slots["caption"])) ? ("true") : undefined, "data-orientation": p.orientation, "data-emphasis": p.emphasis, "data-spacing": p.spacing, "data-captioned": (slots["caption"]) ? ("") : undefined },
      (slots["caption"]) ? createElement("span", { className: "ty-separator__line", "aria-hidden": "true" }) : null,
      (slots["caption"]) ? createElement("span", { className: "ty-separator__caption" },
        props.caption,
      ) : null,
      (slots["caption"]) ? createElement("span", { className: "ty-separator__line", "aria-hidden": "true" }) : null,
    ))
})
