// Generated by tools/elements/generate.mjs from packages/ui/src/elements/section-heading/definition.ts. Do not edit.
import { createElement, forwardRef, useId, useImperativeHandle, useRef, type ReactNode } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)
const filled = (v: ReactNode) => v !== undefined && v !== null && v !== false && v !== ''

/** Heads a section inside a page or a sheet: the title at the section level (h2 by default, h3 or h4 inside a sheet), an optional subtitle line (plain meta text, not a heading), an optional decorative leading icon, and a `trailing` slot for the section's own actions, a count, a toggle or a link. The title wraps by default; `truncate` clips it to one line with the full text as a tooltip. The heading id (`heading-id`, generated otherwise) lets the enclosing section name itself with `aria-labelledby`. */
export interface TySectionHeadingProps {
  /** Section name; the heading text, and the tooltip when `truncate` clips it. */
  title?: string
  /** Heading level (2, 3 or 4, as its attribute spelling); level 2 uses the h2 step, 3 and 4 the h3 step (§2.2). Default: `2`. */
  level?: "2" | "3" | "4"
  /** Supporting line under the title; plain meta text in reading order, not a heading. */
  subtitle?: string
  /** Clip the title to one line with an ellipsis; the full text stays accessible and becomes the tooltip. Wraps by default. */
  truncate?: boolean
  /** Id of the heading element, so the enclosing section can be a region labelled by it; `<instance>-heading` when unset. */
  headingId?: string
  /** A decorative leading icon (`aria-hidden`). */
  icon?: ReactNode
  /** Section actions, a count, a toggle or a link; follows the title in DOM order and wraps under it when it does not fit. */
  trailing?: ReactNode
  /** Extra content under the heading row. */
  children?: ReactNode
  id?: string
  className?: string
}

const DEFAULTS = { level: "2" } as const

export const TySectionHeading = forwardRef<HTMLElement, TySectionHeadingProps>(function TySectionHeading(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  const p = {
    title: props.title,
    level: props.level ?? DEFAULTS.level,
    subtitle: props.subtitle,
    truncate: props.truncate,
    headingId: props.headingId,
  }
  const slots: Record<string, boolean> = { "icon": filled(props.icon), "trailing": filled(props.trailing), "default": filled(props.children) }
  return createElement("ty-section-heading", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "title": text(p.title), "level": text(p.level), "subtitle": text(p.subtitle), "truncate": truthy(p.truncate) ? true : undefined, "heading-id": text(p.headingId) },
    createElement("div", { className: "ty-section-heading", "data-level": p.level },
      createElement("div", { className: "ty-section-heading__row" },
        (slots["icon"]) ? createElement("span", { className: "ty-section-heading__icon", "aria-hidden": "true" },
          props.icon,
        ) : null,
        createElement("div", { className: "ty-section-heading__text" },
          (p.level === "2") ? createElement("h2", { className: "ty-section-heading__title", id: (text(p.headingId) ?? `${instance}-heading`), "data-truncate": truthy(p.truncate) ? '' : undefined, title: (truthy(p.truncate)) ? (p.title) : undefined },
            text(p.title),
          ) : null,
          (p.level === "3") ? createElement("h3", { className: "ty-section-heading__title", id: (text(p.headingId) ?? `${instance}-heading`), "data-truncate": truthy(p.truncate) ? '' : undefined, title: (truthy(p.truncate)) ? (p.title) : undefined },
            text(p.title),
          ) : null,
          (p.level === "4") ? createElement("h4", { className: "ty-section-heading__title", id: (text(p.headingId) ?? `${instance}-heading`), "data-truncate": truthy(p.truncate) ? '' : undefined, title: (truthy(p.truncate)) ? (p.title) : undefined },
            text(p.title),
          ) : null,
          (truthy(p.subtitle)) ? createElement("p", { className: "ty-section-heading__subtitle" },
            text(p.subtitle),
          ) : null,
        ),
        (slots["trailing"]) ? createElement("div", { className: "ty-section-heading__trailing" },
          props.trailing,
        ) : null,
      ),
      (slots["default"]) ? createElement("div", { className: "ty-section-heading__extra" },
        props.children,
      ) : null,
    ))
})
