// Generated by tools/elements/generate.mjs from packages/ui/src/elements/skeleton/definition.ts. Do not edit.
import { createElement, forwardRef, useId, useImperativeHandle, useRef } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)

/** Content-shaped placeholder, hidden from assistive technology; with `label`, one polite status announces the loading and the region is marked busy. Presets (stats, cards, section-heading, filters, analysis) are composed by the element on upgrade. */
export interface TySkeletonProps {
  /** Block form: a text line, a heading line, a circle (avatar) or a rectangle (media, a chart). Default: `line`. */
  shape?: "line" | "heading" | "circle" | "rect"
  /** Named width (`short`, `medium`, `long`, `full`) or any CSS length; full width when unset. A custom length resolves on upgrade (`data-width="custom"` and an inline size). */
  width?: string
  /** Stacked text lines for the `line` and `heading` shapes, widths varied automatically (the last is short). Default: `1`. */
  lines?: number
  /** A composed skeleton instead of blocks; the element composes it on upgrade. */
  preset?: "stats" | "cards" | "section-heading" | "filters" | "analysis"
  /** Repetitions of the preset (tiles, pills, items); the preset's default when unset. */
  count?: number
  /** Grid columns of a tiled preset (1 to 4); the preset's default when unset. */
  columns?: number
  /** Announced once in a visually-hidden status while loading, the region marked `aria-busy` (the PageLoadingState pattern); unset, the skeleton is purely decorative and the host announces. */
  label?: string
  id?: string
  className?: string
}

const DEFAULTS = { shape: "line", lines: 1 } as const

export const TySkeleton = forwardRef<HTMLElement, TySkeletonProps>(function TySkeleton(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  const p = {
    shape: props.shape ?? DEFAULTS.shape,
    width: props.width,
    lines: props.lines ?? DEFAULTS.lines,
    preset: props.preset,
    count: props.count,
    columns: props.columns,
    label: props.label,
  }
  return createElement("ty-skeleton", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "shape": text(p.shape), "width": text(p.width), "lines": text(p.lines), "preset": text(p.preset), "count": text(p.count), "columns": text(p.columns), "label": text(p.label) },
    createElement("span", { className: "ty-skeleton-root", "aria-busy": truthy(p.label) ? 'true' : undefined },
      createElement("span", { className: "ty-skeleton-content", "aria-hidden": "true" },
        (!(truthy(p.preset))) && (p.shape === "line" || p.shape === "heading") ? createElement("span", { className: "ty-skeleton-lines" },
          createElement("span", { className: "ty-skeleton", "data-shape": p.shape, "data-width": p.width }),
        ) : null,
        (!(truthy(p.preset))) && (p.shape === "circle" || p.shape === "rect") ? createElement("span", { className: "ty-skeleton", "data-shape": p.shape, "data-width": p.width }) : null,
        (truthy(p.preset)) ? createElement("span", { className: "ty-skeleton-preset", "data-preset": p.preset }) : null,
      ),
      (truthy(p.label)) ? createElement("span", { className: "ty-visually-hidden", role: "status" },
        text(p.label),
      ) : null,
    ))
})
