// Generated by tools/elements/generate.mjs from packages/ui/src/elements/skip-link/definition.ts. Do not edit.
import { createElement, forwardRef, useId, useImperativeHandle, useRef, type ChangeEvent, type SyntheticEvent } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)

/** First focusable element of the page: jumps past the navigation straight to the main content (WCAG 2.4.1 Bypass Blocks). A native anchor to the target's fragment, visually hidden until focused — never `display: none`, so it stays in the accessibility tree. On activation the element moves focus to the target (a temporary negative tabindex when the target is not natively focusable) and scrolls it clear of the sticky top bar. */
export interface TySkipLinkProps {
  /** Id of the main content element; the anchor's href is its fragment (`#main-content`). Default: `main-content`. */
  targetId?: string
  /** Link text (the I18n adapter's default); translate through this attribute. Default: `Skip to main content`. */
  label?: string
  /** The native click of the anchor, before the focus move. */
  onClick?: (event: SyntheticEvent) => void
  id?: string
  className?: string
}

const DEFAULTS = { targetId: "main-content", label: "Skip to main content" } as const

export const TySkipLink = forwardRef<HTMLElement, TySkipLinkProps>(function TySkipLink(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  const p = {
    targetId: props.targetId ?? DEFAULTS.targetId,
    label: props.label ?? DEFAULTS.label,
  }
  return createElement("ty-skip-link", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "target-id": text(p.targetId), "label": text(p.label) },
    createElement("a", { className: "ty-skip-link", onClick: (event: ChangeEvent<HTMLAnchorElement>) => handlers.current.onClick?.(event) },
      text(p.label),
    ))
})
