// Generated by tools/elements/generate.mjs from packages/ui/src/elements/spinner/definition.ts. Do not edit.
import { createElement, forwardRef, useId, useImperativeHandle, useRef, type ReactNode } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)
const filled = (v: ReactNode) => v !== undefined && v !== null && v !== false && v !== ''

/** Indeterminate work indicator: an indeterminate progressbar named by `label`, drawn as a CSS ring or three pulsing dots (never announced). Under reduced motion the animation stops (the stylesheet) and the element reveals the label as text. */
export interface TySpinnerProps {
  /** Accessible name; the visible caption should say the same. Default: `Loading`. */
  label?: string
  /** Diameter step (`small` follows the text size). Default: `medium`. */
  size?: "small" | "medium" | "large"
  /** The drawing: a border-arc ring or three pulsing dots. Default: `ring`. */
  shape?: "ring" | "dots"
  /** Colour; `inherit` takes the current text colour. Default: `inherit`. */
  tone?: "inherit" | "accent" | "on-accent" | "neutral"
  /** The visible label next to the indicator (keep it the same text as `label`; it is decorative, the progressbar is named by `label`). */
  children?: ReactNode
  id?: string
  className?: string
}

const DEFAULTS = { label: "Loading", size: "medium", shape: "ring", tone: "inherit" } as const

export const TySpinner = forwardRef<HTMLElement, TySpinnerProps>(function TySpinner(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  const p = {
    label: props.label ?? DEFAULTS.label,
    size: props.size ?? DEFAULTS.size,
    shape: props.shape ?? DEFAULTS.shape,
    tone: props.tone ?? DEFAULTS.tone,
  }
  const slots: Record<string, boolean> = { "default": filled(props.children) }
  return createElement("ty-spinner", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "label": text(p.label), "size": text(p.size), "shape": text(p.shape), "tone": text(p.tone) },
    createElement("span", { className: "ty-spinner", role: "progressbar", "aria-label": p.label, "data-size": p.size, "data-shape": p.shape, "data-tone": p.tone },
      (p.shape === "ring") ? createElement("span", { className: "ty-spinner__ring", "aria-hidden": "true" }) : null,
      (p.shape === "dots") ? createElement("span", { className: "ty-spinner__dots", "aria-hidden": "true" },
        createElement("span", { className: "ty-spinner__dot" }),
        createElement("span", { className: "ty-spinner__dot" }),
        createElement("span", { className: "ty-spinner__dot" }),
      ) : null,
      (slots["default"]) ? createElement("span", { className: "ty-spinner__label", "aria-hidden": "true" },
        props.children,
      ) : null,
    ))
})
