// Generated by tools/elements/generate.mjs from packages/ui/src/elements/status-pill/definition.ts. Do not edit.
import { createElement, forwardRef, useId, useImperativeHandle, useRef, type ReactNode } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)
const filled = (v: ReactNode) => v !== undefined && v !== null && v !== false && v !== ''

/** Current state of an item as icon, word and semantic tone. Nothing interactive inside; a known `status` takes its tone and busy state from the element's status map unless `tone` overrides. */
export interface TyStatusPillProps {
  /** The status key (`data-status`); the built-in map colours the common ones (`pending`, `approved`, `processing`, …) while `tone` is absent. */
  status?: string
  /** The semantic tone (`data-tone`); left out, the status map decides (server renderings pass it themselves). */
  tone?: "neutral" | "info" | "success" | "warning" | "danger"
  /** Pill size. Default: `regular`. */
  size?: "small" | "regular"
  /** In-progress: the icon spins (static under reduced motion). */
  busy?: boolean
  /** Announce changes politely (`role="status"`); off by default, so tables of pills create no live regions. */
  announce?: boolean
  /** Plain-HTML label text; the default slot (what frameworks render) wins, then the status map's label, then the status key. */
  label?: string
  /** Accessible name of the pill (`aria-label`), e.g. "Status: Running" on an announced badge. */
  accessibleLabel?: string
  /** Test hook on the pill (`data-testid`). */
  testId?: string
  /** The status word. */
  children?: ReactNode
  /** The status icon (decorative); spins while busy. */
  icon?: ReactNode
  id?: string
  className?: string
}

const DEFAULTS = { size: "regular" } as const

export const TyStatusPill = forwardRef<HTMLElement, TyStatusPillProps>(function TyStatusPill(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  const p = {
    status: props.status,
    tone: props.tone,
    size: props.size ?? DEFAULTS.size,
    busy: props.busy,
    announce: props.announce,
    label: props.label,
    accessibleLabel: props.accessibleLabel,
    testId: props.testId,
  }
  const slots: Record<string, boolean> = { "default": filled(props.children), "icon": filled(props.icon) }
  return createElement("ty-status-pill", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "status": text(p.status), "tone": text(p.tone), "size": text(p.size), "busy": truthy(p.busy) ? true : undefined, "announce": truthy(p.announce) ? true : undefined, "label": text(p.label), "accessible-label": text(p.accessibleLabel), "test-id": text(p.testId) },
    createElement("span", { className: "ty-status", role: (truthy(p.announce)) ? ("status") : undefined, "aria-label": p.accessibleLabel, "data-tone": p.tone, "data-size": p.size, "data-busy": truthy(p.busy) ? '' : undefined, "data-status": p.status, "data-testid": p.testId },
      (slots["icon"]) ? createElement("span", { className: "ty-status__icon", "aria-hidden": "true" },
        props.icon,
      ) : null,
      createElement("span", { className: "ty-status__label" },
        props.children,
      ),
    ))
})
