// Generated by tools/elements/generate.mjs from packages/ui/src/elements/surface/definition.ts. Do not edit.
import { createElement, forwardRef, useId, useImperativeHandle, useRef, type ReactNode, type ChangeEvent, type SyntheticEvent } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)
const filled = (v: ReactNode) => v !== undefined && v !== null && v !== false && v !== ''

/** Bounded container at a chosen elevation. A titled surface is a region named by its title; a pressable one forwards presses anywhere on it to the single primary control in the title (a link with `href`, a button otherwise). */
export interface TySurfaceProps {
  /** Level 1 (sheet glass), 2 (raised card), 3 (floating) or 0 (flat). Default: `sheet`. */
  elevation?: "sheet" | "raised" | "floating" | "flat"
  /** Internal padding step. Default: `regular`. */
  padding?: "none" | "regular" | "roomy"
  /** Heading level of the title. Default: `h3`. */
  titleLevel?: "h2" | "h3" | "h4"
  /** The whole surface is one press target that forwards to the title's primary control; set it when `onclick` is wired. Implied by `href`. */
  pressable?: boolean
  /** Makes the surface a whole-card link: the title's primary control is an anchor and its hit area stretches over the card. */
  href?: string
  /** A chosen card (accent-soft state). */
  selected?: boolean
  /** Pressable surfaces only: inert primary control, no forwarding. */
  disabled?: boolean
  /** Accessible name of the region when there is no visible title. */
  accessibleLabel?: string
  /** The body. */
  children?: ReactNode
  /** The header title (a heading). Required on a pressable surface: it holds the primary control. */
  title?: ReactNode
  /** A secondary line under the title. */
  description?: ReactNode
  /** The footer region, usually actions. */
  footer?: ReactNode
  /** A press of the primary control (directly, or forwarded from anywhere on the surface). */
  onClick?: (event: SyntheticEvent) => void
  id?: string
  className?: string
}

const DEFAULTS = { elevation: "sheet", padding: "regular", titleLevel: "h3" } as const

export const TySurface = forwardRef<HTMLElement, TySurfaceProps>(function TySurface(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  const p = {
    elevation: props.elevation ?? DEFAULTS.elevation,
    padding: props.padding ?? DEFAULTS.padding,
    titleLevel: props.titleLevel ?? DEFAULTS.titleLevel,
    pressable: props.pressable,
    href: props.href,
    selected: props.selected,
    disabled: props.disabled,
    accessibleLabel: props.accessibleLabel,
  }
  const slots: Record<string, boolean> = { "default": filled(props.children), "title": filled(props.title), "description": filled(props.description), "footer": filled(props.footer) }
  return createElement("ty-surface", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "elevation": text(p.elevation), "padding": text(p.padding), "title-level": text(p.titleLevel), "pressable": truthy(p.pressable) ? true : undefined, "href": text(p.href), "selected": truthy(p.selected) ? true : undefined, "disabled": truthy(p.disabled) ? true : undefined, "accessible-label": text(p.accessibleLabel) },
    createElement("section", { className: "ty-surface", "aria-labelledby": (slots["title"]) ? (`${instance}-title`) : undefined, "aria-label": (!(slots["title"])) ? (p.accessibleLabel) : undefined, "data-elevation": p.elevation, "data-padding": p.padding, "data-pressable": (truthy(p.pressable) || truthy(p.href)) ? ("") : undefined, "data-selected": truthy(p.selected) ? '' : undefined, "data-disabled": (truthy(p.pressable) || truthy(p.href)) && (truthy(p.disabled)) ? ("") : undefined },
      (slots["title"] || slots["description"]) ? createElement("header", { className: "ty-surface__header" },
        (slots["title"]) && (p.titleLevel === "h2") ? createElement("h2", { className: "ty-surface__title", id: `${instance}-title` },
          (truthy(p.href)) ? createElement("a", { className: "ty-surface__primary", href: (!(truthy(p.disabled))) ? (p.href) : undefined, "aria-disabled": truthy(p.disabled) ? 'true' : undefined, onClick: (event: ChangeEvent<HTMLAnchorElement>) => handlers.current.onClick?.(event) },
            props.title,
          ) : null,
          (!(truthy(p.href))) && (truthy(p.pressable)) ? createElement("button", { className: "ty-surface__primary", type: "button", disabled: truthy(p.disabled) || undefined, onClick: (event: ChangeEvent<HTMLButtonElement>) => handlers.current.onClick?.(event) },
            props.title,
          ) : null,
          ((!(truthy(p.href))) && (!(truthy(p.pressable)))) ? props.title : null,
        ) : null,
        (slots["title"]) && (p.titleLevel === "h3") ? createElement("h3", { className: "ty-surface__title", id: `${instance}-title` },
          (truthy(p.href)) ? createElement("a", { className: "ty-surface__primary", href: (!(truthy(p.disabled))) ? (p.href) : undefined, "aria-disabled": truthy(p.disabled) ? 'true' : undefined, onClick: (event: ChangeEvent<HTMLAnchorElement>) => handlers.current.onClick?.(event) },
            props.title,
          ) : null,
          (!(truthy(p.href))) && (truthy(p.pressable)) ? createElement("button", { className: "ty-surface__primary", type: "button", disabled: truthy(p.disabled) || undefined, onClick: (event: ChangeEvent<HTMLButtonElement>) => handlers.current.onClick?.(event) },
            props.title,
          ) : null,
          ((!(truthy(p.href))) && (!(truthy(p.pressable)))) ? props.title : null,
        ) : null,
        (slots["title"]) && (p.titleLevel === "h4") ? createElement("h4", { className: "ty-surface__title", id: `${instance}-title` },
          (truthy(p.href)) ? createElement("a", { className: "ty-surface__primary", href: (!(truthy(p.disabled))) ? (p.href) : undefined, "aria-disabled": truthy(p.disabled) ? 'true' : undefined, onClick: (event: ChangeEvent<HTMLAnchorElement>) => handlers.current.onClick?.(event) },
            props.title,
          ) : null,
          (!(truthy(p.href))) && (truthy(p.pressable)) ? createElement("button", { className: "ty-surface__primary", type: "button", disabled: truthy(p.disabled) || undefined, onClick: (event: ChangeEvent<HTMLButtonElement>) => handlers.current.onClick?.(event) },
            props.title,
          ) : null,
          ((!(truthy(p.href))) && (!(truthy(p.pressable)))) ? props.title : null,
        ) : null,
        (slots["description"]) ? createElement("div", { className: "ty-surface__description" },
          props.description,
        ) : null,
      ) : null,
      (slots["default"]) ? createElement("div", { className: "ty-surface__body" },
        props.children,
      ) : null,
      (slots["footer"]) ? createElement("footer", { className: "ty-surface__footer" },
        props.footer,
      ) : null,
    ))
})
