// Generated by tools/elements/generate.mjs from packages/ui/src/elements/switch/definition.ts. Do not edit.
import { createElement, forwardRef, useId, useImperativeHandle, useRef, type ReactNode, type SyntheticEvent } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)
const filled = (v: ReactNode) => v !== undefined && v !== null && v !== false && v !== ''

/** On/off setting with immediate effect. A native checkbox with role="switch" inside a <label>, so labelling, keyboard and form participation are the platform's; Enter toggles as well as Space. */
export interface TySwitchProps {
  /** On. */
  checked?: boolean
  /** Native disabled. */
  disabled?: boolean
  /** Shown but not changeable (`aria-readonly`). */
  readOnly?: boolean
  /** Form field name; the value is sent while on. */
  name?: string
  /** Form value sent while on (the browser sends "on" without one). */
  value?: string
  /** Track size. Default: `regular`. */
  size?: "small" | "regular" | "large"
  /** `tile`: text at the start, control at the end, the whole row is the target. Default: `inline`. */
  layout?: "inline" | "tile"
  /** Accessible name when there is no visible label. */
  accessibleLabel?: string
  /** The visible label. */
  children?: ReactNode
  /** A secondary line, announced as the description. */
  description?: ReactNode
  /** The native change of the checkbox; `checked` is the new state. */
  onChange?: (detail: { checked: boolean }, event: SyntheticEvent) => void
  id?: string
  className?: string
}

const DEFAULTS = { size: "regular", layout: "inline" } as const

export const TySwitch = forwardRef<HTMLElement, TySwitchProps>(function TySwitch(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  const p: Record<string, unknown> = { ...DEFAULTS }
  for (const [key, value] of Object.entries(props)) if (value !== undefined) p[key] = value
  const slots: Record<string, boolean> = { "default": filled(props.children), "description": filled(props.description) }
  return createElement("ty-switch", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "checked": truthy(p.checked) ? true : undefined, "disabled": truthy(p.disabled) ? true : undefined, "read-only": truthy(p.readOnly) ? true : undefined, "name": text(p.name), "value": text(p.value), "size": text(p.size), "layout": text(p.layout), "accessible-label": text(p.accessibleLabel) },
    createElement("label", { className: "ty-switch", "data-layout": text(p.layout), "data-size": text(p.size), "data-selected": truthy(p.checked) ? '' : undefined, "data-disabled": truthy(p.disabled) ? '' : undefined, "data-readonly": truthy(p.readOnly) ? '' : undefined },
      createElement("input", { className: "ty-visually-hidden", type: "checkbox", role: "switch", name: text(p.name), value: text(p.value), checked: Boolean(p.checked), disabled: truthy(p.disabled) || undefined, "aria-readonly": truthy(p.readOnly) ? 'true' : undefined, "aria-label": (!slots["default"]) ? (text(p.accessibleLabel)) : undefined, "aria-labelledby": (slots["default"]) ? (`${instance}-label`) : undefined, "aria-describedby": (slots["description"]) ? (`${instance}-description`) : undefined, onChange: (event) => handlers.current.onChange?.({ checked: event.currentTarget.checked }, event) }),
      createElement("span", { className: "ty-switch__track", "aria-hidden": "true" },
        createElement("span", { className: "ty-switch__thumb" }),
      ),
      (slots["default"] || slots["description"]) ? createElement("span", { className: "ty-switch__text" },
        (slots["default"]) ? createElement("span", { className: "ty-switch__label", id: `${instance}-label` },
          props.children,
        ) : null,
        (slots["description"]) ? createElement("span", { className: "ty-switch__description", id: `${instance}-description` },
          props.description,
        ) : null,
      ) : null,
    ))
})
