// Generated by tools/elements/generate.mjs from packages/ui/src/elements/tabs/definition.ts. Do not edit.
import { createElement, forwardRef, useEffect, useId, useImperativeHandle, useRef, type ReactNode } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)

/** Sibling views of one object, one panel at a time (the APG tabs pattern). The tab list is one tab stop: the arrow keys move along the `orientation` axis, wrapping and skipping disabled tabs, Home and End jump, and Left/Right follow the reading direction. `activation` decides whether moving focus also selects. Selection is controlled with `selected-key` or uncontrolled from `default-selected-key` (the first enabled tab when neither is set); a different selection is reported with `ty-selection-change`. */
export interface TyTabsProps {
  /** Controlled selection: the selected tab's id. The element asks for a change with `ty-selection-change`; the host flips the attribute. */
  selectedKey?: string
  /** Initial selection of an uncontrolled list; the first enabled tab when unset. */
  defaultSelectedKey?: string
  /** Layout of the list and the arrow-key axis: Left/Right (following the reading direction), or Up/Down when vertical. Default: `horizontal`. */
  orientation?: "horizontal" | "vertical"
  /** Automatic selects on focus; manual needs Enter or Space on the focused tab. Default: `automatic`. */
  activation?: "automatic" | "manual"
  /** Accessible name of the tab list (required). */
  label?: string
  /** JSON array of the tabs: [{ "id", "label", "count"?, "disabled"? }]. The count follows the label and joins the accessible name; a disabled tab cannot be selected and the arrow keys skip it. (The React component's decorative icon has no attribute form.) */
  tabs?: string
  /** Keep inactive panels in the DOM (hidden) to preserve their state. The element always keeps them — their nodes belong to the host — so the attribute only tells a wrapper it may unmount. */
  keepMounted?: boolean
  /** The panels: one element per tab, keyed by `data-panel` (the tab's id). The element wires the role, id, `aria-labelledby` and visibility; only the selected panel shows. */
  children?: ReactNode
  /** A different tab was selected (a click, or the keyboard per `activation`). Uncontrolled, the element has already applied it; controlled (`selected-key`), the host flips the attribute. */
  onSelectionChange?: (detail: { key: string }) => void
  id?: string
  className?: string
}

const DEFAULTS = { orientation: "horizontal", activation: "automatic" } as const

export const TyTabs = forwardRef<HTMLElement, TyTabsProps>(function TyTabs(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  useEffect(() => {
    const element = host.current
    if (!element) return
    const listeners: Array<[string, EventListener]> = [
      ["ty-selection-change", (event) => handlers.current.onSelectionChange?.((event as CustomEvent).detail)],
    ]
    for (const [type, listener] of listeners) element.addEventListener(type, listener)
    return () => { for (const [type, listener] of listeners) element.removeEventListener(type, listener) }
  }, [])
  const p = {
    selectedKey: props.selectedKey,
    defaultSelectedKey: props.defaultSelectedKey,
    orientation: props.orientation ?? DEFAULTS.orientation,
    activation: props.activation ?? DEFAULTS.activation,
    label: props.label,
    tabs: props.tabs,
    keepMounted: props.keepMounted,
  }
  return createElement("ty-tabs", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "selected-key": text(p.selectedKey), "default-selected-key": text(p.defaultSelectedKey), "orientation": text(p.orientation), "activation": text(p.activation), "label": text(p.label), "tabs": text(p.tabs), "keep-mounted": truthy(p.keepMounted) ? true : undefined },
    createElement("div", { className: "ty-tabs", "data-orientation": p.orientation },
      createElement("div", { className: "ty-tabs__list", role: "tablist", "aria-label": p.label, "aria-orientation": p.orientation, "data-orientation": p.orientation }),
      props.children,
    ))
})
