// Generated by tools/elements/generate.mjs from packages/ui/src/elements/tag-field/definition.ts. Do not edit.
import { createElement, forwardRef, useEffect, useId, useImperativeHandle, useRef } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)

/** Short values typed into removable pills, optionally assisted by (or restricted to) a suggestion list. Enter or comma commits the draft (or the highlighted suggestion), Backspace on an empty entry removes the last pill; duplicates (case-insensitive), values past `max` and — with `allow-free-text="false"` — values outside `suggestions` are refused. With suggestions the entry is an APG combobox with list autocomplete (active descendant, wrap-around arrows). */
export interface TyTagFieldProps {
  /** JSON array of the committed values (controlled); the element asks for changes with `ty-change`, it never writes its own. */
  value?: string
  /** JSON array of known values; turns the entry into a combobox. */
  suggestions?: string
  /** JSON object of display text per value, used in the popup and on the pills. */
  suggestionLabels?: string
  /** `true` or `false`; unset: free text is allowed. `false`: only values present in `suggestions` are accepted (the `show-arrow` precedent for a default-true switch). */
  allowFreeText?: string
  /** Maximum pills; the entry is disabled at the limit and re-enabled when one is removed. */
  max?: number
  /** Disables the entry and every remove control. */
  disabled?: boolean
  /** Pill tint; `accent` fills with the theme accent. Default: `neutral`. */
  tone?: "neutral" | "accent"
  /** A categorical token (1 to 8) as the pill tint, shown as a small colour square; normalised into range on upgrade, wins over `tone`. */
  categoryIndex?: number
  /** Visible label above the field, targeting the entry; if absent, `accessibleLabel` is required. */
  label?: string
  /** Accessible name of the entry when there is no visible label. */
  accessibleLabel?: string
  /** Hint in the entry. */
  placeholder?: string
  /** Help text below the field, linked as the entry's description. */
  helperText?: string
  /** Marks the field invalid; shown below the helper text and linked as description. */
  errorText?: string
  /** Accessible name template of each remove control; `{value}` is the pill's display text. Default: `Remove {value}`. */
  removeLabel?: string
  /** Accessible name template of the pill list; `{field}` is the label (or accessible label). Default: `{field}: chosen values`. */
  chosenLabel?: string
  /** Accessible name of the suggestion popup. Default: `Suggestions`. */
  suggestionsLabel?: string
  /** Test hook on the root (`data-testid`). */
  testId?: string
  /** A value was added or removed; `value` is the next list as a JSON array. Controlled: the host writes it back to the `value` attribute. */
  onChange?: (detail: { value: string }) => void
  id?: string
  className?: string
}

const DEFAULTS = { tone: "neutral", removeLabel: "Remove {value}", chosenLabel: "{field}: chosen values", suggestionsLabel: "Suggestions" } as const

export const TyTagField = forwardRef<HTMLElement, TyTagFieldProps>(function TyTagField(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  useEffect(() => {
    const element = host.current
    if (!element) return
    const listeners: Array<[string, EventListener]> = [
      ["ty-change", (event) => handlers.current.onChange?.((event as CustomEvent).detail)],
    ]
    for (const [type, listener] of listeners) element.addEventListener(type, listener)
    return () => { for (const [type, listener] of listeners) element.removeEventListener(type, listener) }
  }, [])
  const p = {
    value: props.value,
    suggestions: props.suggestions,
    suggestionLabels: props.suggestionLabels,
    allowFreeText: props.allowFreeText,
    max: props.max,
    disabled: props.disabled,
    tone: props.tone ?? DEFAULTS.tone,
    categoryIndex: props.categoryIndex,
    label: props.label,
    accessibleLabel: props.accessibleLabel,
    placeholder: props.placeholder,
    helperText: props.helperText,
    errorText: props.errorText,
    removeLabel: props.removeLabel ?? DEFAULTS.removeLabel,
    chosenLabel: props.chosenLabel ?? DEFAULTS.chosenLabel,
    suggestionsLabel: props.suggestionsLabel ?? DEFAULTS.suggestionsLabel,
    testId: props.testId,
  }
  return createElement("ty-tag-field", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "value": text(p.value), "suggestions": text(p.suggestions), "suggestion-labels": text(p.suggestionLabels), "allow-free-text": text(p.allowFreeText), "max": text(p.max), "disabled": truthy(p.disabled) ? true : undefined, "tone": text(p.tone), "category-index": text(p.categoryIndex), "label": text(p.label), "accessible-label": text(p.accessibleLabel), "placeholder": text(p.placeholder), "helper-text": text(p.helperText), "error-text": text(p.errorText), "remove-label": text(p.removeLabel), "chosen-label": text(p.chosenLabel), "suggestions-label": text(p.suggestionsLabel), "test-id": text(p.testId) })
})
