// Generated by tools/elements/generate.mjs from packages/ui/src/elements/tag/definition.ts. Do not edit.
import { createElement, forwardRef, useId, useImperativeHandle, useRef, type ReactNode, type ChangeEvent, type SyntheticEvent } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)
const filled = (v: ReactNode) => v !== undefined && v !== null && v !== false && v !== ''

/** Small label for static metadata (a badge or chip), optionally removable; the remove button is a native <button>. An interactive tag (pressable or a link) is a plain styled native — <button class="ty-tag" data-interactive> or <a class="ty-tag" href> — not this element (see docs/html-contract.md). */
export interface TyTagProps {
  /** `accent` fills with the theme accent. Default: `neutral`. */
  tone?: "neutral" | "accent"
  /** A categorical token (1 to 8) shown as a small colour square; normalised into range on upgrade. */
  categoryIndex?: number
  /** Text step; `small` never goes below the meta size. Default: `regular`. */
  size?: "small" | "regular" | "large"
  /** Shows the remove button at the end. */
  removable?: boolean
  /** Accessible name of the remove button; must include the tag text (defaults to "Remove <text>" on upgrade). */
  removeLabel?: string
  /** A polite live region (`role="status"`) for a tag whose text updates dynamically. */
  live?: boolean
  /** Test hook on the tag (`data-testid`). */
  testId?: string
  /** The text; truncates with an ellipsis. */
  children?: ReactNode
  /** A leading icon (decorative); wins over the category square. */
  icon?: ReactNode
  /** The remove button's native click (wired on that button). */
  onClick?: (event: SyntheticEvent) => void
  id?: string
  className?: string
}

const DEFAULTS = { tone: "neutral", size: "regular" } as const

export const TyTag = forwardRef<HTMLElement, TyTagProps>(function TyTag(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  const p = {
    tone: props.tone ?? DEFAULTS.tone,
    categoryIndex: props.categoryIndex,
    size: props.size ?? DEFAULTS.size,
    removable: props.removable,
    removeLabel: props.removeLabel,
    live: props.live,
    testId: props.testId,
  }
  const slots: Record<string, boolean> = { "default": filled(props.children), "icon": filled(props.icon) }
  return createElement("ty-tag", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "tone": text(p.tone), "category-index": text(p.categoryIndex), "size": text(p.size), "removable": truthy(p.removable) ? true : undefined, "remove-label": text(p.removeLabel), "live": truthy(p.live) ? true : undefined, "test-id": text(p.testId) },
    createElement("span", { className: "ty-tag", role: (truthy(p.live)) ? ("status") : undefined, "aria-live": (truthy(p.live)) ? ("polite") : undefined, "data-tone": p.tone, "data-size": p.size, "data-removable": truthy(p.removable) ? '' : undefined, "data-testid": p.testId },
      (slots["icon"]) ? createElement("span", { className: "ty-tag__icon", "aria-hidden": "true" },
        props.icon,
      ) : null,
      (!(slots["icon"])) && (truthy(p.categoryIndex)) ? createElement("span", { className: "ty-tag__swatch", "aria-hidden": "true", "data-category": p.categoryIndex }) : null,
      createElement("span", { className: "ty-tag__text" },
        props.children,
      ),
      (truthy(p.removable)) ? createElement("button", { className: "ty-tag__remove", type: "button", "aria-label": p.removeLabel, onClick: (event: ChangeEvent<HTMLButtonElement>) => handlers.current.onClick?.(event) },
        createElement("svg", { className: "ty-icon", "aria-hidden": "true", focusable: "false", viewBox: "0 0 12 12", fill: "none", stroke: "currentColor", strokeWidth: "1.5", strokeLinecap: "round" },
          createElement("path", { d: "M2.5 2.5l7 7M9.5 2.5l-7 7" }),
        ),
      ) : null,
    ))
})
