// Generated by tools/elements/generate.mjs from packages/ui/src/elements/text-area/definition.ts. Do not edit.
import { createElement, forwardRef, useId, useImperativeHandle, useRef, type ReactNode, type ChangeEvent, type SyntheticEvent } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)
const filled = (v: ReactNode) => v !== undefined && v !== null && v !== false && v !== ''

/** Multi-line text entry. A native <textarea> inside, so input, keyboard and form participation are the platform's; the element adds the character counter, the over-limit state and auto-grow. */
export interface TyTextAreaProps {
  /** Controlled text; the element mirrors it into the textarea (while the user types, the live value is the textarea's own). */
  value?: string
  /** Initial text of an uncontrolled area, applied once on connect; a form reset returns to it. */
  defaultValue?: string
  /** Initial visible lines. Default: `3`. */
  rows?: number
  /** Grows with the content up to `maxRows`, then scrolls. */
  autoGrow?: boolean
  /** Growth limit of `autoGrow`; past it the area scrolls (`data-scrolling`). */
  maxRows?: number
  /** The native resize handle; `autoGrow` always disables it. Default: `vertical`. */
  resize?: "vertical" | "none"
  /** Counted for the counter and the over-limit state; typing is not cut off. */
  maxLength?: number
  /** A character counter under the area (needs `maxLength`). */
  showCounter?: boolean
  /** Counter template; `{count}` and `{max}` are filled in. Default: `{count} of {max} characters`. */
  counterLabel?: string
  /** Counter template past the limit; `{over}` is the excess. Default: `{count} of {max} characters, {over} over the limit`. */
  overLimitLabel?: string
  /** Mono family for code, keys or JSON. */
  monospace?: boolean
  /** Native required. */
  required?: boolean
  /** Native disabled. */
  disabled?: boolean
  /** Shown but not changeable. */
  readOnly?: boolean
  /** Painted and announced as invalid without an error message (a surrounding field marks it). */
  invalid?: boolean
  /** Form field name. */
  name?: string
  /** Native placeholder. */
  placeholder?: string
  /** Accessible name when there is no visible label. */
  accessibleLabel?: string
  /** `aria-labelledby` from a surrounding field (used when there is no visible label and no `accessibleLabel`). */
  labelledBy?: string
  /** `aria-describedby` from a surrounding field, joined before the area's own parts. */
  describedBy?: string
  /** Explicit id of the control (a surrounding field's control id); `<instance>-input` otherwise. */
  controlId?: string
  /** Test hook on the root (`data-testid`). */
  testId?: string
  /** The visible label, targeting the area. */
  label?: ReactNode
  /** Help text under the area, announced as the description. */
  hint?: ReactNode
  /** The error message; marks the area invalid and is announced. */
  error?: ReactNode
  /** The native input of the textarea; `value` is the whole text. */
  onChange?: (detail: { value: string }, event: SyntheticEvent) => void
  id?: string
  className?: string
}

const DEFAULTS = { rows: 3, resize: "vertical", counterLabel: "{count} of {max} characters", overLimitLabel: "{count} of {max} characters, {over} over the limit" } as const

export const TyTextArea = forwardRef<HTMLElement, TyTextAreaProps>(function TyTextArea(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  const p = {
    value: props.value,
    defaultValue: props.defaultValue,
    rows: props.rows ?? DEFAULTS.rows,
    autoGrow: props.autoGrow,
    maxRows: props.maxRows,
    resize: props.resize ?? DEFAULTS.resize,
    maxLength: props.maxLength,
    showCounter: props.showCounter,
    counterLabel: props.counterLabel ?? DEFAULTS.counterLabel,
    overLimitLabel: props.overLimitLabel ?? DEFAULTS.overLimitLabel,
    monospace: props.monospace,
    required: props.required,
    disabled: props.disabled,
    readOnly: props.readOnly,
    invalid: props.invalid,
    name: props.name,
    placeholder: props.placeholder,
    accessibleLabel: props.accessibleLabel,
    labelledBy: props.labelledBy,
    describedBy: props.describedBy,
    controlId: props.controlId,
    testId: props.testId,
  }
  const slots: Record<string, boolean> = { "label": filled(props.label), "hint": filled(props.hint), "error": filled(props.error) }
  return createElement("ty-text-area", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "value": text(p.value), "default-value": text(p.defaultValue), "rows": text(p.rows), "auto-grow": truthy(p.autoGrow) ? true : undefined, "max-rows": text(p.maxRows), "resize": text(p.resize), "max-length": text(p.maxLength), "show-counter": truthy(p.showCounter) ? true : undefined, "counter-label": text(p.counterLabel), "over-limit-label": text(p.overLimitLabel), "monospace": truthy(p.monospace) ? true : undefined, "required": truthy(p.required) ? true : undefined, "disabled": truthy(p.disabled) ? true : undefined, "read-only": truthy(p.readOnly) ? true : undefined, "invalid": truthy(p.invalid) ? true : undefined, "name": text(p.name), "placeholder": text(p.placeholder), "accessible-label": text(p.accessibleLabel), "labelled-by": text(p.labelledBy), "described-by": text(p.describedBy), "control-id": text(p.controlId), "test-id": text(p.testId) },
    createElement("div", { className: "ty-text-area", "data-resize": p.resize, "data-monospace": truthy(p.monospace) ? '' : undefined, "data-auto-grow": truthy(p.autoGrow) ? '' : undefined, "data-invalid": (truthy(p.invalid) || slots["error"]) ? ("") : undefined, "data-readonly": truthy(p.readOnly) ? '' : undefined, "data-disabled": truthy(p.disabled) ? '' : undefined, "data-testid": p.testId },
      (slots["label"]) ? createElement("label", { className: "ty-text-area__label", htmlFor: (text(p.controlId) ?? `${instance}-input`) },
        props.label,
      ) : null,
      (slots["hint"]) ? createElement("p", { className: "ty-text-area__hint", id: `${instance}-hint` },
        props.hint,
      ) : null,
      createElement("textarea", { className: "ty-text-area__input", id: (text(p.controlId) ?? `${instance}-input`), rows: p.rows, name: p.name, placeholder: p.placeholder, disabled: truthy(p.disabled) || undefined, readOnly: truthy(p.readOnly) || undefined, required: truthy(p.required) || undefined, "aria-label": (!(slots["label"])) ? (p.accessibleLabel) : undefined, "aria-labelledby": (!(slots["label"])) && (!(truthy(p.accessibleLabel))) ? (p.labelledBy) : undefined, "aria-describedby": [text(p.describedBy) ?? '', (((slots["hint"])) ? `${instance}-hint` : ''), (((slots["error"])) ? `${instance}-error` : ''), (((truthy(p.showCounter)) && (truthy(p.maxLength))) ? `${instance}-counter` : '')].filter(Boolean).join(' ') || undefined, "aria-invalid": (truthy(p.invalid) || slots["error"]) ? ("true") : undefined, onChange: (event: ChangeEvent<HTMLTextAreaElement>) => handlers.current.onChange?.({ value: event.currentTarget.value }, event) }),
      (slots["error"]) ? createElement("p", { className: "ty-text-area__error", id: `${instance}-error` },
        createElement("svg", { className: "ty-icon", "aria-hidden": "true", focusable: "false", width: "24", height: "24", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round" },
          createElement("circle", { cx: "12", cy: "12", r: "10" }),
          createElement("line", { x1: "12", y1: "8", x2: "12", y2: "12" }),
          createElement("line", { x1: "12", y1: "16", x2: "12.01", y2: "16" }),
        ),
        createElement("span", {  },
          props.error,
        ),
      ) : null,
      (truthy(p.showCounter)) && (truthy(p.maxLength)) ? createElement("p", { className: "ty-text-area__counter", id: `${instance}-counter` }) : null,
    ))
})
