// Generated by tools/elements/generate.mjs from packages/ui/src/elements/text-field/definition.ts. Do not edit.
import { createElement, forwardRef, useEffect, useId, useImperativeHandle, useRef, type ReactNode, type ChangeEvent, type SyntheticEvent } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)
const filled = (v: ReactNode) => v !== undefined && v !== null && v !== false && v !== ''

/** Single-line text entry: plain, search and password. A native <input> inside, so typing, keyboard, autofill and form participation are the platform's; the element adds the clear action (search mode, or `clearable`), the reveal action (password mode), the character counter and the over-limit state. */
export interface TyTextFieldProps {
  /** `search` adds the magnifier and the clear action (Escape clears); `password` adds the reveal action. Default: `text`. */
  mode?: "text" | "search" | "password"
  /** Native type for `mode="text"` (`text` when unset); `mode` wins when both are set. */
  inputType?: "text" | "email" | "url" | "tel" | "number"
  /** Controlled text; the element mirrors it into the input (while the user types, the live value is the input's own). */
  value?: string
  /** Initial text of an uncontrolled field, applied once on connect; a form reset returns to it. */
  defaultValue?: string
  /** Surface treatment of the group. Default: `outlined`. */
  appearance?: "outlined" | "filled"
  /** The clear action outside search mode (search always has it); shown while the field is non-empty and editable. */
  clearable?: boolean
  /** Accessible name of the clear action. Default: `Clear`. */
  clearLabel?: string
  /** Accessible name of the reveal action while the password is hidden. Default: `Show password`. */
  showPasswordLabel?: string
  /** Accessible name of the reveal action while the password is shown. Default: `Hide password`. */
  hidePasswordLabel?: string
  /** Counted for the counter and the over-limit state; typing is not cut off. */
  maxLength?: number
  /** A character counter under the field (needs `maxLength`). */
  showCounter?: boolean
  /** Counter template; `{count}` and `{max}` are filled in. Default: `{count} of {max} characters`. */
  counterLabel?: string
  /** Counter template past the limit; `{over}` is the excess. Default: `{count} of {max} characters, {over} over the limit`. */
  overLimitLabel?: string
  /** Native required. */
  required?: boolean
  /** Native disabled. */
  disabled?: boolean
  /** Shown but not changeable. */
  readOnly?: boolean
  /** Painted and announced as invalid without an error message (a surrounding field marks it). */
  invalid?: boolean
  /** Form field name. */
  name?: string
  /** Native placeholder. */
  placeholder?: string
  /** Native autocomplete hint. */
  autoComplete?: string
  /** Accessible name when there is no visible label. */
  accessibleLabel?: string
  /** `aria-labelledby` from a surrounding field (used when there is no visible label and no `accessibleLabel`). */
  labelledBy?: string
  /** `aria-describedby` from a surrounding field, joined before the field's own parts. */
  describedBy?: string
  /** Explicit id of the control (a surrounding field's control id); `<instance>-input` otherwise. */
  controlId?: string
  /** Test hook on the root (`data-testid`). */
  testId?: string
  /** The visible label, targeting the input. */
  label?: ReactNode
  /** Help text above the group, announced as the description. */
  hint?: ReactNode
  /** The error message; marks the field invalid and is announced. */
  error?: ReactNode
  /** Confirmation of a valid value; only without an error, and hidden while over the limit. */
  success?: ReactNode
  /** A decorative leading icon; wins over the search magnifier. */
  leading?: ReactNode
  /** The native input of the field; `value` is the whole text. */
  onChange?: (detail: { value: string }, event: SyntheticEvent) => void
  /** The clear action ran (its button, or Escape in search mode); the value is already empty and focus is back on the input. */
  onClear?: () => void
  id?: string
  className?: string
}

const DEFAULTS = { mode: "text", appearance: "outlined", clearLabel: "Clear", showPasswordLabel: "Show password", hidePasswordLabel: "Hide password", counterLabel: "{count} of {max} characters", overLimitLabel: "{count} of {max} characters, {over} over the limit" } as const

export const TyTextField = forwardRef<HTMLElement, TyTextFieldProps>(function TyTextField(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  useEffect(() => {
    const element = host.current
    if (!element) return
    const listeners: Array<[string, EventListener]> = [
      ["ty-clear", () => handlers.current.onClear?.()],
    ]
    for (const [type, listener] of listeners) element.addEventListener(type, listener)
    return () => { for (const [type, listener] of listeners) element.removeEventListener(type, listener) }
  }, [])
  const p = {
    mode: props.mode ?? DEFAULTS.mode,
    inputType: props.inputType,
    value: props.value,
    defaultValue: props.defaultValue,
    appearance: props.appearance ?? DEFAULTS.appearance,
    clearable: props.clearable,
    clearLabel: props.clearLabel ?? DEFAULTS.clearLabel,
    showPasswordLabel: props.showPasswordLabel ?? DEFAULTS.showPasswordLabel,
    hidePasswordLabel: props.hidePasswordLabel ?? DEFAULTS.hidePasswordLabel,
    maxLength: props.maxLength,
    showCounter: props.showCounter,
    counterLabel: props.counterLabel ?? DEFAULTS.counterLabel,
    overLimitLabel: props.overLimitLabel ?? DEFAULTS.overLimitLabel,
    required: props.required,
    disabled: props.disabled,
    readOnly: props.readOnly,
    invalid: props.invalid,
    name: props.name,
    placeholder: props.placeholder,
    autoComplete: props.autoComplete,
    accessibleLabel: props.accessibleLabel,
    labelledBy: props.labelledBy,
    describedBy: props.describedBy,
    controlId: props.controlId,
    testId: props.testId,
  }
  const slots: Record<string, boolean> = { "label": filled(props.label), "hint": filled(props.hint), "error": filled(props.error), "success": filled(props.success), "leading": filled(props.leading) }
  return createElement("ty-text-field", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "mode": text(p.mode), "input-type": text(p.inputType), "value": text(p.value), "default-value": text(p.defaultValue), "appearance": text(p.appearance), "clearable": truthy(p.clearable) ? true : undefined, "clear-label": text(p.clearLabel), "show-password-label": text(p.showPasswordLabel), "hide-password-label": text(p.hidePasswordLabel), "max-length": text(p.maxLength), "show-counter": truthy(p.showCounter) ? true : undefined, "counter-label": text(p.counterLabel), "over-limit-label": text(p.overLimitLabel), "required": truthy(p.required) ? true : undefined, "disabled": truthy(p.disabled) ? true : undefined, "read-only": truthy(p.readOnly) ? true : undefined, "invalid": truthy(p.invalid) ? true : undefined, "name": text(p.name), "placeholder": text(p.placeholder), "autocomplete": text(p.autoComplete), "accessible-label": text(p.accessibleLabel), "labelled-by": text(p.labelledBy), "described-by": text(p.describedBy), "control-id": text(p.controlId), "test-id": text(p.testId) },
    createElement("div", { className: "ty-text-field", "data-appearance": p.appearance, "data-mode": p.mode, "data-invalid": (truthy(p.invalid) || slots["error"]) ? ("") : undefined, "data-readonly": truthy(p.readOnly) ? '' : undefined, "data-disabled": truthy(p.disabled) ? '' : undefined, "data-testid": p.testId },
      (slots["label"]) ? createElement("label", { className: "ty-text-field__label", htmlFor: (text(p.controlId) ?? `${instance}-input`) },
        props.label,
      ) : null,
      (slots["hint"]) ? createElement("p", { className: "ty-text-field__hint", id: `${instance}-hint` },
        props.hint,
      ) : null,
      createElement("div", { className: "ty-text-field__group" },
        (slots["leading"]) ? createElement("span", { className: "ty-text-field__leading", "aria-hidden": "true" },
          props.leading,
        ) : null,
        (p.mode === "search") && (!(slots["leading"])) ? createElement("span", { className: "ty-text-field__leading", "aria-hidden": "true" },
          createElement("svg", { className: "ty-icon", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": "true", focusable: "false" },
            createElement("circle", { className: "ty-text-field__glyph", cx: "11", cy: "11", r: "8" }),
            createElement("path", { className: "ty-text-field__glyph", d: "m21 21-4.34-4.34" }),
          ),
        ) : null,
        createElement("input", { className: "ty-text-field__input", id: (text(p.controlId) ?? `${instance}-input`), type: truthy(p.inputType) ? ({"text":"text","email":"email","url":"url","tel":"tel","number":"number"} as Record<string, string>)[String(p.inputType)] : ({"text":"text","search":"search","password":"password"} as Record<string, string>)[String(p.mode)], name: p.name, placeholder: p.placeholder, autoComplete: p.autoComplete, disabled: truthy(p.disabled) || undefined, readOnly: truthy(p.readOnly) || undefined, required: truthy(p.required) || undefined, "aria-label": (!(slots["label"])) ? (p.accessibleLabel) : undefined, "aria-labelledby": (!(slots["label"])) && (!(truthy(p.accessibleLabel))) ? (p.labelledBy) : undefined, "aria-describedby": [text(p.describedBy) ?? '', (((slots["hint"])) ? `${instance}-hint` : ''), (((slots["error"])) ? `${instance}-error` : ''), (((slots["success"]) && (!(slots["error"]))) ? `${instance}-success` : ''), (((truthy(p.showCounter)) && (truthy(p.maxLength))) ? `${instance}-counter` : '')].filter(Boolean).join(' ') || undefined, "aria-invalid": (truthy(p.invalid) || slots["error"]) ? ("true") : undefined, onChange: (event: ChangeEvent<HTMLInputElement>) => handlers.current.onChange?.({ value: event.currentTarget.value }, event) }),
        (truthy(p.clearable) || p.mode === "search") ? createElement("button", { className: "ty-text-field__clear ty-text-field__action", type: "button", "aria-label": p.clearLabel },
          createElement("svg", { className: "ty-icon", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": "true", focusable: "false" },
            createElement("path", { className: "ty-text-field__glyph", d: "M18 6 6 18" }),
            createElement("path", { className: "ty-text-field__glyph", d: "m6 6 12 12" }),
          ),
        ) : null,
        (p.mode === "password") ? createElement("button", { className: "ty-text-field__reveal ty-text-field__action", type: "button", "aria-label": p.showPasswordLabel, "aria-pressed": "false", disabled: truthy(p.disabled) || undefined },
          createElement("svg", { className: "ty-icon", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": "true", focusable: "false" },
            createElement("g", { className: "ty-text-field__eye" },
              createElement("path", { className: "ty-text-field__glyph", d: "M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0" }),
              createElement("circle", { className: "ty-text-field__glyph", cx: "12", cy: "12", r: "3" }),
            ),
            createElement("g", { className: "ty-text-field__eye-off" },
              createElement("path", { className: "ty-text-field__glyph", d: "M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575 1 1 0 0 1 0 .696 10.747 10.747 0 0 1-1.444 2.49" }),
              createElement("path", { className: "ty-text-field__glyph", d: "M14.084 14.158a3 3 0 0 1-4.242-4.242" }),
              createElement("path", { className: "ty-text-field__glyph", d: "M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151 1 1 0 0 1 0-.696 10.75 10.75 0 0 1 4.446-5.143" }),
              createElement("path", { className: "ty-text-field__glyph", d: "m2 2 20 20" }),
            ),
          ),
        ) : null,
        (slots["success"]) && (!(slots["error"])) ? createElement("svg", { className: "ty-icon ty-text-field__success-mark", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": "true", focusable: "false" },
          createElement("circle", { className: "ty-text-field__glyph", cx: "12", cy: "12", r: "10" }),
          createElement("path", { className: "ty-text-field__glyph", d: "m16 9-5.5 5.5L8 12" }),
        ) : null,
      ),
      (slots["error"]) ? createElement("p", { className: "ty-text-field__error", id: `${instance}-error` },
        createElement("svg", { className: "ty-icon", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": "true", focusable: "false" },
          createElement("circle", { className: "ty-text-field__glyph", cx: "12", cy: "12", r: "10" }),
          createElement("line", { className: "ty-text-field__glyph", x1: "12", y1: "8", x2: "12", y2: "12" }),
          createElement("line", { className: "ty-text-field__glyph", x1: "12", y1: "16", x2: "12.01", y2: "16" }),
        ),
        createElement("span", { className: "ty-text-field__error-text" },
          props.error,
        ),
      ) : null,
      (slots["success"]) && (!(slots["error"])) ? createElement("p", { className: "ty-text-field__success", id: `${instance}-success` },
        props.success,
      ) : null,
      (truthy(p.showCounter)) && (truthy(p.maxLength)) ? createElement("p", { className: "ty-text-field__counter", id: `${instance}-counter` }) : null,
    ))
})
