// Generated by tools/elements/generate.mjs from packages/ui/src/elements/theme-palette/definition.ts. Do not edit.
import { createElement, forwardRef, useEffect, useId, useImperativeHandle, useRef } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)

/** Theme, mode and density picker in the command palette's look; a native <dialog> in the top layer while open. */
export interface TyThemePaletteProps {
  /** Shown (a modal dialog in the top layer). */
  open?: boolean
  /** Apply the stored choice (or the defaults) to the document as soon as the element connects, and again when a default changes. */
  apply?: boolean
  /** localStorage key of the choice ({ theme, mode, density } JSON, as ThemeProvider stores it). Default: `ty-theme`. */
  storageKey?: string
  /** Theme when nothing is stored (a host passes its organization default here). Default: `tympan`. */
  defaultTheme?: string
  /** Mode when nothing is stored. Default: `system`. */
  defaultMode?: "system" | "light" | "dark"
  /** Density when nothing is stored. Default: `default`. */
  defaultDensity?: "compact" | "default" | "comfortable"
  /** Comma-separated theme names to offer; all of them when empty. */
  themes?: string
  /** URL of print-themes.css, linked while a print theme is applied. */
  printStylesheet?: string
  /** Link the font stylesheet a theme names (off: no request to a font host). */
  loadFonts?: boolean
  /** JSON object of translated theme names, by theme name. */
  themeLabels?: string
  /** Accessible name of the dialog and the field. Default: `Appearance`. */
  label?: string
  /** Field placeholder. Default: `Search themes, modes and densities`. */
  placeholder?: string
  /** Shown when nothing matches. Default: `No matches`. */
  emptyLabel?: string
  /** Announced result count; {count} is replaced. Default: `{count} results`. */
  resultsLabel?: string
  /** Heading of the built-in themes. Default: `Themes`. */
  groupPresets?: string
  /** Heading of the print themes. Default: `Print styles`. */
  groupPrint?: string
  /** Heading of the colour modes. Default: `Mode`. */
  groupMode?: string
  /** Heading of the densities. Default: `Density`. */
  groupDensity?: string
  /** Label of the system colour mode. Default: `System`. */
  modeSystem?: string
  /** Label of the light mode. Default: `Light`. */
  modeLight?: string
  /** Label of the dark mode. Default: `Dark`. */
  modeDark?: string
  /** Label of the compact density. Default: `Compact`. */
  densityCompact?: string
  /** Label of the default density. Default: `Default`. */
  densityDefault?: string
  /** Label of the comfortable density. Default: `Comfortable`. */
  densityComfortable?: string
  /** Marks the row in use. Default: `Current`. */
  currentLabel?: string
  /** Footer hint beside ↑↓. Default: `move`. */
  hintNavigate?: string
  /** Footer hint beside ↵. Default: `choose`. */
  hintSelect?: string
  /** Footer hint beside esc. Default: `close`. */
  hintClose?: string
  /** A row was chosen and applied; the detail is the whole appearance. */
  onThemeChange?: (detail: { theme: string; mode: string; density: string }) => void
  /** The palette asks to close (Escape, a press outside, or after a choice). The element closes itself too. */
  onClose?: () => void
  id?: string
  className?: string
}

const DEFAULTS = { storageKey: "ty-theme", defaultTheme: "tympan", defaultMode: "system", defaultDensity: "default", label: "Appearance", placeholder: "Search themes, modes and densities", emptyLabel: "No matches", resultsLabel: "{count} results", groupPresets: "Themes", groupPrint: "Print styles", groupMode: "Mode", groupDensity: "Density", modeSystem: "System", modeLight: "Light", modeDark: "Dark", densityCompact: "Compact", densityDefault: "Default", densityComfortable: "Comfortable", currentLabel: "Current", hintNavigate: "move", hintSelect: "choose", hintClose: "close" } as const

export const TyThemePalette = forwardRef<HTMLElement, TyThemePaletteProps>(function TyThemePalette(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  useEffect(() => {
    const element = host.current
    if (!element) return
    const listeners: Array<[string, EventListener]> = [
      ["ty-theme-change", (event) => handlers.current.onThemeChange?.((event as CustomEvent).detail)],
      ["ty-close", () => handlers.current.onClose?.()],
    ]
    for (const [type, listener] of listeners) element.addEventListener(type, listener)
    return () => { for (const [type, listener] of listeners) element.removeEventListener(type, listener) }
  }, [])
  const p: Record<string, unknown> = { ...DEFAULTS }
  for (const [key, value] of Object.entries(props)) if (value !== undefined) p[key] = value
  return createElement("ty-theme-palette", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "open": truthy(p.open) ? true : undefined, "apply": truthy(p.apply) ? true : undefined, "storage-key": text(p.storageKey), "default-theme": text(p.defaultTheme), "default-mode": text(p.defaultMode), "default-density": text(p.defaultDensity), "themes": text(p.themes), "print-stylesheet": text(p.printStylesheet), "load-fonts": truthy(p.loadFonts) ? true : undefined, "theme-labels": text(p.themeLabels), "label": text(p.label), "placeholder": text(p.placeholder), "empty-label": text(p.emptyLabel), "results-label": text(p.resultsLabel), "group-presets": text(p.groupPresets), "group-print": text(p.groupPrint), "group-mode": text(p.groupMode), "group-density": text(p.groupDensity), "mode-system": text(p.modeSystem), "mode-light": text(p.modeLight), "mode-dark": text(p.modeDark), "density-compact": text(p.densityCompact), "density-default": text(p.densityDefault), "density-comfortable": text(p.densityComfortable), "current-label": text(p.currentLabel), "hint-navigate": text(p.hintNavigate), "hint-select": text(p.hintSelect), "hint-close": text(p.hintClose) })
})
