// Generated by tools/elements/generate.mjs from packages/ui/src/elements/toast/definition.ts. Do not edit.
import { createElement, forwardRef, useEffect, useId, useImperativeHandle, useRef } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)

/** Brief, non-blocking confirmation or warning after an action, shown in a fixed landmark region with one live-region politeness per tone (errors assertive, the rest polite). The element owns the queue and the history; toasts arrive through its imperative API (`show`, `success`/`error`/`warning`/`info`, `dismiss`, `history`), reachable through the host ref. Auto-dismiss pauses on hover, focus and a hidden window; errors and toasts with an action stay until dismissed. */
export interface TyToastProps {
  /** Region position (`data-placement`); `bottom-center` is recommended below 640 px. Default: `top-end`. */
  placement?: "top-end" | "top-center" | "bottom-center"
  /** Toasts shown at once; the rest wait in the queue and appear as earlier ones dismiss. Default: `3`. */
  maxVisible?: number
  /** How many past toasts the history keeps (newest first); feeds the notification history. Default: `50`. */
  historyLimit?: number
  /** Accessible name of the region landmark (the I18nAdapter's toast.region in React). Default: `Notifications`. */
  regionLabel?: string
  /** Accessible name of each toast's dismiss button. Default: `Dismiss notification`. */
  dismissLabel?: string
  /** A toast was dismissed — timeout, dismiss button, Escape, swipe, its action, or a `dismiss(id)` call; the detail carries its id (the spec's `onDismiss`). */
  onDismiss?: (detail: { id: string }) => void
  /** A toast's action was pressed; its `onPress` ran too and the toast dismissed itself. Lets hosts that cannot pass a callback still react to the action. */
  onAction?: (detail: { id: string }) => void
  id?: string
  className?: string
}

const DEFAULTS = { placement: "top-end", maxVisible: 3, historyLimit: 50, regionLabel: "Notifications", dismissLabel: "Dismiss notification" } as const

export const TyToast = forwardRef<HTMLElement, TyToastProps>(function TyToast(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  useEffect(() => {
    const element = host.current
    if (!element) return
    const listeners: Array<[string, EventListener]> = [
      ["ty-toast-dismiss", (event) => handlers.current.onDismiss?.((event as CustomEvent).detail)],
      ["ty-toast-action", (event) => handlers.current.onAction?.((event as CustomEvent).detail)],
    ]
    for (const [type, listener] of listeners) element.addEventListener(type, listener)
    return () => { for (const [type, listener] of listeners) element.removeEventListener(type, listener) }
  }, [])
  const p = {
    placement: props.placement ?? DEFAULTS.placement,
    maxVisible: props.maxVisible ?? DEFAULTS.maxVisible,
    historyLimit: props.historyLimit ?? DEFAULTS.historyLimit,
    regionLabel: props.regionLabel ?? DEFAULTS.regionLabel,
    dismissLabel: props.dismissLabel ?? DEFAULTS.dismissLabel,
  }
  return createElement("ty-toast", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "placement": text(p.placement), "max-visible": text(p.maxVisible), "history-limit": text(p.historyLimit), "region-label": text(p.regionLabel), "dismiss-label": text(p.dismissLabel) })
})
