// Generated by tools/elements/generate.mjs from packages/ui/src/elements/wheel-picker/definition.ts. Do not edit.
import { createElement, forwardRef, useEffect, useId, useImperativeHandle, useRef } from 'react'
import { defineTympanElements } from '../index.ts'

if (typeof window !== 'undefined') defineTympanElements()

const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''
const text = (v: unknown) => (truthy(v) ? String(v) : undefined)

/** Touch-friendly vertical scroller that picks one value from an ordered list by centring it in a selection band (drag or flick scrolls and snaps, a tap selects, the keyboard moves by row, page or ends). With `columns`, several wheels sit side by side for compound values (day, month, year), each with its own width share. */
export interface TyWheelPickerProps {
  /** JSON array of the ordered choices: plain strings, or { "value", "label" } objects when the shown text differs from the reported value. */
  options?: string
  /** Selected value. A value no option holds centres the first row and reports nothing until the wheel moves; programmatic changes animate the wheel to the new row. */
  value?: string
  /** Accessible name of the wheel; with `columns`, of the whole group. */
  label?: string
  /** Rows visible at once; an even number rounds up to the next odd one (minimum 3). Default: `5`. */
  visibleRows?: number
  /** Shown but not changeable: the wheel stays focusable, taps, scrolling and keys do not select. */
  disabled?: boolean
  /** Multi-column form: JSON array of { "label", "options", "value", "share"? }, one wheel per entry; `share` is its relative width. Wins over `options` and `value`. */
  columns?: string
  /** Test hook on the wheel (`data-testid`). */
  testId?: string
  /** The wheel settled on a new value, or a row was activated (tap, arrows, PageUp/PageDown, Home/End, typeahead). `value` is the option's value, not its label; `column` is the wheel's index (0 for a single wheel). */
  onChange?: (detail: { value: string; column: number }) => void
  id?: string
  className?: string
}

const DEFAULTS = { visibleRows: 5 } as const

export const TyWheelPicker = forwardRef<HTMLElement, TyWheelPickerProps>(function TyWheelPicker(props, ref) {
  const generated = useId()
  const instance = `ty${generated.replace(/[^a-zA-Z0-9_-]/g, '')}`
  const handlers = useRef(props)
  handlers.current = props
  const host = useRef<HTMLElement>(null)
  useImperativeHandle(ref, () => host.current as HTMLElement)
  useEffect(() => {
    const element = host.current
    if (!element) return
    const listeners: Array<[string, EventListener]> = [
      ["ty-change", (event) => handlers.current.onChange?.((event as CustomEvent).detail)],
    ]
    for (const [type, listener] of listeners) element.addEventListener(type, listener)
    return () => { for (const [type, listener] of listeners) element.removeEventListener(type, listener) }
  }, [])
  const p = {
    options: props.options,
    value: props.value,
    label: props.label,
    visibleRows: props.visibleRows ?? DEFAULTS.visibleRows,
    disabled: props.disabled,
    columns: props.columns,
    testId: props.testId,
  }
  return createElement("ty-wheel-picker", { ref: host, id: props.id, className: props.className, 'data-ty-instance': instance, "options": text(p.options), "value": text(p.value), "label": text(p.label), "visible-rows": text(p.visibleRows), "disabled": truthy(p.disabled) ? true : undefined, "columns": text(p.columns), "test-id": text(p.testId) })
})
