// Generates, from each custom element's definition (packages/ui/src/elements/*/definition.ts):
//
//   packages/ui/src/elements/react/<Name>.tsx    React wrapper (renders the anatomy, wires the events)
//   crates/tympan-dioxus/src/generated/<name>.rs  Dioxus binding (the same anatomy in rsx)
//   crates/tympan-dioxus/tests/fixtures/...       reference HTML of every example (renderElement)
//   crates/tympan-dioxus/tests/parity/generated.rs one SSR parity test per example
//
// Usage: node tools/elements/generate.mjs [--check]
// --check writes nothing and exits 1 when a generated file is out of date.

import { mkdirSync, readFileSync, writeFileSync, existsSync, readdirSync, rmSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

import { buttonDefinition } from '../../packages/ui/src/elements/button/definition.ts'
import { switchDefinition } from '../../packages/ui/src/elements/switch/definition.ts'
import { themePaletteDefinition } from '../../packages/ui/src/elements/theme-palette/definition.ts'
import { renderElement } from '../../packages/ui/src/elements/anatomy.ts'

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const check = process.argv.includes('--check')

const DEFINITIONS = [
  [buttonDefinition, 'packages/ui/src/elements/button/definition.ts'],
  [switchDefinition, 'packages/ui/src/elements/switch/definition.ts'],
  [themePaletteDefinition, 'packages/ui/src/elements/theme-palette/definition.ts'],
]

// The instance id the fixtures and parity tests render with.
const FIXTURE_INSTANCE = 'i'

const pascal = (s) => s.replace(/(^|[-_ ])([a-z0-9])/g, (_, __, c) => c.toUpperCase())
const camel = (s) => s.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase())
const snake = (s) => s.replace(/-/g, '_').replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase()
const RUST_KEYWORDS = new Set(['type', 'loop', 'match', 'move', 'ref', 'self', 'static', 'struct', 'trait', 'use', 'where', 'async', 'await', 'dyn', 'box', 'crate', 'enum', 'fn', 'for', 'if', 'impl', 'in', 'let', 'mod', 'mut', 'pub', 'return', 'super', 'true', 'false', 'unsafe', 'while', 'yield', 'abstract', 'final', 'override', 'virtual'])
const rustIdent = (s) => (RUST_KEYWORDS.has(s) ? `r#${s}` : s)
const componentName = (def) => def.name.replace(/^Ty/, '')
const rustEnum = (def, prop) => `${componentName(def)}${pascal(prop)}`
const header = (source, comment) => `${comment} Generated by tools/elements/generate.mjs from ${source}. Do not edit.`

// ---------------------------------------------------------------------------
// React
// ---------------------------------------------------------------------------

const REACT_ATTR = { class: 'className', for: 'htmlFor', readonly: 'readOnly', tabindex: 'tabIndex', spellcheck: 'spellCheck', autocomplete: 'autoComplete' }

function tsType(prop) {
  if (prop.type === 'boolean') return 'boolean'
  if (prop.type === 'number') return 'number'
  if (prop.type === 'enum') return prop.values.map((v) => JSON.stringify(v)).join(' | ')
  return 'string'
}

function reactCondition(condition) {
  return condition
    .split('|')
    .map((c) => {
      const negated = c.startsWith('!')
      const body = negated ? c.slice(1) : c
      const expr = body.startsWith('slot:') ? `slots[${JSON.stringify(body.slice(5))}]` : `truthy(p.${camel(body)})`
      return negated ? `!${expr}` : expr
    })
    .join(' || ')
}
const reactWhen = (when) => (when?.length ? when.map((c) => `(${reactCondition(c)})`).join(' && ') : null)

function reactBinding(name, binding, tag) {
  let value
  if ('value' in binding) value = JSON.stringify(binding.value)
  else if ('idref' in binding) value = `\`\${instance}-${binding.idref}\``
  else if (!('kind' in binding)) value = `text(p.${camel(binding.prop)})`
  else if (binding.kind === 'flag') value = `truthy(p.${camel(binding.prop)}) ? '' : undefined`
  else if (binding.kind === 'bool') value = `truthy(p.${camel(binding.prop)}) ? 'true' : undefined`
  else if (binding.kind === 'boolean-attr') {
    // React keeps a checkbox's state as a property; the wrapper is controlled.
    value = name === 'checked' && tag === 'input' ? `Boolean(p.${camel(binding.prop)})` : `truthy(p.${camel(binding.prop)}) || undefined`
  }
  const when = reactWhen(binding.when)
  return [REACT_ATTR[name] ?? name, when ? `${when} ? (${value}) : undefined` : value]
}

function reactNode(def, node, indent) {
  const pad = ' '.repeat(indent)
  if ('slot' in node) return `${pad}${node.slot === 'default' ? 'props.children' : `props.${camel(node.slot)}`}`
  const attrs = []
  if (node.class) attrs.push(['className', JSON.stringify(node.class)])
  for (const [name, binding] of Object.entries(node.attrs ?? {})) attrs.push(reactBinding(name, binding, node.tag))
  for (const event of def.events.filter((e) => e.kind === 'native' && eventTarget(def, e) === node)) {
    const detail = Object.keys(event.detail ?? {})
    const call = detail.length
      ? `(event) => handlers.current.${event.reactProp}?.({ ${detail.map((f) => `${f}: event.currentTarget.${f}`).join(', ')} }, event)`
      : `(event) => handlers.current.${event.reactProp}?.(event)`
    attrs.push([event.reactProp, call])
    if (node.tag === 'input' && Object.keys(node.attrs ?? {}).includes('checked') && event.reactProp !== 'onChange') attrs.push(['onChange', '() => undefined'])
  }
  const props = `{ ${attrs.map(([k, v]) => `${/^[A-Za-z]\w*$/.test(k) ? k : JSON.stringify(k)}: ${v}`).join(', ')} }`
  const children = (node.children ?? []).map((c) => reactNode(def, c, indent + 2))
  const element = children.length ? `createElement(${JSON.stringify(node.tag)}, ${props},\n${children.join(',\n')},\n${pad})` : `createElement(${JSON.stringify(node.tag)}, ${props})`
  const when = reactWhen(node.when)
  return when ? `${pad}${when} ? ${element} : null` : `${pad}${element}`
}

/** The anatomy part a native event is wired on: the first part with that native control. */
function eventTarget(def, event) {
  const wanted = { click: ['button', 'a'], change: ['input', 'select', 'textarea'], input: ['input', 'textarea'] }[event.type] ?? []
  const walk = (node) => {
    if ('slot' in node) return null
    if (wanted.includes(node.tag)) return node
    for (const child of node.children ?? []) {
      const found = walk(child)
      if (found) return found
    }
    return null
  }
  return def.anatomy ? walk(def.anatomy) : null
}

function reactWrapper(def, source) {
  const props = Object.entries(def.props)
  const slots = Object.keys(def.slots ?? {})
  const custom = def.events.filter((e) => e.kind === 'custom')
  const lines = []
  lines.push(header(source, '//'))
  const usesSynthetic = def.events.some((e) => e.kind === 'native')
  const reactImports = ['createElement', 'forwardRef', ...(custom.length ? ['useEffect'] : []), 'useId', 'useImperativeHandle', 'useRef', ...(slots.length ? ['type ReactNode'] : []), ...(usesSynthetic ? ['type SyntheticEvent'] : [])]
  lines.push(`import { ${reactImports.join(', ')} } from 'react'`)
  lines.push(`import { defineTympanElements } from '../index.ts'`)
  lines.push('')
  lines.push(`if (typeof window !== 'undefined') defineTympanElements()`)
  lines.push('')
  lines.push(`const truthy = (v: unknown) => v !== undefined && v !== null && v !== false && v !== ''`)
  lines.push(`const text = (v: unknown) => (truthy(v) ? String(v) : undefined)`)
  if (slots.length) lines.push(`const filled = (v: ReactNode) => v !== undefined && v !== null && v !== false && v !== ''`)
  lines.push('')
  lines.push(`/** ${def.doc} */`)
  lines.push(`export interface ${def.name}Props {`)
  for (const [name, prop] of props) lines.push(`  /** ${prop.doc}${prop.default !== undefined ? ` Default: \`${prop.default}\`.` : ''} */`, `  ${name}?: ${tsType(prop)}`)
  for (const slot of slots) lines.push(`  /** ${def.slots[slot].doc} */`, `  ${slot === 'default' ? 'children' : camel(slot)}?: ReactNode`)
  for (const event of def.events) {
    const detail = Object.entries(event.detail ?? {}).map(([k, t]) => `${k}: ${t}`).join('; ')
    const signature = event.kind === 'custom' ? (detail ? `(detail: { ${detail} }) => void` : '() => void') : detail ? `(detail: { ${detail} }, event: SyntheticEvent) => void` : '(event: SyntheticEvent) => void'
    lines.push(`  /** ${event.doc} */`, `  ${event.reactProp}?: ${signature}`)
  }
  lines.push(`  id?: string`, `  className?: string`, `}`)
  lines.push('')
  const defaults = props.filter(([, p]) => p.default !== undefined).map(([n, p]) => `${n}: ${JSON.stringify(p.default)}`)
  lines.push(`const DEFAULTS = { ${defaults.join(', ')} } as const`)
  lines.push('')
  lines.push(`export const ${def.name} = forwardRef<HTMLElement, ${def.name}Props>(function ${def.name}(props, ref) {`)
  lines.push(`  const generated = useId()`)
  lines.push(`  const instance = \`ty\${generated.replace(/[^a-zA-Z0-9_-]/g, '')}\``)
  lines.push(`  const handlers = useRef(props)`)
  lines.push(`  handlers.current = props`)
  lines.push(`  const host = useRef<HTMLElement>(null)`)
  lines.push(`  useImperativeHandle(ref, () => host.current as HTMLElement)`)
  if (custom.length) {
    lines.push(`  useEffect(() => {`)
    lines.push(`    const element = host.current`)
    lines.push(`    if (!element) return`)
    lines.push(`    const listeners: Array<[string, EventListener]> = [`)
    for (const event of custom) {
      const hasDetail = Object.keys(event.detail ?? {}).length > 0
      lines.push(`      [${JSON.stringify(event.type)}, (${hasDetail ? 'event' : ''}) => handlers.current.${event.reactProp}?.(${hasDetail ? '(event as CustomEvent).detail' : ''})],`)
    }
    lines.push(`    ]`)
    lines.push(`    for (const [type, listener] of listeners) element.addEventListener(type, listener)`)
    lines.push(`    return () => { for (const [type, listener] of listeners) element.removeEventListener(type, listener) }`)
    lines.push(`  }, [])`)
  }
  lines.push(`  const p: Record<string, unknown> = { ...DEFAULTS }`)
  lines.push(`  for (const [key, value] of Object.entries(props)) if (value !== undefined) p[key] = value`)
  if (def.anatomy) lines.push(`  const slots: Record<string, boolean> = { ${slots.map((s) => `${JSON.stringify(s)}: filled(props.${s === 'default' ? 'children' : camel(s)})`).join(', ')} }`)
  const hostAttrs = [`ref: host`, `id: props.id`, `className: props.className`, `'data-ty-instance': instance`]
  // React 19 sets a custom element's own properties (the element defines one
  // per prop) and React 18 writes attributes: `true`/`undefined` means the
  // same to both, `''` or `false` would not.
  for (const [name, prop] of props) hostAttrs.push(`${JSON.stringify(prop.attribute)}: ${prop.type === 'boolean' ? `truthy(p.${name}) ? true : undefined` : `text(p.${name})`}`)
  const anatomy = def.anatomy ? `,\n${reactNode(def, def.anatomy, 4)}` : ''
  lines.push(`  return createElement(${JSON.stringify(def.tag)}, { ${hostAttrs.join(', ')} }${anatomy})`)
  lines.push(`})`)
  lines.push('')
  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Rust / Dioxus
// ---------------------------------------------------------------------------

function rustPropType(def, name, prop) {
  if (prop.type === 'boolean') return 'bool'
  if (prop.type === 'number') return 'Option<f64>'
  if (prop.type === 'enum') return rustEnum(def, name)
  return prop.default !== undefined ? 'String' : 'Option<String>'
}

function rustTruthy(def, name) {
  const prop = def.props[name]
  const id = rustIdent(snake(name))
  if (!prop) throw new Error(`${def.tag}: unknown prop ${name}`)
  if (prop.type === 'boolean') return id
  if (prop.type === 'enum') return 'true'
  if (prop.type === 'number') return `${id}.is_some()`
  return prop.default !== undefined ? `!${id}.is_empty()` : `${id}.as_deref().is_some_and(|v| !v.is_empty())`
}

function rustCondition(def, condition) {
  const alternatives = condition.split('|').map((c) => {
    const negated = c.startsWith('!')
    const body = negated ? c.slice(1) : c
    const expr = body.startsWith('slot:') ? `slot_${snake(body.slice(5))}` : rustTruthy(def, body)
    return negated ? `!(${expr})` : expr
  })
  return alternatives.length > 1 ? `(${alternatives.join(' || ')})` : alternatives[0]
}
const rustWhen = (def, when) => (when?.length ? when.map((c) => rustCondition(def, c)).join(' && ') : null)

function rustText(def, name) {
  const prop = def.props[name]
  const id = rustIdent(snake(name))
  if (prop.type === 'enum') return `Some(${id}.as_str())`
  if (prop.type === 'number') return `${id}.map(|v| v.to_string())`
  if (prop.default !== undefined) return `(!${id}.is_empty()).then_some(${id}.as_str())`
  return `${id}.as_deref().filter(|v| !v.is_empty())`
}

function rustBinding(def, name, binding, tag) {
  let value
  if ('value' in binding) value = `Some(${JSON.stringify(binding.value)})`
  else if ('idref' in binding) value = `Some(format!("{instance}-${binding.idref}"))`
  else if (!('kind' in binding)) value = rustText(def, binding.prop)
  else if (binding.kind === 'flag') value = `(${rustTruthy(def, binding.prop)}).then_some("")`
  else if (binding.kind === 'bool') value = `(${rustTruthy(def, binding.prop)}).then_some("true")`
  else if (binding.kind === 'boolean-attr') {
    // Native boolean attributes are properties in Dioxus (the live state).
    const expr = rustTruthy(def, binding.prop)
    const when = rustWhen(def, binding.when)
    return `${name}: ${when ? `${when} && ${expr}` : expr}`
  }
  const when = rustWhen(def, binding.when)
  return `${JSON.stringify(name)}: ${when ? `if ${when} { ${value} } else { None }` : value}`
}

function rustNode(def, node, indent) {
  const pad = ' '.repeat(indent)
  if ('slot' in node) return `${pad}{${node.slot === 'default' ? 'children.clone()' : `${rustIdent(snake(node.slot))}.clone()`}}`
  const attrs = []
  if (node.class) attrs.push(`class: ${JSON.stringify(node.class)}`)
  for (const [name, binding] of Object.entries(node.attrs ?? {})) attrs.push(rustBinding(def, name, binding, node.tag))
  for (const event of def.events.filter((e) => e.kind === 'native' && eventTarget(def, e) === node)) {
    const handler = rustIdent(event.rustProp)
    const detail = Object.keys(event.detail ?? {})
    if (detail.length) {
      const struct = `${componentName(def)}${pascal(event.type)}`
      attrs.push(`${event.type === 'change' ? 'onchange' : `on${event.type}`}: move |event: FormEvent| { if let Some(handler) = ${handler} { handler.call(${struct} { ${detail.map((f) => `${f}: event.${f}()`).join(', ')} }) } }`)
    } else {
      attrs.push(`on${event.type}: move |event| { if let Some(handler) = ${handler} { handler.call(event) } }`)
    }
  }
  const children = (node.children ?? []).map((c) => rustNode(def, c, indent + 4))
  const body = [...attrs.map((a) => `${pad}    ${a},`), ...children].join('\n')
  const element = `${node.tag} {\n${body}\n${pad}}`
  const when = rustWhen(def, node.when)
  return when ? `${pad}if ${when} {\n${pad}    ${element.replace(/\n/g, `\n    `)}\n${pad}}` : `${pad}${element}`
}

// Dioxus writes these HTML boolean attributes only for a truthy value.
const HTML_BOOLEAN = new Set(['checked', 'disabled', 'hidden', 'open', 'readonly', 'required', 'selected', 'multiple'])

function rustBinding_host(def, name, prop) {
  const id = rustIdent(snake(name))
  if (prop.type === 'boolean') return `${JSON.stringify(prop.attribute)}: ${id}.then_some(${HTML_BOOLEAN.has(prop.attribute) ? '"true"' : '""'})`
  return `${JSON.stringify(prop.attribute)}: ${rustText(def, name)}`
}

function rustBindingFile(def, source) {
  const props = Object.entries(def.props)
  const slots = Object.keys(def.slots ?? {})
  const lines = []
  lines.push(header(source, '//!'))
  lines.push(`//!`, `//! ${def.doc}`)
  lines.push('')
  lines.push('#![allow(unused_parens, unused_variables, unused_imports, clippy::all)]')
  lines.push('')
  lines.push('use dioxus::prelude::*;')
  lines.push('')
  lines.push('use crate::runtime::{has_content, use_custom_event, use_instance_id};')
  lines.push('')
  for (const [name, prop] of props.filter(([, p]) => p.type === 'enum')) {
    const en = rustEnum(def, name)
    lines.push(`/// ${prop.doc}`)
    lines.push('#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]')
    lines.push(`pub enum ${en} {`)
    for (const value of prop.values) {
      if (value === prop.default) lines.push('    #[default]')
      lines.push(`    ${pascal(value)},`)
    }
    lines.push('}', '')
    lines.push(`impl ${en} {`)
    lines.push(`    pub const ALL: [${en}; ${prop.values.length}] = [${prop.values.map((v) => `${en}::${pascal(v)}`).join(', ')}];`, '')
    lines.push(`    /// The attribute value.`)
    lines.push(`    pub const fn as_str(self) -> &'static str {`, '        match self {')
    for (const value of prop.values) lines.push(`            ${en}::${pascal(value)} => ${JSON.stringify(value)},`)
    lines.push('        }', '    }', '')
    lines.push(`    /// The variant for an attribute value.`)
    lines.push(`    pub fn parse(value: &str) -> Option<${en}> {`, `        ${en}::ALL.into_iter().find(|v| v.as_str() == value)`, '    }', '}', '')
  }
  for (const event of def.events.filter((e) => Object.keys(e.detail ?? {}).length)) {
    const struct = `${componentName(def)}${pascal(event.type.replace(/^ty-/, ''))}`
    lines.push(`/// ${event.doc}`)
    lines.push('#[derive(Clone, Debug, PartialEq)]')
    lines.push(`pub struct ${struct} {`)
    for (const [field, type] of Object.entries(event.detail)) lines.push(`    pub ${snake(field)}: ${{ string: 'String', boolean: 'bool', number: 'f64' }[type]},`)
    lines.push('}', '')
  }
  lines.push(`/// ${def.doc}`)
  lines.push('#[allow(clippy::too_many_arguments)]')
  lines.push('#[component]')
  lines.push(`pub fn ${def.name}(`)
  for (const [name, prop] of props) {
    lines.push(`    /// ${prop.doc}`)
    const type = rustPropType(def, name, prop)
    const attr = prop.type === 'string' && prop.default !== undefined ? `#[props(into, default = String::from(${JSON.stringify(prop.default)}))] ` : prop.type === 'string' ? '#[props(into)] ' : prop.type === 'number' ? '' : '#[props(default)] '
    lines.push(`    ${attr}${rustIdent(snake(name))}: ${type},`)
  }
  lines.push('    /// Base of the ids the anatomy needs; a generated one when not given.')
  lines.push('    #[props(into)] instance: Option<String>,')
  lines.push('    #[props(into)] id: Option<String>,')
  lines.push('    #[props(into, default)] class: String,')
  for (const slot of slots) {
    lines.push(`    /// ${def.slots[slot].doc}`)
    lines.push(slot === 'default' ? '    children: Element,' : `    ${rustIdent(snake(slot))}: Option<Element>,`)
  }
  for (const event of def.events) {
    const detail = Object.keys(event.detail ?? {}).length
    const struct = `${componentName(def)}${pascal(event.type.replace(/^ty-/, ''))}`
    const payload = detail ? struct : event.kind === 'native' ? 'MouseEvent' : '()'
    lines.push(`    /// ${event.doc}`)
    lines.push(`    ${rustIdent(event.rustProp)}: Option<EventHandler<${payload}>>,`)
  }
  lines.push(') -> Element {')
  lines.push('    let instance = use_instance_id(instance);')
  for (const slot of slots) lines.push(`    let slot_${snake(slot)} = ${slot === 'default' ? 'has_content(&children)' : `${rustIdent(snake(slot))}.is_some()`};`)
  const custom = def.events.filter((e) => e.kind === 'custom')
  if (custom.length) {
    lines.push('    let mut host = use_signal(|| None::<std::rc::Rc<MountedData>>);')
    for (const event of custom) {
      const detail = Object.entries(event.detail ?? {})
      const struct = `${componentName(def)}${pascal(event.type.replace(/^ty-/, ''))}`
      const build = detail.length ? `|detail: crate::runtime::Detail| ${struct} { ${detail.map(([f, t]) => `${snake(f)}: detail.${{ string: 'string', boolean: 'boolean', number: 'number' }[t]}(${JSON.stringify(f)})`).join(', ')} }` : '|_detail: crate::runtime::Detail| ()'
      lines.push(`    use_custom_event(host, ${JSON.stringify(event.type)}, ${rustIdent(event.rustProp)}, ${build});`)
    }
  }
  const hostAttrs = ['"id": id.clone()', `"class": (!class.is_empty()).then_some(class.clone())`, '"data-ty-instance": instance.clone()']
  for (const [name, prop] of props) hostAttrs.push(rustBinding_host(def, name, prop))
  if (custom.length) hostAttrs.push('onmounted: move |event: MountedEvent| host.set(Some(event.data()))')
  lines.push('    rsx! {')
  lines.push(`        ${def.tag} {`)
  for (const attr of hostAttrs) lines.push(`            ${attr},`)
  if (def.anatomy) lines.push(rustNode(def, def.anatomy, 12))
  lines.push('        }')
  lines.push('    }')
  lines.push('}')
  lines.push('')
  return lines.join('\n')
}

function rustExampleCall(def, example) {
  const args = []
  for (const [name, value] of Object.entries(example.props)) {
    const prop = def.props[name]
    const id = rustIdent(snake(name))
    if (prop.type === 'enum') args.push(`${id}: ${rustEnum(def, name)}::${pascal(value)}`)
    else if (prop.type === 'boolean') args.push(`${id}: ${value}`)
    else if (prop.type === 'number') args.push(`${id}: ${Number(value)}f64`)
    else args.push(`${id}: ${JSON.stringify(String(value))}`)
  }
  args.push(`instance: ${JSON.stringify(FIXTURE_INSTANCE)}`)
  for (const [slot, content] of Object.entries(example.slots)) {
    if (slot === 'default') continue
    args.push(`${rustIdent(snake(slot))}: rsx! { ${JSON.stringify(content)} }`)
  }
  const children = example.slots.default ? ` ${JSON.stringify(example.slots.default)}` : ''
  return `${def.name} { ${args.join(', ')},${children} }`
}

function parityTests() {
  const lines = []
  lines.push(header('packages/ui/src/elements/*/definition.ts', '//'))
  lines.push('//')
  lines.push('// Every example of every enhancing element, rendered by the generated')
  lines.push('// Dioxus binding (SSR), must match the reference HTML the definition')
  lines.push('// renders (tests/fixtures), which the React wrapper and the element')
  lines.push("// itself are tested against on the TypeScript side.")
  lines.push('')
  lines.push('use dioxus::prelude::*;')
  lines.push('use tympan_dioxus::*;')
  lines.push('')
  lines.push('use super::common;')
  lines.push('')
  for (const [def] of DEFINITIONS) {
    if (def.kind !== 'enhancing') continue
    for (const example of def.examples) {
      const fn = `${snake(componentName(def))}_${snake(example.name)}`
      lines.push('#[test]')
      lines.push(`fn ${fn}() {`)
      lines.push(`    fn app() -> Element {`)
      lines.push(`        rsx! { ${rustExampleCall(def, example)} }`)
      lines.push('    }')
      lines.push(`    common::assert_matches_fixture(app, ${JSON.stringify(`${def.tag}/${example.name}.html`)});`)
      lines.push('}')
      lines.push('')
    }
  }
  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Write
// ---------------------------------------------------------------------------

const outputs = new Map()
const reactDir = 'packages/ui/src/elements/react'
const rustDir = 'crates/tympan-dioxus/src/generated'
const fixtureDir = 'crates/tympan-dioxus/tests/fixtures'

const reactIndex = [header('packages/ui/src/elements/*/definition.ts', '//')]
const rustMod = [header('packages/ui/src/elements/*/definition.ts', '//!'), '']
for (const [def, source] of DEFINITIONS) {
  outputs.set(`${reactDir}/${def.name}.ts`, reactWrapper(def, source))
  reactIndex.push(`export { ${def.name}, type ${def.name}Props } from './${def.name}.ts'`)
  const module = snake(componentName(def))
  outputs.set(`${rustDir}/${module}.rs`, rustBindingFile(def, source))
  rustMod.push(`pub mod ${module};`, `pub use ${module}::*;`)
  for (const example of def.examples) {
    const slots = Object.fromEntries(Object.entries(example.slots).map(([k, v]) => [k, v.replace(/&/g, '&amp;').replace(/</g, '&lt;')]))
    outputs.set(`${fixtureDir}/${def.tag}/${example.name}.html`, `${renderElement(def, example.props, slots, FIXTURE_INSTANCE)}\n`)
  }
}
outputs.set(`${reactDir}/index.ts`, `${reactIndex.join('\n')}\n`)
outputs.set(`${rustDir}/mod.rs`, `${rustMod.join('\n')}\n`)
outputs.set('crates/tympan-dioxus/tests/parity/generated.rs', parityTests())

let stale = 0
for (const [file, content] of outputs) {
  const path = join(root, file)
  const current = existsSync(path) ? readFileSync(path, 'utf8') : null
  if (current === content) continue
  if (check) {
    console.error(`elements: ${file} is out of date (run node tools/elements/generate.mjs)`)
    stale++
    continue
  }
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, content)
}
// Fixtures of examples that no longer exist.
for (const tag of existsSync(join(root, fixtureDir)) ? readdirSync(join(root, fixtureDir)) : []) {
  for (const file of readdirSync(join(root, fixtureDir, tag))) {
    const rel = `${fixtureDir}/${tag}/${file}`
    if (outputs.has(rel)) continue
    if (check) {
      console.error(`elements: ${rel} has no example`)
      stale++
    } else rmSync(join(root, rel))
  }
}
if (check && stale) process.exit(1)
console.log(`elements: ${check ? 'checked' : 'wrote'} ${outputs.size} generated files from ${DEFINITIONS.length} definitions (${relative(root, reactDir)}, ${rustDir}, ${fixtureDir})`)
