//! Dioxus 0.7 bindings of Tympan's custom elements.
//!
//! Each component (`TyButton`, `TySwitch`, `TyThemePalette`, …) is
//! generated by `tools/elements/generate.mjs` from the element's single
//! definition in `packages/ui/src/elements/*/definition.ts`, the same
//! definition the React wrappers are generated from: typed props (enums for
//! the variants), typed event handlers, and — for the enhancing elements —
//! the element's light-DOM anatomy rendered in `rsx!`, so the markup is
//! Tympan's and the page works before the element script has loaded. The
//! custom element then adds the behaviour (see the design note
//! `docs/design/single-source-components.md`).
//!
//! A host serves [`tympan_tokens::assets`] (the stylesheet and the element
//! bundle) and renders [`TympanHead`] once. FSL-1.1-ALv2.

#[rustfmt::skip]
mod generated;
pub mod elements;
pub mod runtime;

pub use generated::*;
pub use tympan_tokens as tokens;

use dioxus::prelude::*;

/// Links Tympan's stylesheet and loads its custom elements from `base`
/// (where the host serves [`tympan_tokens::assets::ALL`], e.g. `/tympan`),
/// with `version` as a cache-busting query. Both go into the document head,
/// in the order this renders relative to the host's own head elements, so a
/// host that declares its `@layer` order in its own stylesheet renders that
/// first.
///
/// `script: false` omits the custom-element bundle — the choice of a host
/// whose markup comes entirely from [`elements`] (the native Dioxus ports):
/// loading the script over native-rendered `<ty-*>` hosts would upgrade
/// them and run the behaviour twice.
#[component]
pub fn TympanHead(
    #[props(into)] base: String,
    #[props(into, default)] version: String,
    #[props(default = true)] script: bool,
) -> Element {
    let query = if version.is_empty() {
        String::new()
    } else {
        format!("?v={version}")
    };
    rsx! {
        document::Stylesheet { href: "{base}/styles.css{query}" }
        if script {
            document::Script { r#type: "module", src: "{base}/elements.js{query}" }
        }
    }
}
