//! Dioxus 0.7 bindings of Tympan's custom elements.
//!
//! Each component (`TyButton`, `TySwitch`, `TyThemePalette`, …) is
//! generated by `tools/elements/generate.mjs` from the element's single
//! definition in `packages/ui/src/elements/*/definition.ts`, the same
//! definition the React wrappers are generated from: typed props (enums for
//! the variants), typed event handlers, and — for the enhancing elements —
//! the element's light-DOM anatomy rendered in `rsx!`, so the markup is
//! Tympan's and the page works before the element script has loaded. The
//! custom element then adds the behaviour (see the design note
//! `docs/design/single-source-components.md`).
//!
//! A host serves [`tympan_tokens::assets`] (the stylesheet and the element
//! bundle) and renders [`TympanHead`] once. FSL-1.1-ALv2.

#[rustfmt::skip]
mod generated;
pub mod runtime;

pub use generated::*;
pub use tympan_tokens as tokens;

use dioxus::prelude::*;

/// Links Tympan's stylesheet and loads its custom elements from `base`
/// (where the host serves [`tympan_tokens::assets::ALL`], e.g. `/tympan`),
/// with `version` as a cache-busting query.
#[component]
pub fn TympanHead(#[props(into)] base: String, #[props(into, default)] version: String) -> Element {
    let query = if version.is_empty() {
        String::new()
    } else {
        format!("?v={version}")
    };
    rsx! {
        link { rel: "stylesheet", href: "{base}/styles.css{query}" }
        script { r#type: "module", src: "{base}/elements.js{query}" }
    }
}
