// Theme customizer: tailor seeds, radius, contrast, glass and CTA live, see
// every component in light and dark, check contrast, export DTCG and CSS.
import {
  fakhirPreset,
  tympanPreset,
  generateThemeCss,
  highContrastPreset,
  neutralPreset,
  printThemePresets,
  resolveTheme,
  themeToDtcg,
  type ContrastResult,
  type SeedName,
  type ThemeConfig,
} from '@datatechsolutions/tympan-tokens'
import { useEffect, useId, useMemo, useRef, useState } from 'react'
import { Button, NativeSelect, ProofBadge, SegmentedControl, Switch, TextArea, ThemeScope, useTheme } from '../../src'
import { GalleryToolbar } from './Gallery'
import { Showcase } from './Showcase'

const BUILT_IN: Record<string, ThemeConfig> = {
  tympan: tympanPreset,
  fakhir: fakhirPreset,
  neutral: neutralPreset,
  'high-contrast': highContrastPreset,
}
const PRESETS: Record<string, ThemeConfig> = { ...BUILT_IN, ...Object.fromEntries(printThemePresets.map((p) => [p.name, p])) }
const PRESET_GROUPS = [
  { label: 'Built-in', options: Object.keys(BUILT_IN) },
  { label: 'Print styles', options: printThemePresets.map((p) => ({ value: p.name, label: p.label ?? p.name })) },
]
const CUSTOM = 'custom'
const SEEDS: SeedName[] = ['brand', 'neutral', 'danger', 'warning', 'success', 'info']

function Range(props: { label: string; value: number; min: number; max: number; step: number; onChange: (v: number) => void; format?: (v: number) => string }) {
  const id = useId()
  return (
    <div className="ty-gallery-range">
      <label htmlFor={id}>{props.label}</label>
      <input id={id} type="range" min={props.min} max={props.max} step={props.step} value={props.value} onChange={(e) => props.onChange(Number(e.target.value))} />
      <output htmlFor={id}>{props.format ? props.format(props.value) : props.value}</output>
    </div>
  )
}

function download(name: string, text: string, type: string) {
  const url = URL.createObjectURL(new Blob([text], { type }))
  const a = document.createElement('a')
  a.href = url
  a.download = name
  a.click()
  URL.revokeObjectURL(url)
}

function worst(report: ContrastResult[]) {
  return [...report].sort((a, b) => a.ratio / a.min - b.ratio / b.min).slice(0, 5)
}

export function Customizer() {
  const t = useTheme()
  const previous = useRef(t.theme)
  const [presetName, setPresetName] = useState('tympan')
  const [config, setConfig] = useState<ThemeConfig>(() => structuredClone(tympanPreset))
  const [usePins, setUsePins] = useState(true)

  // The whole document uses the tailored theme while the customizer is open, so overlays match.
  useEffect(() => {
    const before = previous.current
    t.setTheme(CUSTOM)
    return () => t.setTheme(before === CUSTOM ? 'tympan' : before)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const effective: ThemeConfig = useMemo(
    () => ({ ...config, name: CUSTOM, label: 'Custom', pins: usePins ? config.pins : undefined, ctaPins: usePins ? config.ctaPins : undefined }),
    [config, usePins],
  )
  const css = useMemo(() => generateThemeCss(effective), [effective])
  const light = useMemo(() => resolveTheme(effective, 'light'), [effective])
  const dark = useMemo(() => resolveTheme(effective, 'dark'), [effective])
  const all = [...light.report, ...dark.report]
  const failing = all.filter((r) => !r.pass)
  const hasPins = !!config.pins

  const setSeed = (seed: SeedName, key: 'hue' | 'chroma', value: number) => {
    setUsePins(false)
    setConfig((c) => ({ ...c, seeds: { ...c.seeds, [seed]: { ...c.seeds[seed], [key]: value } } }))
  }

  const loadPreset = (name: string) => {
    setPresetName(name)
    setConfig(structuredClone(PRESETS[name]!))
    setUsePins(true)
  }

  const exportName = `tympan-theme-${presetName}-custom`
  const standaloneCss = useMemo(() => generateThemeCss(effective, { asDefault: true, densities: true }), [effective])
  const dtcg = useMemo(
    () =>
      JSON.stringify(
        {
          $description: 'Tailored Tympan theme generated by the @datatechsolutions/tympan-tokens customizer (W3C DTCG 2025.10 format).',
          $extensions: { 'br.com.datatechsolutions.tympan': { config: effective } },
          light: themeToDtcg(light),
          dark: themeToDtcg(dark),
        },
        null,
        2,
      ),
    [effective, light, dark],
  )

  return (
    <div className="ty-gallery">
      <style data-ty-customizer>{css}</style>
      {effective.fontsUrl ? <link rel="stylesheet" href={effective.fontsUrl} /> : null}
      <GalleryToolbar extra={<span className="ty-gallery-toolbar__note">Theme: custom</span>} />
      <div className="ty-gallery-customizer">
        <aside className="ty-gallery-customizer__panel" aria-labelledby="customizer-title">
          <h1 id="customizer-title" className="ty-gallery-customizer__title">
            Theme customizer
          </h1>
          <NativeSelect label="Start from preset" groups={PRESET_GROUPS} value={presetName} onChange={loadPreset} />
          {hasPins ? (
            <Switch
              label="Pin design-direction colours"
              description="Keeps the exact §2.3 colours; changing a seed turns this off."
              isSelected={usePins}
              onChange={setUsePins}
              layout="tile"
            />
          ) : null}
          {SEEDS.map((seed) => (
            <fieldset key={seed} className="ty-gallery-seed">
              <legend>{seed}</legend>
              <span className="ty-gallery-swatch" style={{ background: `oklch(0.6 ${config.seeds[seed].chroma} ${config.seeds[seed].hue})` }} aria-hidden="true" />
              <Range label="Hue" min={0} max={360} step={1} value={config.seeds[seed].hue} onChange={(v) => setSeed(seed, 'hue', v)} format={(v) => `${Math.round(v)}°`} />
              <Range
                label="Chroma"
                min={0}
                max={seed === 'neutral' ? 0.05 : 0.3}
                step={0.001}
                value={config.seeds[seed].chroma}
                onChange={(v) => setSeed(seed, 'chroma', v)}
                format={(v) => v.toFixed(3)}
              />
            </fieldset>
          ))}
          <Range label="Radius base (px)" min={0} max={20} step={1} value={config.radius} onChange={(v) => setConfig((c) => ({ ...c, radius: v }))} />
          <SegmentedControl label="Contrast" options={['default', 'high']} value={config.contrast} onChange={(v) => setConfig((c) => ({ ...c, contrast: v as ThemeConfig['contrast'] }))} />
          <SegmentedControl label="Call to action" options={['gradient', 'solid']} value={config.cta} onChange={(v) => setConfig((c) => ({ ...c, cta: v as ThemeConfig['cta'] }))} />
          <Switch label="Glass surfaces" isSelected={config.glass} onChange={(glass) => setConfig((c) => ({ ...c, glass }))} />

          <section className="ty-gallery-report" aria-labelledby="report-title">
            <h2 id="report-title">Contrast (WCAG 2.2 AA)</h2>
            <p>
              <ProofBadge state={failing.length ? 'refuted' : 'proved'} label={failing.length ? `${failing.length} failing` : 'all pass'} /> {all.length} pairs in light and dark.
            </p>
            <details>
              <summary>Closest to the limit, and APCA Lc (informational)</summary>
              <table className="ty-gallery-report__table">
                <caption className="ty-visually-hidden">Pairs closest to the WCAG limit</caption>
                <thead>
                  <tr>
                    <th scope="col">Pair</th>
                    <th scope="col">WCAG</th>
                    <th scope="col">APCA Lc</th>
                  </tr>
                </thead>
                <tbody>
                  {[...worst(light.report).map((r) => ['light', r] as const), ...worst(dark.report).map((r) => ['dark', r] as const)].map(([mode, r]) => (
                    <tr key={`${mode}-${r.fg}-${r.over.join()}`}>
                      <td>
                        {mode}: {r.fg} on {r.over[0]}
                      </td>
                      <td>
                        {r.ratio}:1 (≥ {r.min})
                      </td>
                      <td>{r.apca}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </details>
          </section>

          <section className="ty-gallery-export" aria-labelledby="export-title">
            <h2 id="export-title">Export</h2>
            <div className="ty-gallery-row">
              <Button onPress={() => download(`${exportName}.tokens.json`, dtcg, 'application/json')}>DTCG JSON</Button>
              <Button onPress={() => download(`${exportName}.css`, standaloneCss, 'text/css')}>CSS</Button>
            </div>
            <TextArea label="Theme config" monospace readOnly rows={6} value={JSON.stringify({ ...effective, name: presetName }, null, 2)} />
          </section>
        </aside>
        <main className="ty-gallery-columns" aria-label="Preview">
          {(['light', 'dark'] as const).map((mode) => (
            <ThemeScope key={mode} theme={CUSTOM} mode={mode} density={t.density} className="ty-gallery-column" data-gallery-mode={mode}>
              <p className="ty-gallery-column__label">custom · {mode}</p>
              <Showcase scope={`custom-${mode}`} />
            </ThemeScope>
          ))}
        </main>
      </div>
    </div>
  )
}
