// Strings of the provenance viewer. English is complete; pt-BR is the
// product's language. Hosts override through `labels` or FlowMessagesProvider.

import { defineLabels } from '../internal/labels'
import type { ProofKey, ProvActorKind, ProvKind, ProvRelation } from './model'

export interface ProvenanceLabels {
  graphName: string
  graphRole: string
  treeName: string
  queryBar: string
  focus: string
  focusAll: string
  direction: string
  backward: string
  forward: string
  both: string
  hops: string
  view: string
  viewGraph: string
  viewTree: string
  filters: string
  filtersActive: string
  filterKinds: string
  filterActors: string
  filterActorName: string
  filterProof: string
  actorsAsNodes: string
  clearFilters: string
  legend: string
  inspector: string
  closeInspector: string
  cameFrom: string
  madeFrom: string
  noRelations: string
  details: string
  when: string
  attributedTo: string
  /** Accessible name of a node: kind, title, proof word, actor. */
  nodeName: string
  actorNodeName: string
  /** Tree row relation prefix, e.g. "was derived from". */
  treeVia: string
  emptyTitle: string
  emptyText: string
  isolated: string
  focusFiltered: string
  noMatches: string
  deep: string
  loading: string
  errorTitle: string
  retry: string
  count: string
  kinds: Record<ProvKind, string>
  relations: Record<ProvRelation, string>
  /** Relation read from the older end ("used by", "source of"). */
  relationsReversed: Record<ProvRelation, string>
  proof: Record<ProofKey, string>
  actorKinds: Record<ProvActorKind, string>
}

export const defaultProvenanceLabels: ProvenanceLabels = {
  graphName: 'Provenance graph',
  graphRole: 'graph',
  treeName: 'Provenance list',
  queryBar: 'Provenance query',
  focus: 'Item in focus',
  focusAll: 'Whole graph',
  direction: 'Direction',
  backward: 'Back to sources',
  forward: 'Forward to uses',
  both: 'Both',
  hops: 'Steps',
  view: 'View',
  viewGraph: 'Graph',
  viewTree: 'List',
  filters: 'Filters',
  filtersActive: 'Filters ({count, plural, one {# active} other {# active}})',
  filterKinds: 'Item types',
  filterActors: 'Who acted',
  filterActorName: 'Actor name',
  filterProof: 'Proof state',
  actorsAsNodes: 'Show actors as nodes',
  clearFilters: 'Clear filters',
  legend: 'Proof states',
  inspector: 'Evidence',
  closeInspector: 'Close evidence',
  cameFrom: 'Came from',
  madeFrom: 'Used by',
  noRelations: 'None',
  details: 'Details',
  when: 'When',
  attributedTo: 'Attributed to',
  nodeName: '{kind}: {title}, {proof}, {actor}',
  actorNodeName: '{kind}: {name}',
  treeVia: '{relation}',
  emptyTitle: 'No provenance yet',
  emptyText: 'Nothing has been recorded for this project. Items appear here as searches, sources and assertions are registered.',
  isolated: 'This item has no recorded links.',
  focusFiltered: 'The item in focus is hidden by the filters.',
  noMatches: 'No item matches these filters.',
  deep: 'This view is large ({count} items). Reduce the number of steps to read it more easily.',
  loading: 'Loading the provenance graph',
  errorTitle: 'The provenance could not be loaded',
  retry: 'Try again',
  count: '{count, plural, one {# item} other {# items}}',
  kinds: {
    query: 'query',
    retrieval: 'retrieval',
    source: 'source',
    assertion: 'assertion',
    record: 'record',
    analysis: 'analysis',
    edition: 'edition',
    manuscript: 'manuscript sentence',
  },
  relations: { wasDerivedFrom: 'was derived from', used: 'used', wasGeneratedBy: 'was generated by', wasAttributedTo: 'was attributed to' },
  relationsReversed: { wasDerivedFrom: 'source of', used: 'used by', wasGeneratedBy: 'generated', wasAttributedTo: 'responsible for' },
  proof: { proved: 'proved', pending: 'pending', refuted: 'refuted', not_disclosed: 'not disclosed', none: 'no proof' },
  actorKinds: { person: 'person', agent: 'agent', system: 'system' },
}

export const provenanceLabelsPtBR: ProvenanceLabels = {
  graphName: 'Grafo de proveniência',
  graphRole: 'grafo',
  treeName: 'Lista de proveniência',
  queryBar: 'Consulta de proveniência',
  focus: 'Item em foco',
  focusAll: 'Grafo inteiro',
  direction: 'Direção',
  backward: 'Até as fontes',
  forward: 'Até os usos',
  both: 'As duas',
  hops: 'Saltos',
  view: 'Vista',
  viewGraph: 'Grafo',
  viewTree: 'Lista',
  filters: 'Filtros',
  filtersActive: 'Filtros ({count, plural, one {# ativo} other {# ativos}})',
  filterKinds: 'Tipos de item',
  filterActors: 'Quem agiu',
  filterActorName: 'Nome do ator',
  filterProof: 'Estado de prova',
  actorsAsNodes: 'Mostrar atores como nós',
  clearFilters: 'Limpar filtros',
  legend: 'Estados de prova',
  inspector: 'Evidência',
  closeInspector: 'Fechar evidência',
  cameFrom: 'Veio de',
  madeFrom: 'Usado por',
  noRelations: 'Nenhum',
  details: 'Detalhes',
  when: 'Quando',
  attributedTo: 'Atribuído a',
  nodeName: '{kind}: {title}, {proof}, {actor}',
  actorNodeName: '{kind}: {name}',
  treeVia: '{relation}',
  emptyTitle: 'Nenhuma proveniência ainda',
  emptyText: 'Nada foi registrado neste projeto. Os itens aparecem aqui à medida que buscas, fontes e asserções são registradas.',
  isolated: 'Este item não tem ligações registradas.',
  focusFiltered: 'O item em foco está oculto pelos filtros.',
  noMatches: 'Nenhum item com esses filtros.',
  deep: 'Esta vista é grande ({count} itens). Reduza o número de saltos para ler melhor.',
  loading: 'Carregando o grafo de proveniência',
  errorTitle: 'Não foi possível carregar a proveniência',
  retry: 'Tentar de novo',
  count: '{count, plural, one {# item} other {# itens}}',
  kinds: {
    query: 'consulta',
    retrieval: 'recuperação',
    source: 'fonte',
    assertion: 'asserção',
    record: 'registro',
    analysis: 'análise',
    edition: 'edição',
    manuscript: 'frase do manuscrito',
  },
  relations: { wasDerivedFrom: 'derivou de', used: 'usou', wasGeneratedBy: 'gerado por', wasAttributedTo: 'atribuído a' },
  relationsReversed: { wasDerivedFrom: 'origem de', used: 'usado por', wasGeneratedBy: 'gerou', wasAttributedTo: 'responsável por' },
  proof: { proved: 'provada', pending: 'pendente', refuted: 'refutada', not_disclosed: 'não informada', none: 'sem prova' },
  actorKinds: { person: 'pessoa', agent: 'agente', system: 'sistema' },
}

export const provenanceLabelsEs: ProvenanceLabels = {
  graphName: 'Grafo de procedencia',
  graphRole: 'grafo',
  treeName: 'Lista de procedencia',
  queryBar: 'Consulta de procedencia',
  focus: 'Elemento en foco',
  focusAll: 'Grafo completo',
  direction: 'Dirección',
  backward: 'Hacia las fuentes',
  forward: 'Hacia los usos',
  both: 'Ambas',
  hops: 'Pasos',
  view: 'Vista',
  viewGraph: 'Grafo',
  viewTree: 'Lista',
  filters: 'Filtros',
  filtersActive: 'Filtros ({count, plural, one {# activo} other {# activos}})',
  filterKinds: 'Tipos de elemento',
  filterActors: 'Quién actuó',
  filterActorName: 'Nombre del actor',
  filterProof: 'Estado de prueba',
  actorsAsNodes: 'Mostrar actores como nodos',
  clearFilters: 'Borrar filtros',
  legend: 'Estados de prueba',
  inspector: 'Evidencia',
  closeInspector: 'Cerrar evidencia',
  cameFrom: 'Proviene de',
  madeFrom: 'Usado por',
  noRelations: 'Ninguno',
  details: 'Detalles',
  when: 'Cuándo',
  attributedTo: 'Atribuido a',
  nodeName: '{kind}: {title}, {proof}, {actor}',
  actorNodeName: '{kind}: {name}',
  treeVia: '{relation}',
  emptyTitle: 'Todavía no hay procedencia',
  emptyText: 'No se ha registrado nada en este proyecto. Los elementos aparecen aquí a medida que se registran búsquedas, fuentes y aserciones.',
  isolated: 'Este elemento no tiene vínculos registrados.',
  focusFiltered: 'El elemento en foco está oculto por los filtros.',
  noMatches: 'Ningún elemento coincide con estos filtros.',
  deep: 'Esta vista es grande ({count} elementos). Reduzca el número de pasos para leerla mejor.',
  loading: 'Cargando el grafo de procedencia',
  errorTitle: 'No se pudo cargar la procedencia',
  retry: 'Reintentar',
  count: '{count, plural, one {# elemento} other {# elementos}}',
  kinds: {
    query: 'consulta',
    retrieval: 'recuperación',
    source: 'fuente',
    assertion: 'aserción',
    record: 'registro',
    analysis: 'análisis',
    edition: 'edición',
    manuscript: 'frase del manuscrito',
  },
  relations: { wasDerivedFrom: 'derivó de', used: 'usó', wasGeneratedBy: 'generado por', wasAttributedTo: 'atribuido a' },
  relationsReversed: { wasDerivedFrom: 'origen de', used: 'usado por', wasGeneratedBy: 'generó', wasAttributedTo: 'responsable de' },
  proof: { proved: 'probada', pending: 'pendiente', refuted: 'refutada', not_disclosed: 'no informada', none: 'sin prueba' },
  actorKinds: { person: 'persona', agent: 'agente', system: 'sistema' },
}

export const provenanceLabels = defineLabels<ProvenanceLabels>('provenance', { en: defaultProvenanceLabels, 'pt-BR': provenanceLabelsPtBR, es: provenanceLabelsEs })
