// Writes dist/fonts.css: the @font-face rules (font-display swap, unicode-range
// slices, URLs relative to this package's fonts/) of the CJK Noto families.
// The files and fonts/manifest.json come from
// packages/tokens/scripts/fetch-fonts.mjs, which also lists the specs
// (CJK_FONT_SPECS in packages/tokens/src/fonts.ts).
//
//   node scripts/build.mjs           # write dist/fonts.css
//   node scripts/build.mjs --check   # only validate the manifest and files
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { CJK_FONT_FAMILIES, CJK_FONT_SPECS, fontFaceCss } from '../../tokens/src/fonts.ts'

const pkg = join(dirname(fileURLToPath(import.meta.url)), '..')
const manifest = JSON.parse(readFileSync(join(pkg, 'fonts', 'manifest.json'), 'utf8'))

const errors = []
for (const spec of CJK_FONT_SPECS) {
  const faces = manifest.specs[spec]
  if (!faces) errors.push(`font spec not bundled, run packages/tokens/scripts/fetch-fonts.mjs: ${spec}`)
  else for (const id of faces) if (!existsSync(join(pkg, 'fonts', manifest.faces[id].file))) errors.push(`font file missing: fonts/${manifest.faces[id].file}`)
}
for (const [family, f] of Object.entries(manifest.families)) {
  if (!CJK_FONT_FAMILIES.includes(family)) errors.push(`not a CJK family, belongs in packages/tokens: ${family}`)
  if (f.license !== 'OFL-1.1' || !existsSync(join(pkg, 'fonts', f.licenseFile))) errors.push(`licence missing or not OFL-1.1: ${family}`)
}
if (errors.length) {
  console.error(errors.join('\n'))
  process.exit(1)
}
if (process.argv.includes('--check')) {
  console.log(`fonts-cjk: ${CJK_FONT_SPECS.length} specs, ${Object.keys(manifest.faces).length} files ok`)
  process.exit(0)
}
const banner = '/* @datatechsolutions/tympan-fonts-cjk: @font-face rules for the CJK Noto families (SIL OFL 1.1, see fonts/manifest.json and THIRD_PARTY_NOTICES.md), generated by scripts/build.mjs. Files load only when text uses a face and falls in its unicode-range. Do not edit. */'
mkdirSync(join(pkg, 'dist'), { recursive: true })
writeFileSync(join(pkg, 'dist', 'fonts.css'), `${banner}\n${fontFaceCss(manifest, CJK_FONT_SPECS, '../fonts/')}\n`)
console.log(`fonts-cjk: dist/fonts.css (${CJK_FONT_SPECS.length} families)`)
